### ISSUE TITLE
Add a 'Diff against last checkpoint' button in the version control

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#100]
<img width="1086" alt="Screenshot 2020-07-09 at 15 00 35" src="https://user-images.githubusercontent.com/16639049/87058874-87a8da00-c200-11ea-8dc3-e16e1d9dba15.png">

Adding a button for the most common operation would be really handy. At the moment, doing this operation requires 4 awkward clicks :(

**Comment by yaustar** [comment]
I'm imagining this:
![image](https://user-images.githubusercontent.com/16639049/121175414-ecc2e080-c852-11eb-9d8b-bf1d7a1c8c6c.png)

**Comment by vkalpias** [comment]
At the moment we do not know if there are any changes without running a diff. Do you think we should always show this 'Changes since last checkpoint' bit regardless if there might be no changes?

**Comment by yaustar** [comment]
I think so yes as it matches the listing in the Diff sub panel view

**Comment by yaustar** [comment]
Released to production 1.18.12
