### ISSUE TITLE
Feature Requests: Buy Additional Space, Folder Creation and Search Bar

### ISSUE THREAD

**Issue by AlbertoMalavasi** [playcanvas/editor#1003]
There are three feature requests that we would like to make:

1. The possibility of upgrading the available storage capacity for a specific ORG. 
2. The possibility of creating folders to store projects. It would be much easier to manage our data if we could categorize and group related projects together.
3. Add a search bar to the interface, which would help us navigate through our projects with greater ease.

**Comment by yaustar** [comment]
1. Email us at support@playcanvas.com and we can help with that.
2 + 3. Duplication of https://github.com/playcanvas/editor/issues/156
