### ISSUE TITLE
Expose 'Opacity Fades Specular' on StandardMaterial

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#1007]
It seems this is not enabled / exposed yet?

![image](https://user-images.githubusercontent.com/59932779/228766489-0572a0a8-39b4-4de7-bc1a-9ed3d99635ab.png)

This is what the users see:

![image](https://user-images.githubusercontent.com/59932779/228766730-db9373df-8e81-4fda-a5aa-7147fd004e79.png)

**Comment by yaustar** [comment]
Do we want to expose it? We can do that quite easily if it's done and we want users to use it

**Comment by willeastcott** [comment]
Duplicate of #191. Closing.
