### ISSUE TITLE
New Project Editor View doesn't support importing projects direct to ORG accounts

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#1011]
On https://playcanvas.com/editor, the importing doesn't support going to ORG accounts. 

![image](https://user-images.githubusercontent.com/16639049/229804625-26e35af0-b5fb-4ed3-a874-3e72a7384527.png)

(The cloud icon)

There's a list of ORGs on the left, perhaps we can use the currently selected user/ORG as the target for the import?

**Comment by yak32** [comment]
the issues is fixed and deployed to PROD
