### ISSUE TITLE
Expose debug rendering functionality

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#1016]
expose functionality from this engine PR
https://github.com/playcanvas/engine/pull/5261

![image](https://user-images.githubusercontent.com/59932779/233980019-cfc6b58b-8f30-4af3-89f7-d21e0c9c2f34.png)

@jiajasper for UX design.

**Comment by kpal81xd** [comment]
So i was initially thinking of something like this where you would add a property to the camera component as an alternative for adding a new menu in the launcher or viewport since that requires an additional select menu to manage each cameras shader pass 

![image](https://github.com/playcanvas/editor/assets/48248865/dfb6571c-1696-4eb9-aead-87e3935a054b)

**Comment by mvaligursky** [comment]
I think we care about rendering inside the Editor's viewport only, using Editor's camera. We do not need to handle camera's in the launcher / game, as those are owned by the user, and they can implement debug rendering themselves if they need to.

And so I think maybe we need a drop down on top of the 3d view in the Editor, perhaps directly left of the `Perspective` dropdown?
<img width="1152" alt="Screenshot 2023-12-20 at 13 57 00" src="https://github.com/playcanvas/editor/assets/59932779/734cbbfc-180f-42a9-8a25-542e8604d295">

**Comment by Maksims** [comment]
> I think we care about rendering inside the Editor's viewport only, using Editor's camera. We do not need to handle camera's in the launcher / game, as those are owned by the user, and they can implement debug rendering themselves if they need to.
> 
> And so I think maybe we need a drop down on top of the 3d view in the Editor, perhaps directly left of the `Perspective` dropdown? <img alt="Screenshot 2023-12-20 at 13 57 00" width="1152" src="https://private-user-images.githubusercontent.com/59932779/291913180-734cbbfc-180f-42a9-8a25-542e8604d295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODI2OTYsIm5iZiI6MTcwMzA4MjM5NiwicGF0aCI6Ii81OTkzMjc3OS8yOTE5MTMxODAtNzM0Y2JiZmMtMTgwZi00MmE5LThhMjUtNTQyZTg2MDRkMjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE0MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODRlMjc4YjUyOGU2OGRkYThiYzlhMjZmYWRhZjI3MmZmN2FiZTcwNmZmYWRkZmZhMTE5MDQzNTY5Y2EwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lI5CXVhQUAwVx8-PE1jatLPOwdrkffHhpQ7zzH0EnA">

It can be as an icon with a drop-down just like perspective drop down would be amazing!

**Comment by willeastcott** [comment]
The question is....what icon would it be? 🤔

**Comment by mvaligursky** [comment]
I just realised. If we have the Editor camera selected, this will be only visible in the Editor. But if in the Editor you select a game camera to be active, this will be reflected in the launcher as well! That'd be so awesome.
