### ISSUE TITLE
Curve attribute arrays bug out when array length change

### ISSUE THREAD

**Issue by Astra307** [playcanvas/editor#1019]
Curve attribute arrays stop working if the length of the array change. This also happens if the curve attribute is part of a json attribute array which changes length.

To fix a bugged curve the interpolation mode needs to be changed back and forth between a different setting (does not matter which).

The bug is reproduced in [this example project](https://playcanvas.com/editor/scene/1729146).
_(Both boxes are supposed to move similarly. To bug the moving box simply change the curve attribute length in the editor. To un-stuck the static box simply change the interpolation mode of curve 0 to another and back in the editor.)_

**Comment by Astra307** [comment]
Hey, any progress on this?
It might sound weird, but in our company we have to deal with this bug almost every day due to some of our central script using this feature. Which is pretty annoying.. so yeah.. would be rly great to have it fixed :)

**Comment by slimbuck** [comment]
Really sorry it's taken so long. I will try to investigate soooon!

**Comment by Astra307** [comment]
Wow, that WAS soon X)
looking forward to seeing it in production!

**Comment by slimbuck** [comment]
Sorry we've had to spend extra time testing the latest editor release (with new engine especially). Hopefully we'll have this out within a week.

**Comment by slimbuck** [comment]
This should now be fixed!
