### ISSUE TITLE
504 server error when importing models

### ISSUE THREAD

**Issue by maciej-lepb** [playcanvas/editor#1021]
### Description

Since a few hours we are unable to import any mesh into assets due to a 504 server error.

This has been observed on multiple devices, browsers, user accounts, platform, etc. I.e. seems to be a global server issue.

### Steps to Reproduce

1. Open any project into editor
2. Pick any .fbx from your hard drive. 
3. Open your browser's developer tools
4. Drag and drop it onto the assets panel
5. Observe the asset never finishes processing
6. Observe a POST https://playcanvas.com/api/assets/xxxxxxxxxx/reimport?branchId=xxxxxxx 504
7. When you inspect this error in the network panel, you'll see the attached:

This is a blocking issue preventing all development on our side at the moment.
<img width="993" alt="Screenshot 2023-04-28 at 16 12 52" src="https://user-images.githubusercontent.com/67952729/235171389-01e0c255-b0a3-464a-937a-b8ec6fc07154.png">

**Comment by yaustar** [comment]
We've seen an increased load on our GLB import server and have been investigating. We will get back to you as soon as possible

**Comment by yaustar** [comment]
We have flushed the queue for model uploads and new uploads seem to be working

We are still monitoring the situation while looking at how we can prevent this in the future
