### ISSUE TITLE
Incorrect camera attribute descriptions

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1022]
This is a follow up on https://github.com/playcanvas/editor/issues/997

The attribute descriptions were applied to incorrect attributes:

![image](https://user-images.githubusercontent.com/5677782/235733371-27d9e870-35f5-451a-836e-91787a11924f.png)

**Comment by yaustar** [comment]
Fixed in https://github.com/playcanvas/editor-ui/pull/95

**Comment by willeastcott** [comment]
Now deployed...
