### ISSUE TITLE
Profiler ignores the draw calls limit

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#103]
![image](https://user-images.githubusercontent.com/5677782/87433422-f7003e80-c5f1-11ea-9578-c5d7574a2562.png)

Seems the camera draw calls limit setting has stopped working. The option is ignored currently.

**Comment by willeastcott** [comment]
When the engine was [ported to ES6 modules](https://github.com/playcanvas/engine/pull/2166), some properties that were in the `pc` namespace were removed. These included some properties used by the Profiler to limit draw call rendering. I've moved them to be static properties on the `ForwardRenderer` class [here](https://github.com/playcanvas/engine/pull/3122).

In addition, the launch page will require a follow up PR to use the moved properties. But I've verified it works again with these changes.

**Comment by willeastcott** [comment]
Fixed! 😄
