### ISSUE TITLE
Editor feature: search by asset tag.

### ISSUE THREAD

**Issue by franciscochong** [playcanvas/editor#1031]
![image](https://github.com/playcanvas/editor/assets/94553544/b80f6a3b-72ab-4e69-b6df-db8d0192f68f)
I think it would be very useful to be able to search by a specific asset tag in your asset explorer.

**Comment by Maksims** [comment]
You can. Type a tag in square brackets, like so: `[monster]`

**Comment by franciscochong** [comment]
Thanks so much! :D

**Comment by Maksims** [comment]
Check User Manual, there is more: https://developer.playcanvas.com/en/user-manual/designer/assets/#searching
