### ISSUE TITLE
Prefer WebGL 1.0 on launch seems broken

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/editor#1032]
We are attempting to run tests on a WebGL 1.0 context but it seems the editor launch flag/param isn't respected anymore.

Steps to reproduce:
1. Toggle Prefet WebGL 1.0 to true
2. Launch
3. Go to console and check the context running, it's still WebGL 2.0:
```
// returns true
pc.app.graphicsDevice.webgl2
```
This is quite important given the only other way to test is to either disable WebGL 2.0 on the device or export a .zip build and manually set the context.

Setting Prefer WebGL 2.0 to false in the Rendering settings also doesn't seem to work.

**Comment by slimbuck** [comment]
Can confirm, fix in the works.
