### ISSUE TITLE
FBX Model Import Error with Animation

### ISSUE THREAD

**Issue by Casval111** [playcanvas/editor#1038]
1. test project: https://playcanvas.com/project/1079024/overview/model-viewer
2. test fbx file: [BOX.zip](https://github.com/playcanvas/editor/files/11846827/BOX.zip)

**Comment by slimbuck** [comment]
Hi @Casval111 , thanks for reporting this. Looks like we pushed a bad update. We'll get a fix to PROD asap.

**Comment by slimbuck** [comment]
Fix has been pushed out, please try again!

**Comment by Casval111** [comment]
OK. It seems to be fixed.
