### ISSUE TITLE
Template instantiation issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1042]
We have some templates having troubles to instantiate correctly in Launcher, when the template is dragged into scene in the Editor. It doesn't happen when the app is launched.

Here is the error:
![image](https://github.com/playcanvas/editor/assets/5677782/4e2edac4-8d65-40f7-9898-dcc92f095a00)

Editor vs Launcher:
![image](https://github.com/playcanvas/editor/assets/5677782/a3c25769-0a58-4587-aa6f-9f8212232766)

Its an authored asset, so can't make it public. Please, give a username I could add to a repro project (if needed):

https://playcanvas.com/project/1098513/overview/template-issue

Steps to repro:
1. Open launcher.
2. Drag and drop a template to the scene in Editor.

**Comment by slimbuck** [comment]
The function is actually `findByGuid`. Fix is in the works.

As always - thanks for reporting!
