### ISSUE TITLE
missing child entity breaks entity delete function

### ISSUE THREAD

**Issue by Casval111** [playcanvas/editor#1048]
1.  "Cannot find child entity 4fd082e9-500a-48a7-a9a1-73bd3ad488a9 of parent "Root" (684df6b4-c6d6-11e6-89b2-22000ac481df)" error occurred
2. all entities in this scene, cannot be deleted.
3.
![image](https://github.com/playcanvas/editor/assets/59910939/0ae20d2c-32f8-428d-963c-286522194e69)

**Comment by yaustar** [comment]
Please see this thread on a fix: https://forum.playcanvas.com/t/cannot-find-child-entity-of-parent-root-editor-error-cant-delete-entities/23048

If this is a newish project, it would be great if you have an reproducible steps to share that can be done on a new project for the team to look at

**Comment by Casval111** [comment]
That works.
