### ISSUE TITLE
Remove Google+ share button from published apps

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#105]
![image](https://user-images.githubusercontent.com/697563/87818174-12718080-c862-11ea-8601-85f58e7c536c.png)

If you click it, you get this:

![image](https://user-images.githubusercontent.com/697563/87818232-24ebba00-c862-11ea-9234-6d09f42fcab2.png)

**Comment by vkalpias** [comment]
Fixed (will be deployed in the next few days)
