### ISSUE TITLE
Losing controls on viewport resize

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1051]
On viewport resize the controls are getting lost:

https://github.com/playcanvas/editor/assets/5677782/e592019a-3e47-48af-a425-2a5957974a6f

**Comment by willeastcott** [comment]
Can you reproduce this every time you try it? It doesn't happen on my Win10 laptop in Chrome.

**Comment by LeXXik** [comment]
Yes, always repro. Using Win 11 desktop. Tried both Chrome stable and canary. Also Edge.

**Comment by willeastcott** [comment]
@LeXXik The attempted fix for this is now live. Can you confirm it no longer happens?

**Comment by LeXXik** [comment]
@willeastcott yes, I confirm. Thank you!
