### ISSUE TITLE
Lower the priority of unfavoriting a branch

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1052]
At the moment the "Unfavorite this branch" is offered as a top selection, which is higher than switching to a branch. This is a feature request to move the option lower in the selection list. Switching a branch should probably be a top offered selection, regardless of whether the branch is favorite or not.

![image](https://github.com/playcanvas/editor/assets/5677782/141c0ca0-c90c-4794-a08f-b8b2473fbfed)

**Comment by slimbuck** [comment]
Agree!
