### ISSUE TITLE
Allow imported scripts to load as modules

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1054]
This is a feature request to allow third party scripts to be loaded as module.
![image](https://github.com/playcanvas/editor/assets/5677782/dbd77561-3a81-4d56-a2e0-9f25e44cd071)

```js
<script>...</script>
```
would become
```js
<script type="module">...</script>
```

**Comment by Maksims** [comment]
This will definitely break if enabled by default for all scripts. So this should be an option for individual scripts.

**Comment by marklundin** [comment]
Adding `type='module'` on these will cause these scripts to be async which may be problematic as there's no guarantee no of execution order between these and classic scripts.

We are gradually moving toward [first class support for ES modules](https://github.com/playcanvas/engine/pull/5963) in the engine and editor, so the above use case can be solved like this;

```javascript
// printer.js
export function print(name) {
    console.log(name);
}
```

```javascript
import { print } from './printer.js';
// pc.ScriptType
var Script = pc.createScript('script');
Script.prototype.initialize = function() {
    print('example');
};
```

Closing for now as unplanned
