### ISSUE TITLE
GLB import no longer works

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1055]
The GLB import feature seems to no longer work. To repro, simply import any Scetchfab model. For example:

![image](https://github.com/playcanvas/editor/assets/5677782/7d3efb2f-e74d-459f-a278-841c340161b5)

Result:

![image](https://github.com/playcanvas/editor/assets/5677782/031e1905-c172-4008-bcd9-fbcb20c95d0c)

**Comment by coldfireagc** [comment]
Ditto for FBX format

**Comment by slimbuck** [comment]
The servers experienced a huge spike in activity earlier.

We're busy investigating, but ultimately yours jobs may take a while to complete.

**Comment by slimbuck** [comment]
We've cleared the backlog now. Sorry about that, please try again!
