### ISSUE TITLE
Deprecated value in hint

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1058]
Standard material Vertex Color hint is using a deprecated name:

Using: `diffuseMapVertexColor`
Expected: `diffuseVertexColor`

Same thing for others, like specular, emissive, etc.

![image](https://github.com/playcanvas/editor/assets/5677782/088e574d-52c8-4e3c-a28a-b9f55327bc0e)

**Comment by willeastcott** [comment]
Ooo, well spotted. I've submitted a fix for this!
