### ISSUE TITLE
Template not recognizing an attribute change

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1061]
Use case: a template in the scene has a script with an attribute of type `entity`.

- The template change is detected only if one of the template children are selected. Or the first selection outside of template:

Repro: https://playcanvas.com/project/1145186/overview/template-issue

https://github.com/playcanvas/editor/assets/5677782/67e14d25-37a7-4233-ae6a-ad212ab266e3

**Comment by yaustar** [comment]
As designed since templates can only store references to entities within template itself 

It can't store references to entities outside the template as that reference may not exist when the template is instantiated elsewhere or at runtime

**Comment by LeXXik** [comment]
Closing as per design.
