### ISSUE TITLE
Editor warnings

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1062]
Create new blank project, open it in Editor, observe console. Console will have a number of warnings:

![image](https://github.com/playcanvas/editor/assets/5677782/91fba372-a5ef-41f5-b621-6bccafca9780)

**Comment by Maksims** [comment]
That is a good warning, it reminds devs to add docs to reference popups.

**Comment by willeastcott** [comment]
I've just fixed the only warning of this type that is currently being output to the console. So I'm closing this issue.
