### ISSUE TITLE
Code Editor File Dropdown Bug

### ISSUE THREAD

**Issue by kpal81xd** [playcanvas/editor#1065]
### Description

Graphical bug when hovering over the `File` dropdown in the Code Editor. The red highlighted box below indicates the area for which the dropdown is unresponsive.

![image](https://cdn.discordapp.com/attachments/408617316415307778/1166464787719409717/image.png?ex=654a95fd&is=653820fd&hm=e234bd3925136fa6ae23f9bfabc2b2f4dddb36b9278829b5ecc4d2dee7844328&)

* Browser/Platforms - Chrome, Firefox (Windows 11)

### Steps to Reproduce

1. Visit any valid Code Editor [https://playcanvas.com/editor/code/{any_id}](https://playcanvas.com/editor/code/{any_valid_id})
2. Hover over the `File` dropdown option
3. The button is only clickable and the hover effect only shows in the lower and right portion of the option

**Comment by willeastcott** [comment]
Looks like it's the drag handle for the tree view:

![image](https://github.com/playcanvas/editor/assets/697563/28164fbb-1f38-418d-9d62-d267e8eb1ccf)

**Comment by willeastcott** [comment]
If you try to drag a tree view item, the 'invisible' drag handle disappears from the top left corner.

**Comment by willeastcott** [comment]
I'm wondering if this should be created hidden: https://github.com/playcanvas/pcui/blob/main/src/components/TreeView/index.ts#L196

**Comment by kpal81xd** [comment]
Yes since the drag handle item will be hidden once the drag action has been completed already restoring the File dropdown to perform as intended.

**Comment by willeastcott** [comment]
This was fixed here: https://github.com/playcanvas/pcui/pull/364

Should be fixed once we've bumped the Editor to the latest version of PCUI.
