### ISSUE TITLE
Errors, when enabling SharedArrayBuffer setting

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1073]
Getting console errors in Launcher:

![image](https://github.com/playcanvas/editor/assets/5677782/f8b66185-c9d0-42f8-963e-eb1c1071f684)

Seems like they appear when the launcher is idle for a bit.

**Comment by isumygin-sc** [comment]
hm, I can't reproduce the issue.

**Comment by LeXXik** [comment]
Can no longer reproduce. Not sure what it was. Closing.
