### ISSUE TITLE
Tween in store (scripts) is not valid

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1074]
It uses `TWEEN` variable, which is not valid for Editor. Probably copy-pasta issue.

https://github.com/playcanvas/engine/blob/a72b99e0af4b727ca9e6837b13694bd0a2d7c102/scripts/animation/tween.js#L316

**Comment by marklundin** [comment]
Just to clarify, is this a regression @yaustar?

**Comment by mvaligursky** [comment]
I uploaded the library version (https://github.com/playcanvas/playcanvas-tween/blob/main/tween.js) to the store now.

**Comment by yaustar** [comment]
> Just to clarify, is this a regression @yaustar?

The original version was from the `playcanvas-tween` library which is 'correct' in the sense it's what the tutorials, docs and forums reference: https://developer.playcanvas.com/en/tutorials/tweening/

It was incorrectly updated to the engine helper script that uses https://github.com/tweenjs/tween.js

In that sense it's a 'regression'. There is a bigger issue about the scripts available in the engine repo being different to what is on the editor site. eg Orbit Camera, first person controller, etc and how to sync them or whether they should be sync'ed

**Comment by yaustar** [comment]
@mvaligursky Minor and doesn't affect behaviour. When the tween library is imported, it doesn't have `.js` at the end of the asset name

<img width="517" alt="image" src="https://github.com/playcanvas/editor/assets/16639049/11635816-f21a-4eab-9eca-165e182d4a1b">

With the other scripts:

<img width="686" alt="image" src="https://github.com/playcanvas/editor/assets/16639049/c6c560f7-3fd4-458d-9174-1ca95f3a1c1b">

**Comment by mvaligursky** [comment]
@isumygin-sc - any idea why the file files not have the extension?

**Comment by isumygin-sc** [comment]
it's fixed and I will also update upload process for store item to make script preload by default ...
