### ISSUE TITLE
Disable Create Preload Bundles by default

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1083]
Forum: https://forum.playcanvas.com/t/preload-zip-files/34344

Consider unchecking `Create Preload Bundles` by default, when downloading a build:

![image](https://github.com/playcanvas/editor/assets/5677782/a5a57c6b-968e-4a3f-8bac-8ccb914579e0)

**Comment by willeastcott** [comment]
Yeah, we should remove this from the UI and ensure it defaults to false. TBH, I'd be happy for the whole feature to be removed from the codebase - but probably easier to just disable in the UI for now.
