### ISSUE TITLE
Ability to reorder layers in an animation state graph in the editor.

### ISSUE THREAD

**Issue by GWattsJP** [playcanvas/editor#1084]
The ordering of layers in an Animation State Graph affects the way in which they blend together. Sometimes you will realise that you need to re-order the layers in order to make something higher / lower priority in the overall blend than it is.

At the moment the editor provides no way to reorder the layers, so you have to manually swap the nodes in the two layers by hand.

Being able to drag them in the left hand panel to change the order, in the same way you can script components on an entity, would save a lot of time.

For example, if I decide that I need to switch the order of where `dead` is in this tree, I have to essentially delete every layer below where I need it to be and recreate them all.

<img width="442" alt="Screenshot 2024-01-10 at 10 14 04" src="https://github.com/playcanvas/editor/assets/16132759/15e93cbc-0f63-42a2-9a69-15e6e48d2e35">

**Comment by willeastcott** [comment]
The PR to address this has now been merged, @GWattsJP. We'll get it deployed and let you know when it's there so you can verify you're happy with the solution. Stay tuned!

**Comment by kpal81xd** [comment]
@GWattsJP the PR has now been merged! Feel free to try it out and let me know if you have any issues 👌
