### ISSUE TITLE
Editor crash on copy/paste

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1087]
If you copy an entity that has a legacy Animation component with a missing animation and try to paste into a new project, the Editor will crash.

![image](https://github.com/playcanvas/editor/assets/5677782/046c777d-225a-4249-bf93-8c8c676d2ab1)

![image](https://github.com/playcanvas/editor/assets/5677782/4497e7f0-34ef-41d8-bbf2-f7587407c26d)

![image](https://github.com/playcanvas/editor/assets/5677782/46fa7e8e-03fd-47a6-a2ca-13c67b2e31a0)

**Comment by kpal81xd** [comment]
This is fixed and will be in included in the next editor release 👍
