### ISSUE TITLE
Render options in Viewport (wireframe, physics shapes)

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#1088]
With latest update we've received Wireframe rendering - awesome!
For the better UX and consistency across UI, it should be a checkbox instead of a switch.
Also, as there is a new options panel called "Render", we could move "Physics Edit Mode" into that panel. And call it "Physics Shapes".

**Comment by mvaligursky** [comment]
This is also coming to that menu soon.
https://github.com/playcanvas/editor/issues/1016

**Comment by LeXXik** [comment]
I thought that "Render" title came from the fact that it renders Render Components. Legacy model components are not affected by this setting.

**Comment by mvaligursky** [comment]
That's a good bug report @LeXXik . Model components should be handled as well @kpal81xd

**Comment by LeXXik** [comment]
Added a separate issue: https://github.com/playcanvas/editor/issues/1089
