### ISSUE TITLE
[Script Editor] Renaming file does not save changes

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#109]
### Description

If you make a change to a file, then rename the file, after you press <kbd>ENTER</kbd> the file will act like it's been saved when it actually doesn't save. The orange highlight saying the file isn't saved won't show and attempting to save with <kbd>CTRL</kbd>+<kbd>S</kbd> won't save the file. Using the file in the project will result in a file that doesn't have the latest changes. You can tell it isn't saved by refreshing the script editor, once refreshed the orange highlight on the file will be back and when you use <kbd>CTRL</kbd>+<kbd>S</kbd> this time around, the file will actually save.

#### With a new file (common use-case)

1. Open the script editor.
2. Right-click anywhere in the left-side file tree to create a new file using the right-click context menu. Any file type will do.
3. Once the file is created, paste any text into the file. (but don't hit save)
4. Right-click on the newly-created file, click on "Rename".
5. Type in a new filename, then hit <kbd>ENTER</kbd> to have the file renamed.
6. Notice that the filename is no longer orange, indicating that file has been "saved". However, the file has not been saved and pressing <kbd>CTRL</kbd>+<kbd>S</kbd> won't save the file.
7. Refresh the page.
8. The file that was just created will now have an orange filename showing that the file was never saved.

#### Pre-existing file

1. Open the script editor.
2. Edit a file.
3. Rename the file.
4. Notice that the filename is no longer orange, indicating that file has been "saved". However, the file has not been saved and pressing <kbd>CTRL</kbd>+<kbd>S</kbd> won't save the file.
5. Refresh the page.
6. The file that was just created will now have an orange filename showing that the file was never saved.

### Screenshots of Process

Create new asset.
![image](https://user-images.githubusercontent.com/6013871/88489977-1f7b2780-cf66-11ea-8672-438798154401.png)

Add some text to the file.
![image](https://user-images.githubusercontent.com/6013871/88489986-2f930700-cf66-11ea-8f98-dd5ddecad7d4.png)

Rename the file.
![image](https://user-images.githubusercontent.com/6013871/88489991-3883d880-cf66-11ea-9744-c6c266fd64e2.png)

After pressing <kbd>ENTER</kbd>, the file will look like it was saved.
![image](https://user-images.githubusercontent.com/6013871/88490001-46d1f480-cf66-11ea-832a-e5a8cbaf3658.png)

After refreshing the page the filename is orange again, indicating that the file was never saved.
![image](https://user-images.githubusercontent.com/6013871/88490014-610bd280-cf66-11ea-89ba-74bf1da0255a.png)

**Comment by vkalpias** [comment]
Fixed.
