### ISSUE TITLE
Open files in CodeEditor are not restored after browser tab reload or reopening

### ISSUE THREAD

**Issue by s-stafeev** [playcanvas/editor#1094]
It feels like the list of open files is remembered randomly rather than the last opened ones.
You can add a menu item for forced remembering:
_Tools
|-- Remember Opened Files_
![image](https://github.com/playcanvas/editor/assets/47380574/94210d56-e080-4e11-8581-07cdd6266c9e)

**Comment by yaustar** [comment]
The files that are opened are based on the URL param `tab` followed by a comma separated list of asset ids

```
https://playcanvas.com/editor/code/1188338?tabs=166406759
```

The Editor doesn't remember what files were opened between sessions.
