### ISSUE TITLE
Draw status bar on top

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1099]
The left menu is placed on top of the bottom status bar, if the window is narrow enough. It should be drawn under it, instead, so messages are no clipped:

![image](https://github.com/playcanvas/editor/assets/5677782/a64dc6e5-e117-427b-8a64-7da905e40665)

**Comment by willeastcott** [comment]
I have submitted a fix for this. We should be able to deploy it in the coming days. Thanks for logging this issue! 🙏
