### ISSUE TITLE
Material anisotropy typo

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#110]
### Description

"Anisotropy" is spelled like "Anistropy" in the editor.

![image](https://user-images.githubusercontent.com/6013871/88505380-49a00a00-cfa5-11ea-8501-7b3700787d18.png)

I was learning about anisotropy and had trouble finding information about the difference between that and anistropy. 😂

**Comment by willeastcott** [comment]
Fixed. This will be deployed shortly.
