### ISSUE TITLE
Show selection count

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1100]
This is a feature request to show the count of selected objects (entities/assets) in the status bar.

![image](https://github.com/playcanvas/editor/assets/5677782/21f14ebd-b6c8-4070-8b74-7b2efbc45393)

**Comment by Maksims** [comment]
There is already a count at the top of the inspector:

![image](https://github.com/playcanvas/editor/assets/636263/ce839e5c-e1da-40ef-9717-3d174de8521c)

**Comment by LeXXik** [comment]
Ah, never noticed it, thanks! Probably my Excel habits, expecting to see it in status bar.

**Comment by willeastcott** [comment]
LOL. Soooo, should we close this?

**Comment by LeXXik** [comment]
Yep.
