### ISSUE TITLE
[RFC] ESM bundling

### ISSUE THREAD

**Issue by marklundin** [playcanvas/editor#1109]
## Support for ESM bundling

> [!NOTE]
> ESM bundling does not attempt to fundamentally rewrite the playcanvas export format. Only what is necessary to have bundled scripts

This is a WIP progress ticket to track and discuss bundling for ESM based projects

As the engine and editor will soon support ES Modules https://github.com/playcanvas/engine/issues/4767, users should be able to export bundled versions of projects with ESM Scripts. This can improve network load by providing optimised builds that end users have control over.

## Requirements

- Bundling ESM projects for both download and published apps.
- Backwardly compatible with existing projects. (Does not change the export pipeline for current projects) 
- Alllows gradual migration. Compatible with projects containing boths classic and esm scripts together.
- Bundles bootstrap, engine and user code together into a single build.
- Supports code splittings (split by preload/split by scene) for optimising load/cache
- Supports modern bundling features (tree shaking/symbol replacement/transforms)
- Obeys minify and concatenation editor options (concatenate false: creates separate files, but still tree-shaken etc)

## Remaining Tasks

- [x] Bundle published apps
- [x] Bundle downloaded apps
- [x] Bundle loading screen
- [x] Verify code splitting strategies
- [x] Concatenations / minification
- [x] Export source maps
- [x] Surface build errors to editor
- [x] Support custom loading screen work

### User configuration

Update: We've opted for user build configuration to be presented in the export UI dialog as opposed to a separate congfig. This is mainly for UX consistency with how export options are currently presented. 

~~This can be specified using a simple `build.json`  in the root of the project, if none are found we use a  pre-defined set of options.~~

~~Additionally users can define a `debug.build.json` used in the launcher. This will allow user to configure different environments depending on the environment.~~

### Code Transformation/Transpiling
Bundling will support basic code transformations, starting with minimal initial transforms like stripping debugger statements etc. Over time, we may expand this to include other transformations, such as TypeScript. Each addition will be evaluated on a case by case basis.

However, we don’t plan to support broad code lowering (e.g., Babel et al). Supporting every possible browser target and language feature would be unmanageable. Instead, we’ll focus on a common baseline and let users decide the language features to use specific to their needs. We’re also exploring the option for users to download the project’s source with the same ESM bundler, enabling custom transformations like Babel for local use.

### Breaks rest-api-tools
See https://github.com/playcanvas/playcanvas-rest-api-tools/issues/50 for more information

**Comment by Maksims** [comment]
> This can be specified using a simple `build.json` in the root of the project, if none are found we use a pre-defined set of options.

Can you please clarify this?
Does it require creating a JSON asset by the user?

**Comment by marklundin** [comment]
Yep to override build options etc, otherwise it will just default to some predefined ones.

**Comment by marklundin** [comment]
Just outlining some further details for visibility.

### ESM Script Resolution

When you export a project, a number of js files are shipped, but the main entry point is `__start__.js`. This instantiates the application, makes requests to load scene data, which it uses to pre-load ESM Scripts.

The important thing here is that the application requires scene/asset json data to import ESM Scripts. Therefore a bundler can't statically analyze the code and resolve these dependenciesa. Therefore we need some way to dynamically add these to the bundle process.

### Code splitting

ESM Scripts should be in a separate bundle to the main entry point. This allows for lazy-loading. In addition, sub dependencies within Scripts should support [standard](https://rollupjs.org/tutorial/#code-splitting) [code-splitting](https://github.com/evanw/esbuild/blob/main/docs/architecture.md#code-splitting) which will allow better loading

### Further improvments
There's additional room to improve the output structure of an exported project which is more in-line with modern web practices (transpilation, obfuscation, etc), however this is an ongoing discussion which can be incrementally improved upon, and is not mandatory for this ticket.

**Comment by marklundin** [comment]
This work has not been completed.
