### ISSUE TITLE
The asset panel tree selection issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1119]
The folder tree in the asset panel doesn't show the folder in the inspector panel on the first click. You have to click it a second time. It works correctly inside the assets list, though:

https://github.com/playcanvas/editor/assets/5677782/c85fa8b2-7143-4277-96f9-d76cab3f98c3

**Comment by Maksims** [comment]
It is intentional, to allow navigating through folders while having an asset selected.

Good example is: select a material, then navigate to folder to find texture you want to use on that material.

If clicking on a folder would select it also, that workflow would prove difficult.

**Comment by LeXXik** [comment]
That seems like trying to guess what a user wants to do, which works only for half use cases. I think if the user wishes to pick a texture or an asset for one of the material slots from another folder, he can do that via "select asset mode" (or whatever that focus mode is called). The normal folder selection should be unassuming.

https://github.com/playcanvas/editor/assets/5677782/e0535162-0fa4-48c0-9b2f-cfaaa1c62875

**Comment by LeXXik** [comment]
I do see myself sometimes having a material selected and browsing folders for textures without focus mode, though. Perhaps, it could be kept as is, if a material/asset is selected, but allow folder selection? I often create new folders, and trying to rename it by selecting from the tree feels like the Editor is trying to get in my way.

**Comment by Maksims** [comment]
> I do see myself sometimes having a material selected and browsing folders for textures without focus mode, though. Perhaps, it could be kept as is, if a material/asset is selected, but allow folder selection otherwise? I often create new folders, and trying to rename them by selecting from the tree feels like the Editor is trying to get in my way.

I'm afraid there is no perfect solution here. Introducing more "magical rules" might make it worse.
The second click - always selects the asset.
Also, this behaviour is only specific to the tree, in the list of assets clicking on the asset will select it regardless of type.

Asset picker navigates automatically to the folder of current assets in that slot or to the material you are picking the texture for if there is nothing selected for the slot. So in the case of picking one asset - that is fine. But when you are required to select multiple assets, it is too much of a hustle to jump between folders on each asset picker interaction. That is why there is a way to select material, then navigate through the tree to the necessary folder/folders and drag'n'drop textures.
