### ISSUE TITLE
Draco throws

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1121]
A follow up to #1103 

Activating Shared Array Buffer and using web worker now works. However, I got this error from Draco once. I can't seem to reproduce it though now, not sure if something changed.

![image](https://github.com/playcanvas/editor/assets/5677782/4a0da4ea-7ae3-488a-897b-1b2c72cec369)

**Comment by marklundin** [comment]
This is in the launch page?

**Comment by LeXXik** [comment]
It was, yes. However, I can no longer reproduce it :/

**Comment by marklundin** [comment]
Can this be closed @LeXXik ?

**Comment by LeXXik** [comment]
Can be closed. Haven't seen the issue in a while.
