### ISSUE TITLE
Cannot open Editor in Firefox

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1126]
Unable to open Editor in Firefox. Showing gray screen.

![image](https://github.com/playcanvas/editor/assets/5677782/9246bb59-236b-4b14-9c69-fd78c8dfa005)

Some notifications in console, but doesn't seem like anything critical:

![image](https://github.com/playcanvas/editor/assets/5677782/7ee183e2-de10-4532-a9bb-4a0bbeed1454)

Firefox v:
121.0 (64-bit)
122.0 (64-bit)
123.0.1 (64-bit)

**Comment by mvaligursky** [comment]
investigating, thanks!

**Comment by mvaligursky** [comment]
The deployment was reverted and all is working again, thanks for the report!
