### ISSUE TITLE
Script attribute of type 'json' not accepted

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#113]
Docs: https://developer.playcanvas.com/en/api/pc.ScriptAttributes.html

According to docs, script attribute of type `json` is a valid option. However the following script will fail parsing in Editor, complaining that `json` is not a valid type:
```
Script.attributes.add('myJSON', { type: 'json' });
```
![image](https://user-images.githubusercontent.com/5677782/89025007-c7aa3b00-d32e-11ea-8309-2070479c5c7f.png)

**Comment by LeXXik** [comment]
Depends on https://github.com/playcanvas/engine/pull/2234
Can be closed.

**Comment by Maksims** [comment]
It could be that `json` type is supported by Engine, but not yet added to the Editor (functionality to create UI based on json schema, can be a bit complex).

**Comment by yaustar** [comment]
If you are looking to load a JSON file from the assets, this is what you need: https://developer.playcanvas.com/en/tutorials/loading-json/

**Comment by LeXXik** [comment]
Yes, @Maksims, I agree, adding support for organizing schema from UI is not trivial.
Thank you for the link, @yaustar! Yes, I am aware of how to load the JSON. 

My original post of the issue was regarding the docs statement:
![image](https://user-images.githubusercontent.com/5677782/90284563-d4747600-de7a-11ea-95a5-ffd42839c64a.png)

If I wouldn't know how to load JSON, this would be the first place I'd look for. And event though it is stated there, that `json` is an accepted string literal, I would face the error message I posted originally.

**Comment by vkalpias** [comment]
Hi @LeXXik we actually have a PR ready for supporting JSON attributes with a custom schema: https://github.com/playcanvas/engine/pull/2234

**Comment by LeXXik** [comment]
Got it. Thanks!
