### ISSUE TITLE
Concatenation issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1133]
Creating worker fails, when Launcher is started with "Concatenate Scripts" option:

![image](https://github.com/playcanvas/editor/assets/5677782/e11bdb94-4f3e-4579-9dcf-4374fc6d0249)

Related forum: https://forum.playcanvas.com/t/new-worker-causing-build-fail/35411
Repro: https://playcanvas.com/project/1204252/overview/concatenation-issue

**Comment by leonidaspir** [comment]
I think that works as expected given all preloaded scripts will be included in the concatenated script file. 

Does setting preload = false to the worker script fix this? That's the proposed way to treat worker script file on production builds too.

**Comment by LeXXik** [comment]
Yes, it works correctly without concatenation. In our builds, we download non-concatenated build and concatenate/minify it ourselves, so we have a control over what is concatenated.

Still could be useful in Launcher, when the project has many scripts, as loading is much faster with concatenated option in that case. Perhaps a boolean property could be added to script asset to be excluded from concatenation.

**Comment by marklundin** [comment]
The `concatenate` flag will inline this, which will always be a problem when creating workers. You can probably get around this using `URL.createObjectURL` with inline workers etc. Closing for now
