### ISSUE TITLE
App failing to start under some condition

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1141]
Originally thought the issue was:
https://github.com/playcanvas/engine/issues/6224

However, it appeared to be unrelated, so had another look at the user project. I've modified the project - everything is disabled in the scene hierarchy and a debug variant of the engine is loaded. The issue only happens in the build, not in launcher, so reporting it to Editor. Somehow the scope gets lost and the app fails to start:

https://playcanv.as/b/d8217e10

**Comment by marklundin** [comment]
Was the lost scope a false report with the source maps issue @LeXXik?

**Comment by marklundin** [comment]
Hmm, so it looks like there are 2 version of the engine in this project. The console is logging out `Powered by PlayCanvas 1.70.0-dev b27ce4537` which is originating from this [debug build](https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/d8217e10/files/assets/173988976/1/playcanvas.dbg.js), however there's also the [playcanvas-stable release 1.69.2](https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/d8217e10/playcanvas-stable.min.js). Can't quite tell, but it feels like this might be causing issues

**Comment by marklundin** [comment]
Ok apparently the 2 engines is unrelated and the error still occurs

**Comment by LeXXik** [comment]
Right. I've added a debug version there for readability and load it after engine. The error is same without it, though, so it is not related.

**Comment by kpal81xd** [comment]
> Right. I've added a debug version there for readability and load it after engine. The error is same without it, though, so it is not related.

Do you know an engine version which works with this project?

**Comment by kpal81xd** [comment]
Okay so we figured out that the `window.app` is being redefined during the preload process.

**Comment by LeXXik** [comment]
Thanks! Yes, I found the script which is a culprit. Removing it, I can confirm the build works fine. That was an obscure one, but closing as a user error.

![image](https://github.com/playcanvas/editor/assets/5677782/602561e2-b06e-44cf-8549-aec45ac6af27)

**Comment by kpal81xd** [comment]
Adding a fix to keep the start app in a separate scope regardless for future 👍
