### ISSUE TITLE
Do not allow creating a script with a reserved name

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1159]
At the moment you can create a script with any name, even with restricted name. Then the Editor will show an error (an obscure one, at the bottom status line) that the script is using a reserved name. This is a feature request to not allow creating a script with a reserved name in the first place.

![image](https://github.com/playcanvas/editor/assets/5677782/af588920-13cf-4750-98ca-fad801a489d1)

**Comment by mvaligursky** [comment]
related / duplicate of https://github.com/playcanvas/editor/issues/927

**Comment by LeXXik** [comment]
Closing in favor #927
