### ISSUE TITLE
Line-break does not stop link parsing in dashboard comments. 

### ISSUE THREAD

**Issue by ChristianTucker** [playcanvas/editor#116]
I was advised to report this bug here, even though it's a dashboard related issue. 

### Description

When posting a comment on a post through the PlayCanvas dashboard, links do not properly take line-breaks (Shift + Enter) into consideration during parsing, causing the first word after the line-break to be included in the link.

![bug](https://user-images.githubusercontent.com/23084841/89275743-88623f80-d5f7-11ea-875e-f2d738f7ecf6.png)

This does not work on the original post. 

### Steps to Reproduce

Comment on any post and type out or paste a link. Then after the link hit (Shift+Enter) to create a line break, and continue typing. The first word in the next line will be appended to the link.

**Comment by willeastcott** [comment]
This no longer seems to happen. Closing.
