### ISSUE TITLE
GLB File Size Increases from 3MB to 26MB After Importing to PlayCanvas 

### ISSUE THREAD

**Issue by ertugrulcetin** [playcanvas/editor#1164]
I recently optimized my GLB file, successfully reducing its size from ~25MB to 3MB. However, when I upload this 3MB GLB file to the PlayCanvas Editor, the file size inflates to 26MB. Previously, I used BabylonJS with the same model, and the network panel showed the desired 3MB size.

Has anyone else experienced this issue? What steps can I take to ensure that the imported file size remains close to 3MB in PlayCanvas?

I've used to reduce the GLB file: https://juunini.github.io/gltf-optimizer 

Here is the GLB: https://drive.google.com/file/d/1FdHYzl9ILR-M7cGXTN7fPXRiK85OnSGe/view

**Comment by mvaligursky** [comment]
Forum post: https://forum.playcanvas.com/t/glb-file-size-increases-from-3mb-to-26mb-after-importing-to-playcanvas/36039

**Comment by slimbuck** [comment]
Hey @ertugrulcetin , have you enabled draco compression in asset import settings?

**Comment by mvaligursky** [comment]
Yep just tried with draco, it this is now down to 2.2MB, please use that.
Closing but reopen if this does not solve it for you.

**Comment by ertugrulcetin** [comment]
Thank you guys, it seems that the problem solved. I did not know that the draco was not on by default.
