### ISSUE TITLE
Unable to scale from camera view

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1166]
When viewport is switched to Camera view, then scale gizmo is not usable:

https://github.com/playcanvas/editor/assets/5677782/4284ef9c-68ef-49a6-8b36-292fd6f0f727

**Comment by kpal81xd** [comment]
I cannot replicate this the scaling works for both perspective and camera views

**Comment by LeXXik** [comment]
I can no longer reproduce as well. Closing.
