### ISSUE TITLE
Custom Engine Specification Not Working Correctly

### ISSUE THREAD

**Issue by sutobu000** [playcanvas/editor#1167]
When using the PlayCanvas custom engine feature, there is an issue where the latest engine is always selected, even when specifying a self-hosted engine or a localhost engine.

https://developer.playcanvas.com/user-manual/editor/launch-page/custom-engine/

Current situation:
- https://code.playcanvas.com/playcanvas-x.x.x.min.js loads correctly.
- When specifying a custom engine URL, the latest engine is used instead of the specified version.

When a custom engine URL is specified, the engine at that URL should be used.

We would greatly appreciate it if you could address this issue. Thank you for your consideration.

<img width="1453" alt="スクリーンショット 2024-06-25 12 24 12" src="https://github.com/playcanvas/engine/assets/17917713/688409a6-ca0c-4467-9a39-f17a483a7784">
<img width="1451" alt="スクリーンショット 2024-06-25 12 25 21" src="https://github.com/playcanvas/engine/assets/17917713/01a9a88f-fe0d-4ad8-9fb2-8cce08ac541a">

**Comment by slimbuck** [comment]
Hi @sutobu000,

I'm not sure if the docs make this clear, but you are only able to use engine served from https://code.playcanvas.com and http(s)://localhost. No other domains will work. This was added as a security measure.

Could this be the problem?

Thanks

**Comment by sutobu000** [comment]
Oh, I see it can be used from https://localhost !
I've been using https://192.168... until now...

It seems this was the cause of the problem. I now understand that for local development environments, I need to use localhost instead of IP addresses like 192.168...

Thank you for the quick response!

**Comment by sutobu000** [comment]
@slimbuck, I had one more question, 

When I want to check the content on a head-mounted display, I don't think I can run it with localhost. Is there any good workaround for this?
I really need to use a slightly modified version of the engine for debugging.

**Comment by slimbuck** [comment]
Is this because you need https? Could you serve from `https://localhost`.

**Comment by sutobu000** [comment]
Yes, HTTPS is necessary. However, that's not the issue here.

I think we need to use an IP address to access the local server on the PC from a smartphone or head-mounted display.
Probably, the way to access localhost from a smartphone or head-mounted display would be to use the 192.168... IP address, so is there any other way to handle this?

**Comment by Maksims** [comment]
For testing on device, upload compiled engine as JS file in assets, and select "load after engine" for it. So Launcher will use that engine, and no query params required.
