### ISSUE TITLE
Override window "apply" "revert" disappears bug

### ISSUE THREAD

**Issue by tdautreme** [playcanvas/editor#1172]
I’m trying PlayCanvas, but I encountered a bug with the override popup. I can’t click “apply” or “revert” because the popup disappears each time I try to put my cursor on it.

https://www.youtube.com/watch?v=uljcSiRfEtk&ab_channel=tdautreme

**Comment by slimbuck** [comment]
Hi @tdautreme , this is a pretty issue thanks for reporting. We're investigating and will fix asap.
