### ISSUE TITLE
Newly created script isn't added to the entity

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/editor#1174]
### Steps to Reproduce

1. Create a new entity
2. Add a script component to that entity
3. Using script component input try to create a new script
4. Script is created
5. Script isn't added to the script component
6. Error appears
![image](https://github.com/user-attachments/assets/ed8f69ae-7e82-4737-bcce-0b9187c2ee22)

**Comment by mvaligursky** [comment]
Thanks for the report @OlegGedzjuns , I can reproduce it as well. We'll fix is shortly.
