### ISSUE TITLE
Imports of non `mjs` files fail in editor

### ISSUE THREAD

**Issue by marklundin** [playcanvas/editor#1178]
Code that fetches non `.mjs` paths do not resolve correctly in the editor.

In this [example](https://playcanvas.com/editor/scene/2040755.)  the `debug.mjs` is the glue script that loads the relative `./debug.wasm` file.  Running this files throws a network error `unable to resolve ./debug.wasm`.

This happens because the service worker that maps asset registry urls (`./path/to/file.mjs`) to the backend urls (`/files/assets/api/file.mjs?id-xyz`) is currently restricted to `.mjs` files only, meaning a `fetch('./debug.wasm')` will 404.

This was done to prevent any issues with fetch/import statements with existing scripts, however it's not intuitive to developers why this doesn't work.

Ideally the editor should allow a wider range or import targets, but maybe restrict the mapping to those that only originate from `.mjs` files

**Comment by marklundin** [comment]
I've made an updated which is more permissive in resolving asset urls. This means you have more ways to resolve file urls from ESM Scripts.

This should allow you to do the following:

```javascript
// ✅ This works
import { x }  from './my/other/module.mjs';
const { x } = import('./my/other/module.mjs');

// ✅ type attributes work
import json from '/path/to/some.json' with { type: 'json' };
import('/path/to/some.json', { with: { type: "json" } });

// ✅ relative fetch also works
fetch('/path/to/some.jpg')
fetch('/path/to/some.wasm')
```

**Comment by LeXXik** [comment]
Mark, would there be a ballpark week, when this fix goes out?

**Comment by marklundin** [comment]
I'm on leave this week, but will take a look when I'm back. There's likely some impact on the project export process too
