### ISSUE TITLE
Launch button not pressable when Inspector panel is minified

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#118]
It is not possible to click on Launch button when Inspector is minified, as "Launch" tooltip pops over the button under the mouse cursor triggering blur on button.
![image](https://user-images.githubusercontent.com/636263/89648192-86ce9b00-d8c7-11ea-8b8c-fa0eabc8837e.png)

### Solution:
When inspector is minified, show "Launch" tooltip to the left of a button. Not bellow as it will obstruct options menu.

**Comment by vkalpias** [comment]
Fixed.
