### ISSUE TITLE
Assign a material to multiple mesh instances at once

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#119]
### Description
My character models consist of many meshes. Most of them need the same material. When I make a change in the model, I have to re-assign the material for all meshes one by one by selecting the material and dragging it to the mesh instance. 

I would like if there was a way to assign a material to multiple mesh instances at once.

### Example
![Meshes](https://user-images.githubusercontent.com/52896137/89901450-62373380-dbe5-11ea-99e7-74e1e04e3c76.png)

**Comment by Maksims** [comment]
When you upload the model, it usually creates material, if it is single material and you need to replace it, you can use context menu on asset > replace, which will replace its use with your selected another material.

**Comment by albertvanveen** [comment]
Ah I see, that saves a lot of work! Thank you @Maksims!

**Comment by willeastcott** [comment]
Closing since @Maksims is correct to suggest using the `Replace` function.
