### ISSUE TITLE
Code Editor: console error when working with mjs scripts

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1190]
Code Editor shows a console error when working with .mjs scripts. The scripts do no have attributes and do not use Script class.

![image](https://github.com/user-attachments/assets/2d90170e-d365-414a-b2e2-c6ae210c5658)

And also possibly related:

![image](https://github.com/user-attachments/assets/e978c786-0369-4a48-8a62-1bdedbf8227f)

**Comment by marklundin** [comment]
Thanks for the report. Is this in a blank project?

**Comment by LeXXik** [comment]
The second screenshot appears in a blank project, which has an .mjs file with simple contents:
```js
// my-class.mjs
class MyClass {}
```
The first one seems to need some other conditions.
