### ISSUE TITLE
GLB: issue when upload glb and covert in json

### ISSUE THREAD

**Issue by LynX39** [playcanvas/editor#1191]
### Description

Provide as much information as possible. Include (where applicable):

There is an issue when uploading GLB files within the editor, resulting in only the structural JSON file being created instead of all associated files. Screenshots and the imported test file will be provided below.

File: [test.glb.zip](https://github.com/user-attachments/files/16799336/test.glb.zip)

![Screenshot_3](https://github.com/user-attachments/assets/91dbb5c2-18b4-46c3-a890-fd8ec53ab8ef)
![Screenshot_4](https://github.com/user-attachments/assets/b052921e-60ff-440f-b57f-50e9aecd6b33)

### Steps to Reproduce

1.  Upload a glb

**Comment by mvaligursky** [comment]
@kpal81xd - this can be probably closed?

**Comment by marklundin** [comment]
I have checked this with a new and existing project, and this seems to be fixed. Please re-open if you're still having this issue @LynX39
