### ISSUE TITLE
3D Gaussian Splat Statues no longer works!

### ISSUE THREAD

**Issue by equilento** [playcanvas/editor#1202]
Here's the error:

Failed to compile vertex shader:

ERROR: 0:185: '=' : cannot convert from 'highp 4-component vector of uint' to 'highp 4-component vector of float'
ERROR: 0:187: 'transformC' : undeclared identifier
ERROR: 0:187: 'texelFetch' : no matching overloaded function found
ERROR: 0:187: '=' : dimension mismatch
ERROR: 0:187: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'
ERROR: 0:197: 'center' : undeclared identifier
ERROR: 0:197: 'assign' : l-value required (can't modify a const)
ERROR: 0:197: '=' : dimension mismatch
ERROR: 0:197: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:204: 'covA' : undeclared identifier
ERROR: 0:204: 'assign' : l-value required (can't modify a const)
ERROR: 0:204: '=' : dimension mismatch
ERROR: 0:204: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:205: 'covB' : undeclared identifier
ERROR: 0:205: 'assign' : l-value required (can't modify a const)
ERROR: 0:205: '=' : dimension mismatch
ERROR: 0:205: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:218: 'center' : undeclared identifier
ERROR: 0:218: 'assign' : l-value required (can't modify a const)
ERROR: 0:218: '=' : dimension mismatch
ERROR: 0:218: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:219: 'covA' : undeclared identifier
ERROR: 0:219: 'assign' : l-value required (can't modify a const)
ERROR: 0:219: '=' : dimension mismatch
ERROR: 0:219: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:220: 'covB' : undeclared identifier
ERROR: 0:220: 'assign' : l-value required (can't modify a const)
ERROR: 0:220: '=' : dimension mismatch
ERROR: 0:220: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
ERROR: 0:242: 'evalSplat' : no matching overloaded function found
ERROR: 0:242: '!' : wrong operand type - no operation '!' exists that takes an operand of type const mediump float (or there is no acceptable conversion)
ERROR: 0:242: '' : boolean expression expected
ERROR: 0:249: 'texCoord' : undeclared identifier
ERROR: 0:249: 'assign' : l-value required (can't modify a const)
ERROR: 0:249: '=' : dimension mismatch
ERROR: 0:249: 'assign' : cannot convert from 'highp 2-component vector of float' to 'const highp float'
ERROR: 0:250: 'color' : undeclared identifier
ERROR: 0:250: 'getColor' : no matching overloaded function found
ERROR: 0:250: 'assign' : l-value required (can't modify a const)

180: varying vec4 clip;
181:
182: float PI = 3.14159;
183:
184: void readDataCustom() {
185: vec4 tA = texelFetch(transformA, splatUV, 0);
186: vec4 tB = texelFetch(transformB, splatUV, 0);
187: vec4 tC = texelFetch(transformC, splatUV, 0);
188:
189: if (mode == 0.0) {
190:
while rendering Pass:RenderPassForward | Camera: Camera, Layer: World(TRANSP) | Node: Narcissus, Material: splatMaterial

[object Object]

**Comment by slimbuck** [comment]
Hi @equilento , sorry about this. Please can you give us more info (this seems to be working for me).

Which platform is this (machine & browser)?
Can you share the project or a cut-down repro?

Thanks

**Comment by slimbuck** [comment]
Oh sorry I hasn't seen your update. I will investigate tomorrow.

We updated gsplat shaders recently so the project probably just needs a small tweak.

**Comment by slimbuck** [comment]
I've updated the project for the latest GS shader structure.

**Comment by slimbuck** [comment]
Hi @equilento ,

The shader in engine v1 doesn't work with WebGPU due to a transpiler complication. This was fixed in engine v2. 

Do require WebGPU GS in engine v1? We could probably patch engine v1 if you do.

Thanks!

**Comment by slimbuck** [comment]
It can work in engine v2, but the shader chunks have changed so we'll have to update those first.

We plan on starting testing on editor v2 (with engine v2 support) next week, so perhaps that'll be a good time to convert this demo over.

**Comment by slimbuck** [comment]
Hi @equilento , no I haven't yet. We were a bit delayed releasing editor v2 due to the inevitable holiday season complications. Soon though, I'm keen to have this working.
