### ISSUE TITLE
Auto POT is doubling the size of pre-optimized images when images are already POT

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#122]
### Description

Hello, I have a normal 2048x2048 PNG image that I pre-optimized with pngquant. That brought its size down from 1.44 MB to 606 KB. When uploading to the editor, it seems like even though the image is already POT, the editor resizes it anyways and blows up the size to 1.22 MB. Disabling the project setting that automatically resized images to POT fixed this issue. The change in asset size from resizing I understand, but the editor should know not to resize the image if it is already POT.

### Steps to Reproduce

1. Upload the attached 2048x2048 texture into the PlayCanvas editor.
2. The texture will initially show up as 606 KB in the editor, before jumping to 1.22 MB for seemingly no reason. Downloading this same asset confirms this is not a visual bug.
3. Uncheck "Texture POT" in the project settings.
4. Repeat step 1. This time the image asset will stay at 606 KB.

2048x2048 PNG (606 KB)
![orig_Normal(1)-fs8_test](https://user-images.githubusercontent.com/6013871/90046466-830f8f80-dc9e-11ea-8451-4ff3c9432bd5.png)

**Comment by yaustar** [comment]
It looks like the Editor importer is converting it from 8bits per pixel to 24bits per pixel hence the bump in size. Not sure if that's by design or a bug 🤔

**Comment by slimbuck** [comment]
This is a bug.

**Comment by Christopher-Hayes** [comment]
> It looks like the Editor importer is converting it from 8bits per pixel to 24bits per pixel hence the bump in size. Not sure if that's by design or a bug thinking

Hmm, interesting. Couldn't tell if the jump was from an optimization or not lol. The VRAM stays at 21.33 MB regardless, but not sure how performance compares.

**Comment by leonidaspir** [comment]
VRAM allocation will be the same, since all regular image formats (PNG or JPG) will get converted to RGBA or RGB maps when uploaded to the GPU. So for the same resolution the memory required is the same.

**Comment by yaustar** [comment]
The fix is now rolled out :)
