### ISSUE TITLE
Capsule collision shape is rendered at double the height set

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#123]
Height set at 2, being rendered at what looks to be 4.

![image](https://user-images.githubusercontent.com/16639049/90266154-7bd9b480-de4b-11ea-9889-948a0a9e962a.png)

**Comment by yaustar** [comment]
Looks to be due a recent change made when we added the cone collision @ellthompson

**Comment by albertvanveen** [comment]
I think the height that is displayed is correct. Since the model has a height of 1 unit, the collider has to be double as high  when it is 2 units and that is the case.

**Comment by yaustar** [comment]
Deployed
