### ISSUE TITLE
Editor memory issue after update to v1.47

### ISSUE THREAD

**Issue by IgorIFGD** [playcanvas/editor#1234]
After recent update, one of our projects began to load extremely slowly (taking ~5mins to load the editor on a PC with 64GB RAM, sometimes the editor tab just crashes with out-of-memory error). 
I suppose the issue is caused by the new console that currently shows 10.7k info messages (mostly about outdated material properties, a screenshot attached) that overloads the DOM.

Is there any way to disable/get rid of the new console and avoid these extreme loading times?

![image](https://github.com/user-attachments/assets/98e72a54-4632-4538-942b-e88ffeed5e89)
![image](https://github.com/user-attachments/assets/c2c056c6-5683-4834-b27a-02bed009532c)
![image](https://github.com/user-attachments/assets/00d8521b-b289-42a3-859e-5eec95356c71)

**Comment by slimbuck** [comment]
Ah sorry about this @IgorIFGD , we're on it.

**Comment by kpal81xd** [comment]
@IgorIFGD We have just deployed a patch to disable the console for now but you can still use the 'View history' button if you wish to see these messages
