### ISSUE TITLE
GSplat showing in Asset Viewer, but not in project

### ISSUE THREAD

**Issue by Cinewulf** [playcanvas/editor#1238]
### Description

Own Gaussian Splats, edited and exported to compressed PLY in current SuperSplat, do show up in the Asset Viewer, but not in the project (neither in the editor nor in the build). In the editor, there is also no bounding box shown.

Left: PC Editor, right: Asset Viewer
![PLY-editor-viewer](https://github.com/user-attachments/assets/f1dccba2-b949-4383-b965-a24348a71392)

Platform is Windows 11 Pro 23H2 (editor, build) and Android (build).
![WebGL_report](https://github.com/user-attachments/assets/f1796d39-855a-456b-896d-007e6759923b)

Source project is forked "3D Gaussian Splat Statues" (where, by the way, all Splats are showing up upside down and have a z rotation of 180°):
![project_3DGaussianSplatStatues](https://github.com/user-attachments/assets/9a6ccee7-e88b-4ec9-9779-fb451b1c2899)

### Steps to Reproduce

1. SuperSplat: Import PLY (exported from Postshot)
2. SuperSplat: Export as compressed PLY
3. PC: Import compressed.PLY into Assets Panel
4. PC: drag Gaussian Splat asset into viewport
5. optional. PC: with asset selected in Assets Panel, in Inspector open "Open in Viewer"

**Comment by slimbuck** [comment]
Hi @Cinewulf , release is complete. Please can you confirm it's working for you?

Thanks!
