### ISSUE TITLE
Select parent when entity has a child model

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#124]
I would like to request a feature that would allow to select the entity parent in the tree:

![image](https://user-images.githubusercontent.com/5677782/90283151-4f885d00-de78-11ea-91c3-72460314c0a3.png)

Steps to repro:
1. Create an empty entity
2. Add a child with a model component
3. Click on the entity from the viewer

Current behavior:
4. The child node is selected

Proposed change:
4. Parent is selected

Reasoning:
It is easy to select the entity in the viewer, then apply transformations only later realizing you did those on a child, instead of parent.

**Comment by yaustar** [comment]
I agree with the frustration but disagree on this particular solution. What happens in the case where you do want to select the child?

**Comment by vkalpias** [comment]
In the old days of PlayCanvas we had a right click menu when you clicked on an object in the scene that showed all the parents and let you select one.

**Comment by yaustar** [comment]
Can we have it back? 😅

**Comment by LeXXik** [comment]
Well, I see an object as a one complete entity in the viewer. I am simple man - I see an object, I click it because I want to do something with it. 
If I need a child, how would I select it from the viewer? What if my entity has several children?

If I need a child - I go to tree. If I pick something from viewer - I mean to pick the whole object.

**Comment by yaustar** [comment]
There are cases where you have parent entity and children entity are other objects such as a house, a fence, a tree etc.

If I clicked on something, I expect it to select the object I clicked on so I can move it.

**Comment by LeXXik** [comment]
Yes, you are right. An entity may be a composite of many models. I oversaw this simple issue, my bad. Probably no easy solution then.

**Comment by willeastcott** [comment]
I agree that there's no easy, generic solution here, so I'm going to close this issue.

**Comment by yaustar** [comment]
Was the right context menu not an option?

**Comment by willeastcott** [comment]
My thinking is that, if you're going to bring up the context menu, it's because you are *already aware* that the entity you're selecting in the 3D view is not the *actual* entity you want to select. And if that's the case, you might as well just go to the Hierarchy view. It's not going to stop you just left clicking an entity and moving it, unaware that you should have been moving the parent.

**Comment by yaustar** [comment]
I can see situations where it would be faster to do it in the the 3D view.

For example when there are multiple instances/copies of the same object, it's easier to right click on the object that I want to move, select the parent entity and move it vs trying to find the correct one in the hierarchy view.

Also, it's less mouse movement than having to continuously go from 3D view, hierarchy view to select the parent and back to the 3D view to use the gizmo.

Especially when moving/editing lots of entities.

**Comment by yaustar** [comment]
Thinking out loud here, could we have a grouping feature that would allow the user to say, 'this entity and all its children are one selectable group' so that selecting any entity in that group automatically selects the parent?

This type of problem could show up more when we start introducing model assets as templates/heirachy  
and every graphnode is selectable.

**Comment by willeastcott** [comment]
@vkalpias and @Maksims - can you remember why we removed that feature from the context menu?

**Comment by vkalpias** [comment]
> @vkalpias and @Maksims - can you remember why we removed that feature from the context menu?

I do not remember, it's possible we just missed it. Might be useful to check how other engines handle this issue as well.
