### ISSUE TITLE
On page loading, console is maximized, and then plays animation for minimizing.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#1240]
When Editor is loaded, it has console maximized, then it plays animation for minimizing. This is consistent if hierarchy or inspector panel is minimized, but by default, these panels are maximized, while console by default is minimized.

It should not play such animation, and ensure when Editor is open, there is no weird flickering and animations (which leads to viewport resizes and re-renders) so it slows down startup time.

**Comment by kpal81xd** [comment]
Just updated editor fix for this should be live
