### ISSUE TITLE
Enable value draggers on light component properties

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#125]
![image](https://user-images.githubusercontent.com/5677782/90486261-601f2880-e141-11ea-89f6-43a352b3827a.png)

Feature request: enable value draggers (dragging? not sure how to call them - the ability to control the input numbers with a mouse) for the directional and spot light properties like range and angle.

**Comment by willeastcott** [comment]
@LeXXik, are these draggers not sufficient:

![dragger](https://user-images.githubusercontent.com/697563/199567777-db95aaad-4ffb-440b-bb1b-caf9e48dc140.gif)

**Comment by LeXXik** [comment]
@willeastcott yes, they are, thank you! I believe they were not available at the time of writing the issue. We can close this now.
