### ISSUE TITLE
Number fields to accept , as a decimal separator 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#126]
https://forum.playcanvas.com/t/playcanvas-editor-feedback/616/322?u=yaustar

The number field should accept `,` as well as `.` for decimal separator

**Comment by jarileon** [comment]
Is there any estimate on when this would be implemented @yaustar ? The lack of comma support int he number fields make it quite irritating to use the editor when all your decimal numbers resolve to zero.

**Comment by yaustar** [comment]
No estimate on this at the moment unfortunately. As it's part of PCUI which is open source now, someone could add the support as a PR and we can merge that in.

**Comment by slimbuck** [comment]
Closing here in favour of https://github.com/playcanvas/pcui/issues/20

**Comment by yaustar** [comment]
Now on Prod :) thanks to https://github.com/playcanvas/pcui/pull/21
