### ISSUE TITLE
Margin precision in editor

### ISSUE THREAD

**Issue by Cr0c81** [playcanvas/editor#127]
Margin values rounded to 1/100, can not set 1/1000 and less.
If screen is 1900+ size - margin minimal distance is 19+px (((

**Comment by mvaligursky** [comment]
another one like this
https://forum.playcanvas.com/t/material-offset-and-tiling-values-decimals/15418

**Comment by LeXXik** [comment]
Met this issue when I had a ball I needed to add a collision component to. The ball real life diameter was 5.7 cm, which makes the collision radius of 0.0285 in Editor. The Editor didn't allow to enter it, so had to create the collision component through the script.

**Comment by Cr0c81** [comment]
> Met this issue when I had a ball I needed to add a collision component to. The ball real life diameter was 5.7 cm, which makes the collision radius of 0.0285 in Editor. The Editor didn't allow to enter it, so had to create the collision component through the script.

This not worked if You create UI design.

**Comment by ellthompson** [comment]
A fix for this has been released for the editor. The default precision for numeric inputs is now 7. Closing this issue.
