### ISSUE TITLE
Extend the particle system

### ISSUE THREAD

**Issue by SophieRefshauge** [playcanvas/editor#13]
**Particle system wishlist:**
~- Blend modes on colour tab (different blendmodes on top of alpha sprite basically (add, mult, overlay)~ now separate issue https://github.com/playcanvas/engine/issues/2547
~- Start scale on sprite~ now separate issue https://github.com/playcanvas/editor/issues/217

- Use sprites from texture atlas instead of single textures

*Edit: Split up this issue in common wish list and particle randomization (new issue)

**Comment by ellt92** [comment]
Hi Sophie. All of these features seem really valuable. Most of the features related to randomisation per particle can likely be implemented together. I'm thinking that'd be a good first feature. Do you mind splitting that out into its own issue? Listing all of the different types of per particle randomisation that you're likely to need.

**Comment by SophieRefshauge** [comment]
Hi Elliott,
I'll get on it right away.
- Sophie

**Comment by yaustar** [comment]
Closed as we now have split issues
