### ISSUE TITLE
Video texture tutorial doesn't load video asset (401) on Safari with Launch Tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#131]
Try to launch https://playcanvas.com/editor/project/405850 in Safari.

The video playback will show a 401 error and this might be due to Safari sandboxing video playback and that access to the video file in the project requires user authentication? 

See this post for more details: https://stackoverflow.com/a/14699507

This isn't an issue for the published builds as the video file doesn't require authentication to access.

**Comment by willeastcott** [comment]
The scene runs fine in the launcher in Safari 17.5 on macOS Sonoma 14.5. Closing.
