### ISSUE TITLE
Directional light arrow disappears

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#141]
When selecting the directional light, the light direction arrow sometimes disappears from the 3D view.

How to reproduce:

- Add a directional light to the scene, if it doesn't exist yet.
- Select the light from the hierarchy tree - the light is selected and the direction arrow is visible in the 3d view
- Select something else from the tree, and select the light again - the arrow is not visible

In order to make it visible again, you would need again to select something else, then the light.

**Comment by willeastcott** [comment]
I am unable to reproduce this. 

![light-arrow](https://user-images.githubusercontent.com/697563/97587670-8be94500-19f3-11eb-9976-1f705bf4bc61.gif)

(Ignore the long delay after I click entities in the hierarchy before the arrow appears or disappears - my laptop has performance problems at the moment and recording video didn't help!) 😄

**Comment by LeXXik** [comment]
Thank you for the video, Will! 

I noticed the issue when I was tweaking the lights in this project:
https://playcanvas.com/editor/scene/976047

However, it looks like I am no longer able to reproduce it either. I'm pretty sure it was there when I was reporting it, though :) Please, feel free to close the issue.

**Comment by willeastcott** [comment]
Ahh OK. We have been working hard to resolve front-end exceptions so maybe this got fixed as a side effect! 😄 

If this happens again, please don't hesitate to reopen the issue!
