### ISSUE TITLE
json schema attributes are mutated when using enums

### ISSUE THREAD

**Issue by TheJonRobinson** [playcanvas/editor#146]
### Description

When reusing a json schema with enums, the first use works but all subsequent uses cause an editor error. Tracing this down, it seems like the enum part of the schema is mutated into a form which makes it incorrect to pass to another script.

The code snippet below demos this.

### Steps to Reproduce

```
var barSchema = [{
  name: 'someEnum',
  type: 'number',
  "enum": [{
    'valueOne': 1
  }, {
    'valueTwo': 2
  }, {
    'valueThree': 3
  }]
}];

// This works...
var fooScript = pc.createScript('Foo');
fooScript.attributes.add('bar', {  type: 'json', schema: barSchema });

// But this doesn't as the above seems to mutate barSchema
var fubarScript = pc.createScript('Fubar');
fubarScript.attributes.add('bar', {  type: 'json', schema: barSchema });
```

**Comment by vkalpias** [comment]
Thank you, this should now be fixed.

**Comment by TheJonRobinson** [comment]
Thanks for the quick fix!
