### ISSUE TITLE
Editor view disappears on tab changes

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#16]
### Description
If I switch to another tab from PlayCanvas editor and get back to editor, editor view disappears. To fix that I click full screen button or resize all browser to fix it. That fixes issue, but for some reason it disappears and stays like this.

### Steps to Reproduce

1. Open PlayCanvas editor and open a scene.
2. After few seconds change tab to another and wait on tab for a while.
3. Come back to PlayCanvas editor, you'll see it displays gray background, that's all.

I think for some reason it turns idle mode and resizing make it work again. That issue started to occur 1 months ago. I use Macbook Pro 2017 and Chrome browser.

I believe in that Chrome kills canvas context to save up battery, I noticed this behavior on other applications too. When I get back to tab, onfocus function can trigger resizing and that can simply fix issue.

Here is a gif to show you process, (pause looping) :
https://gyazo.com/586bbba5337f0362498420e11c7833e7

**Comment by willeastcott** [comment]
Hi @devcem - I've not been able to reproduce this problem. Is it still affecting you?

**Comment by devcem** [comment]
> Hi @devcem - I've not been able to reproduce this problem. Is it still affecting you?

No @willeastcott I think it's fixed now. I'm also not able reproduce it. Maybe something to do with Chrome browser.

Closed issue.
