### ISSUE TITLE
Investigate rendering error when mouse wheel zooming

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/editor#164]
When I zoom in and out of the editor view using the mouse wheel, the following message gets printed to the console:
```WebGL: INVALID_VALUE: uniform4fv: invalid size```

I don't see any rendering issues in the viewport.

**Comment by willeastcott** [comment]
FYI: I can't repro this on Windows in Chrome.

**Comment by willeastcott** [comment]
@slimbuck This was logged a very long time ago. Presumably this was either fixed or isn't much of an issue. You might want to check whether it's still happening. But I'm closing this for now.
