### ISSUE TITLE
Hierarchy search scrollbar not visible anymore

### ISSUE THREAD

**Issue by FrantzVZ777** [playcanvas/editor#166]
The hierarchy search scrollbar does not appear anymore.

How to reproduce:
1. Make lots of duplicated objects with same name to fill up the entire hierarchy panel
2. Search the object name
The result list of objects is not scrollable anymore so you cannot see the entire list as it is cropped...

**Comment by ellthompson** [comment]
Thanks for posting. A fix for this will go out with the next release of the editor!
