### ISSUE TITLE
Users can select the canvas on iOS

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#167]
On iOS devices, holding down a finger on the canvas will select it
![image](https://user-images.githubusercontent.com/16639049/94679427-fc7b4400-0317-11eb-8247-110a876ec829.png)

There is a temporary fix here: https://playcanvas.com/project/722923/overview/ios-select-canvas-fix

We will need to add these CSS rules to the launch page and publish templates.

Test plan:
TBD:

**Comment by Maksims** [comment]
Adding `user-select: none;` to `body` element, can lead to unwanted issues: none of child elements will be selectable. This is not desirable in cases where people use DOM for their UI.

So only add such CSS to `canvas` element, and not `body`.

**Comment by yaustar** [comment]
Ah, good shout 
> none of child elements will be selectable

I checked for interactivity but not being able to select the elements.

**Comment by yaustar** [comment]
Without the body CSS, I can still select part of the page 🤔 Will need more consideration here :( 

![image](https://user-images.githubusercontent.com/16639049/94703576-e335c000-0336-11eb-9226-70bba9a1586f.png)

**Comment by Maksims** [comment]
And what about `contextmenu` event on canvas? Is it caught and used `preventDefault` and `stopPropagation`?

**Comment by yaustar** [comment]
Related issue https://github.com/playcanvas/engine/issues/2619

**Comment by yaustar** [comment]
Duplicate of #160
