### ISSUE TITLE
More options for particle randomization

### ISSUE THREAD

**Issue by SophieRefshauge** [playcanvas/editor#17]
Extend the particle system to include more options for randomization:

- Choose random colour on particle spawn (from specific user set selection of colours)
- Choose random sprite in sprite sheet on particle spawn (not for animation purposes but for sprite variance within one particle system)
- Choose random start scale (between min and max value)
- Choose a random number of particles on particle spawn (between min and max values)

@ellt92

**Comment by ellt92** [comment]
Thanks Sophie, i've assigned myself to this feature. I'll begin investigating this now.

**Comment by ellt92** [comment]
Hi Sophie, here's a quick update on this feature.

Colour:
This seems to be tricky to implement with the current editor/engine setup. This feature would require a deeper restructure of the current particle system so i'm going to shift my focus away from this for the time being.

Sprite:
I've created an implementation for this in the engine and will expose this to the editor once the next engine release is out. Essentially it allows you to define the number of animations that are contained within a particle systems sprite sheet. The editor will then allow you to switch on a 'randomise animations' toggle, which will randomly select one of these animations per particle. For this requested feature, each sprite in the sprite sheet can be set as an animation containing a single frame.

Scale:
Currently the scale can be randomised in the editor by turning on the randomise switch when editing the particle systems scale curve. You can then define both a min and max curve, with values randomly selected between these ranges.
![image](https://user-images.githubusercontent.com/1721533/76339042-7f439f80-62f1-11ea-8807-4ac2ca34758f.png)

Number of particles:
Currently you can randomise the emission rate of the particle system so the amount of particles in the system can fluctuate over it's lifetime. If you select the prewarm option, the amount of initially spawned particles will be randomised by this range too. Does this cover the functionality you need?

**Comment by SophieRefshauge** [comment]
Number of particles:
Typically I use the particle system to create short bursts of particles (one emission per play). So the lifetime is very short and all the particles spawn at almost the same time. For greater variety, being able to set an initial random number of particles spawning would be helpful, otherwise it will always spawn exactly the number I've plotted into particle count. Using the pre-warm option here is not sadly not valid, since I still want the particles to burst out instead of bluntly being there from the beginning.

Scale:
If I use the scale randomisation like this, won't the scaling over lifetime be random too?
If I want the particles to follow a particular curve relatively, but still vary in size on spawn, I would need to set the initial scale on spawn, and not over lifetime.
The way the curves are editable now it's difficult to match the min and max curve to each other. I would prefer being able to separate the initial scale from the animation over lifetime.

Sprite:
Sounds very cool - looking forward to using this. I've noticed that running animated sprite sheets from within a particle system seems a little perfomance heavy on mobile. Is that a concern with this approach?

Colour:
Sad to hear that, since it would greatly optimise the number of particle systems needed for an effect. Currently my workaround is duplicating the entire system, which is not very iteration-friendly. I hope that you can find the time later on. :)
**Maybe a copy settings/preset system could be useful in the meantime?**

**Comment by ellt92** [comment]
Hi @SophieRefshauge, i've made some changes to the editor to enable the sprite randomisation feature. It would be great to get your feedback on it! If you can post your playcanvas username here i'll turn on the feature for you before it's release.

With regards to the number of particles: It's a good point that you raise with the short burst use case. I'll have a look into the viability of introducing this. I also understand that it's not ideal to match two curves with each other to get equal scaling of all particles, I can raise the issue with our designer. For your idea about the copy settings / preset system, this is definitely something i'll keep you posted on!

**Comment by SophieRefshauge** [comment]
@ellt92 That would be great. My username is woolypolygon.

**Comment by ellt92** [comment]
@SophieRefshauge Thanks, I've added the feature to your account. Please let me know how you get on!

**Comment by SophieRefshauge** [comment]
@ellt92 - I don't see any change in the particle system. Is there something I need to check or do to get the update?
Can I use it in a project shared with other people?

**Comment by ellthompson** [comment]
I'm closing this issue as sprite randomisation options have been released in the editor.
