### ISSUE TITLE
Editor Feature Request: Unique Names when Duplicating Entities (solution included)

### ISSUE THREAD

**Issue by Mentos-** [playcanvas/editor#172]
One feature I miss coming from UE4 is the unique name duplicated actors are given. So if you have a 'Box' actor in UE4 and duplicate it, a new actor with the label 'Box2' will be created. If you select two actors 'Box' and 'Box2' and duplicate them, then 'Box3' and 'Box4' will be created.

It does not look like the editor.js code is hosted on Github for Pull Requests though?

Here's a text file [uniqueNameWhenDuplicatingEntities3.txt](https://github.com/playcanvas/editor/files/5336331/uniqueNameWhenDuplicatingEntities3.txt) which has the necessary functions to implement this.

With those functions added to /* editor/entities/entities-duplicate.js */ you would just need to add the following line of code at line 34358 (in editor.js)
 
![editorNewLine](https://user-images.githubusercontent.com/3871989/95131679-7b171d80-072c-11eb-9a37-b406e9ddba91.png)

Let me know what you guys think and if maybe there is a way to make a pull request for this I'm not aware of!

**Comment by Mentos-** [comment]
I refactored one of the functions after realizing there was some redundant code. 'uniqueNameWhenDuplicatingEntities3.txt' should represent the latest solution

**Comment by ellthompson** [comment]
Thanks for this @Mentos- ! You're right in that the editor codebase isn't public on github. I've gone ahead and integrated your code snippet into the codebase and it'll go out with the next release :).
