### ISSUE TITLE
Grab slider without changing current value

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#173]
It is not possible to grab the slider without changing the current value.

Before click, mouse hovered over the slider:
![image](https://user-images.githubusercontent.com/5677782/95241037-ebe63480-0815-11eb-8832-b090d28d758d.png)

Immediately after the click, mouse button pressed, mouse was not moved:
![image](https://user-images.githubusercontent.com/5677782/95241203-1c2dd300-0816-11eb-9c58-a3216555eb7c.png)

This makes it hard to do small adjustments to the current values.

Suggestion: before and after click the value should remain the same, if mouse was not moved.

**Comment by ellthompson** [comment]
Hi @LeXXik , thanks for posting this issue. Since open sourcing the [PCUI library](https://github.com/playcanvas/pcui), this issue will need to be addressed there. Would you mind creating an issue in that repo? After it's fixed in PCUI the editor will pull through the changes.

**Comment by LeXXik** [comment]
@ellthompson right, I moved it to the PCUI. Thank you for pointing to the source, I assume you want me to submit a PR? :) I will look into it during the weekend.
