### ISSUE TITLE
Specify power preference for WebGL when creating the Engine

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#175]
There has been a change to Chrome's default power preference for WebGL sometimes before Dec 2019. This only affects dual-GPU MacBook Pros right now, but may affect Windows machines in the near future.

Chrome used to treat WebGL's "default" powerPreference context creation option as "high-performance". In order to save battery life and improve the user experience on these dual-GPU machines, the default has been changed to "low-power".

PlayCanvas does not provides authors explicit control of this setting, but would be worth giving them the option to set it to 'high-performance', at least, if they have a game with expensive shaders or geometry and want to force the high-performance GPU. Note there is a user experience cost with using this setting; the system hitches for ~1 second when switching back and forth between the integrated and discrete GPUs.

P.S. Safari on macOS has had this behavior for some time now.

Further reference to this:

https://twitter.com/gfxprogrammer/status/1308912968076341249
Very nice! Would you consider using { powerPreference: 'high-performance' } in your context creation attributes? And avoid { alpha: false }? These will make it run much better on MacBooks. Thanks!

**Comment by mvaligursky** [comment]
also logged here
https://jira.sc-corp.net/browse/PAC-3084

**Comment by marklundin** [comment]
Ahh, just raise an issue for this in https://github.com/playcanvas/engine/issues/2471, but I believe this is actually more editor related

**Comment by willeastcott** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/697563/97579317-d1a11000-19e9-11eb-8281-1143ecd612e8.png)
