### ISSUE TITLE
search list multiple selection with Shift not working

### ISSUE THREAD

**Issue by FrantzVZ777** [playcanvas/editor#182]
After performing a search of items in the hierarchy panel, it is impossible to do a multiple selection with the shift key.

Click the first item, then press the SHIFT key and hold it. Click the last item and release the SHIFT key. 
This works in the hierarchy panel, but is broken once you are in the result list of a search.

<img width="305" alt="Screenshot 2020-10-12 at 11 06 47 AM" src="https://user-images.githubusercontent.com/25144112/95701153-65997a80-0c7b-11eb-85ff-b4a79224eab2.png">

**Comment by willeastcott** [comment]
I believe this is now fixed. @FrantzVZ777 - can you verify please?

**Comment by FrantzVZ777** [comment]
Yes it does but it is struggling when the parts are in different sub groups in the hierarchy.
I have hundred of road tiles in different groups in my hierarchy and can’t select them properly with shift when I type the road keyword in the search field.

If they belong to the same group no problem but with sub group the behaviour is broken.

W


Frantz Lasorne, Visionaries 777
Co-Founder
frantz@visionaries777.com <mailto:frantz@visionaries777.com>
http://visionaries777.com/ <http://visionaries777.com/>
M: (+852) 9276 1777
Level 4, Wing Hing Commercial Building, 16 Sutherland Street, Sheung Wan, Hong Kong

Anticipating the Future

**Comment by willeastcott** [comment]
What do you think @vkalpias?

**Comment by vkalpias** [comment]
Indeed - this should now be fixed as well.

**Comment by willeastcott** [comment]
Yes, I have verified. Thanks @vkalpias!!! 🎉
