### ISSUE TITLE
Allow script assets to be added to the document as an ES6 Module

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#184]
This will allow developers to start importing module libraries which is common in the web library eco system

See thread: https://forum.playcanvas.com/t/using-es6-modules-in-online-editor/6896/7?u=yaustar

**Comment by willeastcott** [comment]
@marklundin Presumably all your work on ESM scripts covers this? Therefore, I'm closing this but reopen if I am misunderstanding.
