### ISSUE TITLE
Mesh Instances no longer show mesh names

### ISSUE THREAD

**Issue by RipcordDev** [playcanvas/editor#187]
### Description

Models selected in the editor no longer show the name of the mesh instances when selecting Asset or Entity Materials.

![image](https://user-images.githubusercontent.com/60748378/96946019-34a41b80-14ad-11eb-87ed-f48b360b00e4.png)

Beside each mesh instance ID it used to say the name of the mesh, now it only says node for each.  My projects tend to use a lot of common materials so this makes assigning materials a guessing game.  

This seems to affect both new and old projects.

Windows / Chrome Version 86.0.4240.75

### Steps to Reproduce

1. Select any Model type asset in the editor
2. Expand the Mesh Instances rollout
3. All of the mesh instances will be named node rather than the names assigned in the 3D modeling program

**Comment by vkalpias** [comment]
@slimbuck this is an issue only with GLB models. For JSON models we downloaded the model JSON and read the node names. With GLB we can't do that but probably won't need to do anything since we won't have a model asset generated eventually...

**Comment by slimbuck** [comment]
Perhaps we can add these to the model metadata for GLB?

**Comment by vkalpias** [comment]
This should now be fixed.
