### ISSUE TITLE
Editor is unable to parse extended scripts

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#188]
Consider the following 2 scripts:

```
/* jshint esversion: 6 */
class MyBaseScript extends pc.ScriptType {...}
pc.registerScript(MyBaseScript , 'myBaseScript ');
```

```
/* jshint esversion: 6 */
class MyDerivedScript extends MyBaseScript {...}
pc.registerScript(MyDerivedScript, 'myDerivedScript');
```

`MyDerivedScript` script works fine if the application is launched, but the Editor fails to parse it, when the Parse button is clicked. It complains that "MyBaseScript" is undefined.

**Comment by LeXXik** [comment]
@marklundin is `./MyDerivedClass.mjs` is relative to the script that imports it, or is it the assets root?

**Comment by marklundin** [comment]
It's relative to the importing file, although these relative paths depend on a separate editor update which should be happening today.
