### ISSUE TITLE
Read only Editor project, script component is not interactive.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#192]
When selecting script component on readonly projects, it does not allow to view script file from component panel.

![image](https://user-images.githubusercontent.com/636263/97039174-ad21df80-1574-11eb-83fc-a622e5b5dc40.png)
**Yellow** - this button should open Code Editor, just like "View" button when selecting script assets.
**Red** - those elements should be hidden when viewing with readonly.
~~**Blue** - should not be clickable in readonly.~~

**Comment by yaustar** [comment]
I think blue should be clickable as it shows the asset in the assets panel IIRC.

**Comment by Maksims** [comment]
> I think blue should be clickable as it shows the asset in the assets panel IIRC.
You right.

**Comment by willeastcott** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/697563/97579092-8b4bb100-19e9-11eb-883e-f97d94cc2db3.png)
