### ISSUE TITLE
Read only, context menu is not working.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#193]
When in Editor in readonly mode, it does not allow to copy entities and assets. With recently added features to PlayCanvas to copy assets cross-projects, this would be very useful to benefit the community.

Provide context menu with: copy option for hierarchy.
Provide context menu with: copy, download, view (code, text, glb, etc) options for assets panel.

**Comment by yaustar** [comment]
Thankfully the copy hotkey does work but yes, it would really help to have the context menu.

**Comment by willeastcott** [comment]
Fixed.
