### ISSUE TITLE
Number type Script Attributes only have 2 decimal points of precision

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#195]
![20201026-2006](https://user-images.githubusercontent.com/16639049/97222294-13517100-17c6-11eb-862f-5404cf3afdb1.gif)

**Comment by yaustar** [comment]
I believe this used to be at least 3 from memory

**Comment by vkalpias** [comment]
You can specify the `precision` in the script attribute. e.g.
```
Script.attributes.add('attribute', {type: 'number', precision: 5})
```

**Comment by yaustar** [comment]
Thanks! Has the default changed? I don't remember 2 decimal places being the default 🤔

**Comment by yaustar** [comment]
Looks like this will be fixed via: https://github.com/playcanvas/pcui/pull/31

**Comment by vkalpias** [comment]
You can set the precision of numeric script attributes in the script attribute directly e.g.
```
Script.attributes.add('numeric', {type: 'number', precision: 10})
```
Changing the default precision to 7 might cause a lot of numeric inputs to store all the little JavaScript related imprecisions
