### ISSUE TITLE
Source model file inspector contents CSS needs corrections.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#196]
Upload FBX file with multiple textures and materials.
Select that FBX file after it is processed, in Inspector information will be styled badly:

![image](https://user-images.githubusercontent.com/636263/97224527-ec9d3580-17d9-11eb-89dc-62fef51b0356.png)

**Comment by vkalpias** [comment]
Thanks fix hasn't been deployed yet :)

**Comment by vkalpias** [comment]
This should be fixed now.
