### ISSUE TITLE
Project settings > Script Loading Order > style is off

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#197]
Each script now looks like its missing background.
Please check other panels, such as Layers, as it has missing backgrounds and some borders as well.

![image](https://user-images.githubusercontent.com/636263/97229660-608f0c00-17e1-11eb-8d30-7d8e0b4630be.png)

**Comment by vkalpias** [comment]
Hi!

I'm not able to reproduce this although we had some major CSS refactoring deployed today which might be responsible for fixing it?

**Comment by Maksims** [comment]
Yes, can verify it is fixed now.
