### ISSUE TITLE
Offer Draco compression for GLBs generated on import

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#206]
An option to apply Draco compression to GLB files generated on import of FBX files should be added to the Editor. For now, it could live alongside the Convert to GLB checkbox in Asset Tasks section of Project Settings. Under the option, when checked, an 'Import Draco' button should be enabled, which would import the Draco WASM decoder into the Asset Panel for the project.

**Comment by valentincognito** [comment]
Any updates on this one ? Having GLB compression really would be a must have for lighter projects

**Comment by yaustar** [comment]
Unfortunately, no update on this. The current workaround is to publish a build and compress the GLBs at that stage with a script and including the Draco WASM in the project.

**Comment by willeastcott** [comment]
This is now implemented:

https://blog.playcanvas.com/draco-mesh-compression-arrives-in-the-playcanvas-editor/

Closing.
