### ISSUE TITLE
Server-consistency

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#208]
Hello. 
The AWS-server that runs the edtior often seem to become unstable from 16:00 hours to 24:00 hours CET?
Can this be dealt with? Either by fixing it or if not possible, please make notifications to when updates or other things are being done to the editor and or/server.
//br Thomas

**Comment by yaustar** [comment]
Hm. I'm not aware of outstanding issues with the service during these times. 4pm CET is roughly when the US starts working up so maybe it's due to extra load?

What do you mean by unstable? Is it a particular set of operations such as texture compression? Are assets missing? etc

**Comment by FutureFireplace** [comment]
Many of times, when creating a 'New folder' in the editor, or while editing a script, the editor and launcher seem to lag quite a bit, and I do have to refresh to see the folder and/or see the script alterings work. These effects seem to get worse at the mentioned hours. ... can live with it, but not optimal.

**Comment by slimbuck** [comment]
Hi @FutureFireplace,

We're really sorry to hear about the problems you've been experiencing, it must be super frustrating. Just know that we take the editor experience very seriously and are working hard to improve our backend. Please keep reporting specific issues as you notice them, this might help us isolate the issues on our side.

Thanks!

**Comment by FutureFireplace** [comment]
Thanks a lot. As yaustar mentioned the World Clock trend with the US coming online at that moment might be the issue (with US users feeling the same challenges off course).
The improvement seem nessesary + constructive - from here on forward all will benefit.

{Good to get this kind of feedback, from this 'part of the PC island' :-)  }

**Comment by yaustar** [comment]
We have recently made major improvements to the backend. Please re-open if you are still running into similar issues.
