### ISSUE TITLE
Parallax's strength description is incorrect

### ISSUE THREAD

**Issue by gameatp** [playcanvas/editor#21]
![3](https://user-images.githubusercontent.com/4427058/75837774-d1bc2200-5e00-11ea-8a13-ea5eb45143da.jpg)

**Comment by willeastcott** [comment]
Well noticed! Thanks for the bug report. But actually, this has already been fixed in the Editor codebase. The material inspector is now completely rewritten, but it still not enabled for all users. I'll get the team to deploy this update today hopefully. I'll close this for now.
