### ISSUE TITLE
View Conflicts in merge tool crashes browser tab on very large text files

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#213]
With very large text files such as those built from Type Script can cause the view conflicts window to close the tab and any linked tabs.

Ideally, if a file is too large, we should treat it as a binary and only ask the user to choose one branch or the other.

Looks like it is 'stuck' in this while loop:
```
    MergeFileEditor.prototype.createDstOverlays = function () {
        var content = this.cm.getValue();

        var match;
        while ((match = REGEX_DST_BRANCH.exec(content)) !== null) {
            var startPos = this.cm.posFromIndex(match.index);
            startPos.line--;
            var endPos = this.cm.posFromIndex(match.index + match[1].length);
            endPos.line--;

            this.createOverlay('dst-branch', config.self.branch.merge.destinationBranchName, startPos, endPos);
        }
    };
```

The workaround proposed for this is to use pcignore.txt but that cause data lost on attributes on merges. It requires the team to commit code in both branches, parse the scripts in both branches and then merge the branches in PlayCanvas which is error prone.

Video attached here: [Kapture 2020-11-05 at 14.41.17.mp4.zip](https://github.com/playcanvas/editor/files/5495085/Kapture.2020-11-05.at.14.41.17.mp4.zip)

I also have a private test project that repos the issue.

**Comment by vkalpias** [comment]
Should be fixed now
