### ISSUE TITLE
Light Mapper Baking button never releases previous allocated GPU memory

### ISSUE THREAD

**Issue by valentincognito** [playcanvas/editor#214]
### Description

I don't think I have ever noticed this issue before so I don't know if it was introduce recently but it's a pretty major red flag bug. In the editor every time you rebake the lightmapp of the scene it uses more and more GPU memory until you eventually run out of it. On a medium size scene (100 unique static lightmapped objects) You reach the full capacity of your GPU in 3 to 4 clicks on the light mapper baking button.

### Steps to Reproduce

1. Populate your scene with object with the lightmapped option enabled
2. Add a light that affect lightmapped objects 
3. Click a few times on the ligthmapp baking button
4. Observe the GPU memory usage

**Comment by mvaligursky** [comment]
fixed by https://github.com/playcanvas/engine/pull/2779
(should be released within a week)
