### ISSUE TITLE
Asset missing from downloaded build. 

### ISSUE THREAD

**Issue by aprice-sbg** [playcanvas/editor#22]
### Description

We have an asset that does not appear in a downloaded build of the project.  When viewing the asset via the editor's asset registry, it shows up with a red stripe under the file name, and an "Failed" entry saying "Op submit failed. Maximum submit retries exceeded"

* URL to a simple, reproducible test case that illustrates the problem clearly: Project is private
* Screenshots
[Asset in editor](https://i.imgur.com/GUcjss9.jpg)
* The platform(s)/browser(s) where the issue is seen: all platforms

### Steps to Reproduce

1. See that asset with ID 26681243 exists in asset registry (styles.css)
2. Go to Publish -> Download .ZIP -> Select all scenes -> Download
3. Unzip build and find that folder 26681243 does not exist and styles.css does not exist.

**Comment by halvves** [comment]
Hi @aprice-sbg. I am having trouble reproducing this bug. Are you able to right click the asset and download it via the context menu? If so, it might be possible to fix by re-uploading it. Not ideal, but it seems something has gotten the asset is in a strange mixed state.

**Comment by halvves** [comment]
Hey @aprice-sbg. Just checking in to see if you were able to clear this up by downloading/re-uploading the problematic asset.

**Comment by aprice-sbg** [comment]
Hi. The problem resolved itself without re-uploading the asset. A few days later, the error cleared and assets are now built including the file... closing.
