### ISSUE TITLE
GLB missing UV1

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#220]
After importing an FBX with generated UV1 and having a project setting that converts to GLB, the Editor says that the UV1 is missing on the GLB asset. However, baking a lightmap works, so the engine is actually using the channel. 
Auto-baking is not working, though, since it complains of the missing channel.

**Comment by yaustar** [comment]
@LeXXik Do you have an example FBX that you can share (either publicly or privately?)

**Comment by raytranuk** [comment]
May be related to: https://github.com/playcanvas/engine/pull/2558

(however more likely asset import - because description in this bug indicates engine-side is working?)

**Comment by LeXXik** [comment]
Right, @raytranuk , I think the engine side is working, since the UV1 channel is used. I have sent an FBX model to @yaustar . Hopefully he can reproduce it.

**Comment by shreddox** [comment]
I just had the same problem. My glbs don't recognize the second UV channel (exported from Maya), the json ones do. This seems to be a problem on every model.

**Comment by mvaligursky** [comment]
I tried to reproduce this on a dash_board.fbx imported as glb that @yaustar has given me and all seems to work .. perhaps this has been fixed? I can set up diffuse texture to use both channel 0 and channel 1. I can also bake lightmaps - even though it seems uv1 channel is not properly unwrapped, and so the lightmap does not look very good. But this matches the result to when I import the mesh as a json model.

I'll close the ticket, but if somebody has some other mesh that lightmapping works on when imported as json but not as glb, please reopen it with a repro project / fbx file.
