### ISSUE TITLE
Text input field of an element is to small

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#223]
### Description
The text input field of an element is to small. Selecting text results in scrolling and makes it impossible to select the correct text.

![image](https://user-images.githubusercontent.com/52896137/99192002-a8fe7180-2770-11eb-9b7f-6e85f1b449ba.png)

I would strongly recommend to increasing the height of the field.

### Steps to Reproduce
1. Create a text element
2. Add some text
3. Try to select two rules of the text

**Comment by yaustar** [comment]
This is now a resizable text box :)
