### ISSUE TITLE
Disable fog and lighting in the Editor view only

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#226]
On some projects such as an open world area, it would be great to disable fog and lighting in the Editor view only to make it easier to work with.

In the 5 Seals game where fog is heavily used, zooming out to make edits is more difficult as everything gets affected by fog
![image](https://user-images.githubusercontent.com/16639049/99247936-941cef00-27ff-11eb-8283-039e154acb37.png)

Same again in a horror style game where there is only one dynamic light as a flash light.

**Comment by Maksims** [comment]
I did faced same issue several times as well. Would be nice to have some "quick settings", in viewport, similar to Physics View checkbox, that would be able to enable/disable certain features of a renderer, like lights and fog.

**Comment by yaustar** [comment]
Re-bumped from a discussion with a client

**Comment by yaustar** [comment]
Thumbnail previews are also affected

**Comment by mvaligursky** [comment]
this is now done @yaustar ?

**Comment by yaustar** [comment]
Not published to production yet

**Comment by yaustar** [comment]
Now released as part of Editor release v.1.19.5
