### ISSUE TITLE
Support Roughness property and maps in Standard Material: Editor

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/editor#229]
This issue is linked to an Engine issue: https://github.com/playcanvas/engine/issues/2559

To properly support using roughness instead of shininess/glossiness for in new materials.

The work involved in this issue is:
1) Expose a `use roughness` tick box to switch to show and edit roughness in material properties in the editor.

**Comment by yaustar** [comment]
Released in [1.24.0](https://github.com/playcanvas/editor/releases/tag/v1.24.0)
