### ISSUE TITLE
Offset & tiling settings are not saved

### ISSUE THREAD

**Issue by qWici** [playcanvas/editor#23]
### Description
Any settings for "Offset & tiling" are not saved. 

*URL*: [Test project](https://playcanvas.com/project/669645/overview/test_ui)
*Video*: [on vimeo](https://vimeo.com/395711501)
*Browsers:* testing on Chrome 80.0 and Safari 13.0.3

### Steps to Reproduce

1. Choose material
2. Make some changes in "Offset & tiling"
3. Click on another asset or reload page
4. Check "Offset & tiling" changes

**Comment by vkalpias** [comment]
Hi this should be fixed now.
