### ISSUE TITLE
If processing the font is done when the font is not selected, process font button is disabled

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#232]
Import a font
Click on process font
While the font is process, select another asset
Wait for the font to finish processing (orange circle stops spinning)
Select the font again
See that the process font button is disabled
Fix is to refresh the browser

![Kapture 2020-11-17 at 13 08 41](https://user-images.githubusercontent.com/16639049/99394368-af0e6280-28d6-11eb-97ef-59aa40eaf242.gif)

**Comment by vkalpias** [comment]
Fix will be deployed with next release.
