### ISSUE TITLE
Uncaught ReferenceError: log is not defined

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#233]
Under some circumstances an exception occurs in the opened launcher while working with the Editor. I found a case that allows to reliably reproduce this:

https://playcanvas.com/editor/scene/1034845

There is a script attached to the Root entity. Start the app in the Launcher and drag the script's attribute handle to generate the exception.

Edit:
Related forum thread: https://forum.playcanvas.com/t/events-js-60-uncaught-referenceerror-log-is-not-defined/15895

**Comment by mvaligursky** [comment]
agreed this seems to be a bug - log should not be used in code used 
<img width="2205" alt="Screen Shot 2020-11-20 at 2 06 13 PM" src="https://user-images.githubusercontent.com/59932779/99809862-ce0d2e80-2b3a-11eb-9881-c5f56e071f1e.png">
by launched games?

**Comment by yaustar** [comment]
Hopefully this has been fixed now. Please reopen if you still see these
