### ISSUE TITLE
Regarding handling of projects (much needed search function?) 

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#239]
Hello. This is the top project list of one of my users:
![image](https://user-images.githubusercontent.com/6838800/99905644-6558ba00-2cd2-11eb-8714-fdd35d4dd92b.png)
 - within many of them, I try hard to make telling titles for them in order to find/open certain projects in the process of revisiting them. Many of times I work on one project, for then to close it, in order to work on another. This adds up to irritation, and now I am also using a strategy where I keep six projects open (in the browser), in order to be sure I can find them again (I have around 50 projects in all, and many of them have several scene-effects below them as well).

Solution (and thereby 'feature request' for the website): Can the overview page be made with a search function that lists projects on search words/queries upon project descriptions as well? (for now there is a top limit of 32 letters in the project title, and I can only do so much within 'smart shortenings' within that naming limit :-/ )

// on before hand; thanks

**Comment by Maksims** [comment]
Tags, just like in Gmail labels - would help here a lot.

**Comment by slimbuck** [comment]
I would love to see:
- projects tags (or project folder / hierarchy like the asset browser)
- filter by: project name, tags, team members
- sort by: name, created date, last edited date, project size

**Comment by willeastcott** [comment]
The new project dashboard (accessible from the `See all project` link in the SCENES dialog) should provide the functionality you describe:

![image](https://user-images.githubusercontent.com/697563/199626514-78fbd30b-141a-4f58-99a0-15d0ddcddbb3.png)

You can search/filter as well as sort on last edited, name or creation date.

**Comment by FutureFireplace** [comment]
Thanks - much better approach ... I really need to dive more into those 'User interfaces' within the Editor umbrella of smaller interfaces (the most upper image-of-projects-interface, seems far more newbie-oriented)
