### ISSUE TITLE
Particle color / brightness differs between editor and runtime

### ISSUE THREAD

**Issue by PHou81** [playcanvas/editor#24]
Take a look at the attached screenshot. The particles appear brighter in the editor than they do in the game. This happens on all systems we've tested so far: desktop PC, Mac, and mobile phones (both Android and iOS).

![Particle_color_issue](https://user-images.githubusercontent.com/33447171/76071842-34dfbd00-5f97-11ea-8038-b471e331d986.jpg)

There's no light source in the scene and lighting is turned off in the settings on the particle system component. I've attached a screenshot with all the settings as well.

![particle_settings](https://user-images.githubusercontent.com/33447171/76071863-3c06cb00-5f97-11ea-9d19-4871d57f3734.jpg)

To get the runtime version to look right, we can increase the intensity, making the editor too bright. There should not be any difference between the two.

**Comment by ellt92** [comment]
Hi Peter, i've just tried to reproduce the issue with the settings you provided. However i'm not able to create the same effect.

Would it be possible for you to create a project with the issue so I can take a look?

**Comment by PHou81** [comment]
@ellt92 
Hi, I've not been able to reproduce the issue in a separate project. It definitely occurs in our game so I'm a little stumped as to why it's happening. I guess we could give you access to the game if you'd like to take a look, but since it's not easily reproducible, this could be a weird anomaly in our project.

**Comment by Maksims** [comment]
Try changing clear color of the camera in Editor in settings, and see if it affects the result.

**Comment by willeastcott** [comment]
The original poster was not able to repro in a new project and we have not been able to repro either. Therefore, I will close this now due to inactivity. However, if @PHou81 does manage to submit a repro, we can reopen.
