### ISSUE TITLE
Increase decimal precision on element number fields

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#241]
Users have mentioned they want more precision on the number fields in the element number fields:
![image](https://user-images.githubusercontent.com/16639049/100872218-5d9ad180-3499-11eb-8813-b02d06f01cff.png)

Changing it to 4 decimal points or more would be great.

Also thinking that the anchor and rect fields should be on two rows rather than one so that it's easier to see the vaules:
![image](https://user-images.githubusercontent.com/16639049/100872366-9cc92280-3499-11eb-8f72-d1d470153561.png)

**Comment by willeastcott** [comment]
I've submitted a PR that improves this, although I've only bumped precision to 3, not 4. This is because some number fields are quite narrow, so I think it's a good compromise.

![precision](https://user-images.githubusercontent.com/697563/199624705-1205db42-308d-4df3-8939-27a392405451.gif)
