### ISSUE TITLE
Suggestion: Make archive name of downloaded project sort-able by date

### ISSUE THREAD

**Issue by dexterdeluxe88** [playcanvas/editor#243]
Hi PlayCanvas Team,

Small feature request: Currently, if I do manual downloads of the project for backup reasons, in my Windows folder they get sorted like this:

- FancyProjectName_3_12_2020-21_55_16.zip
- FancyProjectName_5_10_2020-18_37_3.zip
- FancyProjectName_10_9_2020-10_19_41.zip
- FancyProjectName_11_11_2020-11_6_41.zip
...

It would make more sense (at least for me), if you would use some format like PROJECTNAME_YYYY_MM_DD-HH-mm-SS, so the projects get sorted by date, and not by day.

**Comment by vkalpias** [comment]
Thanks that's done now.
