### ISSUE TITLE
Reimporting model doesn't respect Convert to GLB toggle

### ISSUE THREAD

**Issue by Crefossus** [playcanvas/editor#244]
### Description

If you uncheck convert to glb in asset tasks and then reimport an obj/fbx with the rightclick menu, it still produces a GLB. 

I expected it to follow the project settings and was confused for a bit with an obj and thought json might only be generated by another type like fbx. Deleting the asset and then re-uploading works fine.

I was experimenting with lightmaps and because of https://github.com/playcanvas/editor/issues/194 you have to turn off GLB (or make uv1 outside of playcanvas). 

Win/Chrome Version 87.0.4280.88

### Steps to Reproduce

1.  Upload an obj or fbx
2.  Uncheck convert to glb in asset tasks
3.  optional - Delete the glb
4.  Rightclick on obj or fbx and chose reimport

**Comment by willeastcott** [comment]
A fix has been submitted by @slimbuck - it will be deployed next week. 🚀
