### ISSUE TITLE
Some constants are available in the global scope in launch tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#245]
Launch any project.
Open the launch tab
Open up Devtools
In the console, try typing `LAYERID_`
Note they the layer ids constants are accessible without the `pc` scope

In a published build, these are not accessible.

![image](https://user-images.githubusercontent.com/16639049/101356496-0f6a4180-3890-11eb-9062-77b1093f4e1f.png)

**Comment by vkalpias** [comment]
These (and others) are Editor-only constants, they're not meant to be accessible at runtime.

**Comment by yaustar** [comment]
Sorry, I wasn't clear, the issue is accessible at runtime in the launch tab :

![image](https://user-images.githubusercontent.com/16639049/101368798-7a6f4480-389f-11eb-89ad-019e78f2c045.png)

**Comment by Maksims** [comment]
They are not documented public APIs, so I guess it is fine situation. Launcher has many internal things, to make collaborative live stuff, and profiler, and few others.

**Comment by willeastcott** [comment]
Just to explain...this hasn't been fixed by magic. 😄  @kpal81xd and I have been gradually migrating the Editor codebase to ES Modules so, bit by bit, certain global vars have moved into module scope and can no longer be accessed on the `window`.
