### ISSUE TITLE
Deleting script asset on a large project has a second or two freezes the browser

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#247]
Fork the WebVR Lab project: https://playcanvas.com/project/446331/overview/webvr-lab
Delete any script file
Notice that there's a delay before user can interact with the Editor

Video attached
[Kapture 2020-12-07 at 18.02.11.mp4.zip](https://github.com/playcanvas/editor/files/5654386/Kapture.2020-12-07.at.18.02.11.mp4.zip)

**Comment by Maksims** [comment]
Noticed it in WebVR Lab project.

**Comment by vkalpias** [comment]
This should now be fixed.
