### ISSUE TITLE
Add "Download" button to context menu of GLB files

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#248]
### Description

Currently, if you upload an FBX file, you can then download that file by right-clicking on it and hitting "Download". However, if you upload a GLB file directly (as a binary type) or have PlayCanvas convert the FBX to GLB (to a model type), you have to go into the side panel to download the GLB. Right-clicking the asset doesn't present a download button.

For convenience, it would be nice if this was added to the context menu. In addition, I at first thought you couldn't download GLB's until I noticed there was a download button in the side panel.

### Screenshots

FBX asset - Has download button
![image](https://user-images.githubusercontent.com/6013871/101404421-9d502780-38a4-11eb-8066-3335159ccdf3.png)
GLB asset that was converted from FBX (by PlayCanvas) - Does not have download button
![image](https://user-images.githubusercontent.com/6013871/101404461-ab05ad00-38a4-11eb-9277-2f6c82c84dd9.png)
GLB asset uploaded directly (converted to GLB offline) - Does not have download button
![image](https://user-images.githubusercontent.com/6013871/101404846-34b57a80-38a5-11eb-841c-679080d224f9.png)

**Comment by willeastcott** [comment]
I have submitted a PR to address this. 🎉
