### ISSUE TITLE
Broken fbx import when converting to json

### ISSUE THREAD

**Issue by Ajk48n** [playcanvas/editor#25]
Hi,

I believe there is a bug with the fbx importer in playcanvas that causes the converted json file to lose keyframe data that existed in the original fbx.

I’m importing a very simple animation of a box into playcanvas using fbx. When the animation is converted to json, it loses keyframe data that was originally there.

You can see in this test project. If you download the fbx file, there is animation where the ball moves up on the Y-axis on the 2nd frame. But in the json file, that motion is not there at all.

The fbx was exported from Maya, and I’ve tried multiple versions of the fbx plugin.

https://playcanvas.com/project/669752/overview/fbx-import-error

**Comment by slimbuck** [comment]
Hi @Ajk48n,

The playcanvas tools currently only convert the last animation take found in the FBX file. Could this be the issue?

Thanks!

**Comment by Ajk48n** [comment]
Hi @slimbuck 

Thanks for the suggestion, butu nfortunately that isn't the issue. This has happened on a new scene with just a box animated with a few keyframes.

And looking at the data in the json file that Playcanvas makes, the fbx to json conversion is only converting correctly every 6 frames. On all other frames, the json simply gets a linear interpolation between those newly made frames

**Comment by slimbuck** [comment]
Hi @Ajk48n,

Sorry I just read your issue a little more closely. The converter samples FBX animations at regular intervals, by default every 0.1 seconds. If your keyframes are spaced closer than this apart, they can be missed.

**Comment by Ajk48n** [comment]
Hi @slimbuck 

Thanks for the update.

Is there anyway to override that behavior, and have the converter sample every frame?

As it is now, it more difficult to work with fbx files. I've been getting around it by slowing my animations down 6x, but this obviously adds a lot more size to my assets.

Also, is 0.1 seconds sampled at 60fps?

**Comment by slimbuck** [comment]
Hi @Ajk48n ,

Sampling every 0.1 seconds means sampling 10 times a second. Unfortunately there is currently no way to set this rate in the editor.

Please add an issue to https://github.com/playcanvas/editor if you'd like the sampling rate exposed!

**Comment by Ajk48n** [comment]
Hi @slimbuck 

Isn't this thread an issue on github? Or is there something special I need to do in order to mark it as such?

Also, is there a reason that the conversion is handled this way opposed to just sampling every single frame?

**Comment by slimbuck** [comment]
Sorry @Ajk48n I missed your last message!

The issue is on github and we look into this soon as we can.

The reason animations are sampled at regular intervals is because it's simplest approach: sampling the animation will always work correctly (apart from the sampling rate issues that we're discussing here).

Ideally we would export the curves a they exist in the FBX file instead . However this is not straightforward, but something we will definitely look into.

**Comment by willeastcott** [comment]
Implemented and deployed:

![image](https://user-images.githubusercontent.com/697563/97623575-bf40c980-1a1d-11eb-8a3b-4a19dfbd01f7.png)
