### ISSUE TITLE
Show a warning if texture is not POT and mipmap is enabled (WebGL 1)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#251]
WebGL 1 doesn't support mipmaps on textures that are not POT. We should show a warning in the inspector to make it clear to the user that this could be a concern:

Eg

"Only WebGL2 supports mipmap generation on non power of two textures in width and height. (E.g. 256 x 256, 512 x 1024). See https://caniuse.com/webgl2 to see current browser support. Expect browsers that only support WebGL1 to render differently." 

![image](https://user-images.githubusercontent.com/16639049/101894110-94f63600-3b9d-11eb-9095-cb9cd4a8212d.png)

**Comment by yaustar** [comment]
Warning should also describe symptoms of what would happen if they aren't POT.  

Related forum post: https://forum.playcanvas.com/t/solved-particle-system-textures-appear-pixelated/18787/4

**Comment by Maksims** [comment]
That is why defaults in assets settings to use PoT - is still important today. And should be disabled only by a developer/artist who is aware of consequences.

**Comment by yaustar** [comment]
Released with https://github.com/playcanvas/editor/releases/tag/v1.18.21
