### ISSUE TITLE
Prefiltering RGBM-only cubemaps fails

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/editor#26]
If you upload 6 PNG RGBM textures into the editor and create a cubemap from it, attempting to generate prefiltered lighting data fails.

**Comment by willeastcott** [comment]
I believe the current behavior is:

When uploading 6 HDR/EXR images, 6 DDS files are created with the floating point data in the source images. When prefiltering in the front end, this DDS data is downloaded, and the generated prefiltered cubemap DDS is uploaded to the server.

If you upload RGBM PNGs, the DDS files are not generated.

I guess options are:

1. Prefilter on the back end (and no longer generate the intermediate DDS files).
2. Detect when download of the DDS files fail and just go ahead and use the RGBM files as input for the prefilter operation.

@guycalledfrank might have some thoughts on whether using RGBM data as input for `pc.prefilterCubemap` will result in a poor quality result or not.

**Comment by guycalledfrank** [comment]
It depends on the range. RGBM can clamp them a bit, so final result may look a bit darker. Other than that, it should work but probably wasn't tested with RGBM inputs in years.

**Comment by slimbuck** [comment]
Done
