### ISSUE TITLE
Allow scene hierarchy search to search by component name and also script name

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#262]
Currently scene hierarchy search box searches by entity name only.

It'd be convenient to search additionally by:
- component name: for example "model" would find all entities that have model component
- script name: for example "test" would find all entities that use script with name test.

Note that in this case, perhaps only exact match should find them, partial matches would not find components / scripts.

**Comment by yaustar** [comment]
Bump request by client

**Comment by willeastcott** [comment]
This is now implemented:

![image](https://user-images.githubusercontent.com/697563/199622707-966f47f9-9254-4add-a39c-5716cbcc0223.png)
