### ISSUE TITLE
Expose Area Lights in editor

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/editor#269]
Expose in editor area lights - which was implemented in https://github.com/playcanvas/engine/pull/2535
This may also involve:
- finalize the mechanism via which the LUTs are imported/included in a project
- finalization of API
- UI and widgets
- UX iteration
- documentation
- closed beta testing period
- bug fixing runtime implementation

**Comment by willeastcott** [comment]
Also need to finalize the mechanism via which the LUTs are imported/included in a project.

**Comment by yaustar** [comment]
Now in the Editor
