### ISSUE TITLE
Bug with highlighting selected mesh

### ISSUE THREAD

**Issue by qWici** [playcanvas/editor#27]
### Description
Early when I click on model - target mesh is highligthing in "Mesh instances" list (orange border). Now it does not work. Its okey?

*Video*: [on vimeo](https://vimeo.com/397039989)
*Browsers:* testing on Chrome 80.0 and Safari 13.0.3

**Comment by willeastcott** [comment]
Confirmed. We'll investigate. Thanks for reporting.

**Comment by ellt92** [comment]
A fix for this is now out, so i'll close this issue.
