### ISSUE TITLE
Disable messenger logs

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#272]
I would like to propose disabling the messenger logs by default, as it keeps clogging the console with redundant messages. As a consumer those messages carry no value for me:

![image](https://user-images.githubusercontent.com/5677782/103773482-c7c40a80-5033-11eb-9caf-2602076a4c51.png)

**Comment by Maksims** [comment]
I've had often state of Editor, where after reconnect it would require a page refresh, as some things didn't re-attach properly on events or something.
So used console log to identify there was a reconnect.

It is definitely worth investigating why messenger is reconnecting, as it suppose to hold connection for as long as possible.

**Comment by LeXXik** [comment]
Hmm, interesting. I thought it was an intentional change, as I do remember the messenger kept the connection alive for extended periods previously so these logs were not an issue as they were sparse. This has changed recently and messenger keeps reconnecting often, even if I don't switch tabs.

**Comment by willeastcott** [comment]
Yeah, I've noticed that too as it happens. I assumed it was because my internet had become more unstable recently, but it seems not. Any thoughts, @vkalpias?

**Comment by vkalpias** [comment]
Not sure needs investigation

**Comment by willeastcott** [comment]
I must say - I haven't noticed many of these messages lately so I'm going to close this. But please reopen if you feel it's still a problem.
