### ISSUE TITLE
Render Component on created primitive does not have Material property in inspector

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#279]
Editor needs to be in "Create Container Assets" import setting.

Right click on Scene Root, select New Entity -> Primitive -> Box
In inspector, it says "Materials 0" and it does not have slot to add material to.

![Screen Shot 2021-01-14 at 12 09 50 PM](https://user-images.githubusercontent.com/59932779/104589201-6c140580-5661-11eb-951f-3bfa175d7896.png)

If I change Type to Asset and back to Box, it fixes itself

![Screen Shot 2021-01-14 at 12 11 12 PM](https://user-images.githubusercontent.com/59932779/104589336-9cf43a80-5661-11eb-8f57-72eb815a67c6.png)

**Comment by vkalpias** [comment]
fixed
