### ISSUE TITLE
Allow user to select GPU preference in project settings

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#28]
In the [WebGL specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1), a `powerPreference` value can be passed when creating the WebGL context. Browsers (in particular, Safari and Chrome) have changed (or are changing) the `default` behavior to be `low-power` instead of `high-performance`.

We should expose a new property in the Project Settings panel: `Power Preference`. Tooltip could reuse the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) for the property.

Open question: should the default value be `default` or `high-performance`? (I don't believe the default should be `low-power`). I'm tempted to suggest `high-performance` because this will result in fewer support contacts asking why app performance is lower than expected on certain platforms. Support contacts about battery consumption are likely to be less common, in my view. And in such a case, a developer just has to select a different option and republish.

Note that this should requite minimal or even no changes to the engine itself. It's an Editor task.

**Comment by vkalpias** [comment]
Shouldn't that depend on the device?

**Comment by mvaligursky** [comment]
perhaps this could depend on weather device is plugin in or running on battery

**Comment by willeastcott** [comment]
@vkalpias I'm not so sure. From the MDN docs:

> low-power
> 
> Indicates a request for a GPU configuration that prioritizes power saving over rendering performance. Generally, content should use this if it is unlikely to be constrained by drawing performance; for example, if it renders only one frame per second, draws only relatively simple geometry with simple shaders, or uses a small HTML canvas element. Developers are encouraged to use this value if their content allows, since it may significantly improve battery life on mobile devices.

**Comment by willeastcott** [comment]
@mvaligursky We can't detect whether a device is plugged in from the browser.

**Comment by halvves** [comment]
@willeastcott @mvaligursky - The only way to detect batter/power status is unfortunately now [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API) 😔

**Comment by willeastcott** [comment]
@halvves The Battery Status API is unrelated. Check out the WebGL spec I linked in the initial post for info about the `powerPreference` setting on a WebGL context.

**Comment by willeastcott** [comment]
@halvves Yeah, we can't rely on that.

**Comment by willeastcott** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/697563/97580776-a91a1580-19eb-11eb-98ef-9168ee5e1234.png)
