### ISSUE TITLE
[BUG] Exported Build always using Project Name instead of Project Title?

### ISSUE THREAD

**Issue by ketan-ata** [playcanvas/editor#281]
https://forum.playcanvas.com/t/why-project-name-in-exported-build/16876

Exported project always using Project Name instead of Project Title...
======

My project name is **XYZ 999**.
![pName](https://user-images.githubusercontent.com/54302810/104748163-66a8df00-5777-11eb-8ac4-ce8df950cdea.png)

But during export i renamed it to **XYZ YES**
![eName](https://user-images.githubusercontent.com/54302810/104748197-732d3780-5777-11eb-8281-53ebc6db9132.png)

And after this…
i got this 
![zip](https://user-images.githubusercontent.com/54302810/104748230-7aecdc00-5777-11eb-85e5-eb7b227c8080.png)
 File

But when i put this on server…

I see always
![tab](https://user-images.githubusercontent.com/54302810/104748261-83451700-5777-11eb-935e-05777278e61c.png)
 in Chrome tab…

Where i have to edit this index.html file manually each and every-time…

It is Pain in Head… :sweat_smile:

Can you please fix this?

**Comment by LeXXik** [comment]
+1 this is quite a hassle for multi-project projects at the moment.

**Comment by yak32** [comment]
the fix is ready, will be merged soon

**Comment by yaustar** [comment]
Fixed in release of v1.21.61 that we are aiming to release on Monday/Tuesday
