### ISSUE TITLE
A scene with a Basis compressed texture without the Basis WASM module fails to run

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#283]
All you get is this in the JS console:

![image](https://user-images.githubusercontent.com/697563/105390980-8b86d180-5c11-11eb-9757-eff0bda0c99c.png)

I would argue the scene should still load and run - but maybe just the texture doesn't load. Right now, it's not obvious why things break.

**Comment by Maksims** [comment]
I would argue that even texture should load, just basis variant should be ignored.
If other better variants are available (legacy), then they should be prioritised.

**Comment by yaustar** [comment]
This has been resolved via an engine fix
