### ISSUE TITLE
Show wireframe in viewport.

### ISSUE THREAD

**Issue by SashaRX** [playcanvas/editor#285]
This is a very important basic tool that the editor is missing.

**Comment by leonidaspir** [comment]
Indeed this can be quite useful, even if it works only for the selected entity/model.

**Comment by coldfireagc** [comment]
I know it's been a little bit, but I would also love to have a wireframe view mode for the editor window.

**Comment by defektu** [comment]
Temporary tampermonkey script if anyone needs: https://github.com/defektu/Playcanvas-Editor-Scripts/blob/main/EditorWireframe.js
