### ISSUE TITLE
When copying and pasting a folder 2 levels deep from the root, it is pasted as a flat hierarchy 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#292]
Steps to reproduce:
1. Copy a folder that is at least 2 levels deep in the hierarchy 
2. Paste into a new project
3. Folder is copied but is empty. Files that were in the folder are copied as a flat hierarchy 

https://user-images.githubusercontent.com/16639049/106772275-bfadb980-6637-11eb-9a82-14f120ee44f0.mp4

**Comment by vkalpias** [comment]
This should now be fixed
