### ISSUE TITLE
Failed processing Asset does not show error message in Inspector.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#293]
### Description

Uploading file that failed processing during pipeline, adds a message into asset data, but it is not shown in Inspector, so there is no way to find out what went wrong, except red circle around thumbnail in assets panel.

### Steps to Reproduce

1. Upload this asset (EXR texture, please unpack before as github not allowing to upload EXR files): [grace_negx.zip](https://github.com/playcanvas/editor/files/5934163/grace_negx.zip)
2. Notice it fails processing in assets panel
3. Inspector has no information of the error message, while `taskInfo` on the asset is set: `error while processing metadata`

**Comment by willeastcott** [comment]
Confirmed. Either @yak32 or @slimbuck. We _used_ to support EXR import and I don't see anything special about that image that would prevent it from importing correctly.

**Comment by yak32** [comment]
the version of imagemagick we use in containers doesn't support EXR by default. I am looking for a fix

**Comment by willeastcott** [comment]
This is now fixed.
