### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by azerturk** [playcanvas/editor#294]
Camera not working correctly.  Entity positions are increasing to a random numbers. Everything worked correctly but then suddenly this problem occured. Problem is occured in only one project. I test others working correctly. Numbers are like this "1.615934984461356e+25"
project id is 659469

**Comment by yaustar** [comment]
The project is private so we can't access it. Can you fork it, remove the private bits so you it's just the camera and post a video of the steps to reproduce please?

It's strange that it's only in one project.

**Comment by azerturk** [comment]
I rremove the private option. Please select camera and just move it with mouse then you will see the problem.

**Comment by willeastcott** [comment]
This is because you have set the scale of the parent entity of the camera to 0 for X and Y:

![image](https://user-images.githubusercontent.com/697563/107128141-2e4a7b80-68b3-11eb-945b-d4eee754ccd1.png)

Change those to values back to 1.
