### ISSUE TITLE
Override Ctrl/Cmd + W to close the current code file tab in Code Editor and not the browser tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#296]
There's concern that the overriding this behaviour is not desirable as it's base browser function. We could put this in as a user preference in the code editor?

**Comment by Maksims** [comment]
I don't think we should override native hotkeys, that people are used to, with non-common behaviours.

Here is an example: you want to close tab, and used to using Ctrl + W, you hit it, and it doesn't work, as it closes some of the tab. What next? Hit Ctrl+W many-many times? Or use mouse to close that browser tab?

It is usually not good to alianate common UX practices and behaviours with a custom ones.

**Comment by willeastcott** [comment]
I agree with @Maksims. I don't think it's good practice to override browser native hotkeys. Closing.
