### ISSUE TITLE
Can't remove folders in asset panel

### ISSUE THREAD

**Issue by highvrahos** [playcanvas/editor#3]
This has happened to a forum user, and I was able to reproduce at that same instance. After a couple of minutes the issue was resolved and the folder was deleted.

### Steps to Reproduce

1. Create a new folder on any Playcanvas project
2. Right click on it and select delete
3. Pressing delete on the new modal didn't remove the folder.

![image](https://user-images.githubusercontent.com/29543178/73753219-9fb49300-4762-11ea-9363-66997160ea51.png)

Forum thread: https://forum.playcanvas.com/t/editor-down-cant-connect/11968

**Comment by AlbertoMalavasi** [comment]
Not only folders, but any file contained in any folder..

https://forum-files-playcanvas-com.s3.dualstack.eu-west-1.amazonaws.com/original/2X/1/18833df9bdf0d4100d3dff792a5829e62e7e2194.mp4

**Comment by willeastcott** [comment]
Fixed. Apologies for the inconvenience. The pipeline server needed a restart.

**Comment by WangNianyi2001** [comment]
> Fixed. Apologies for the inconvenience. A server needed a restart.

It now happens again :-(

**Comment by yaustar** [comment]
@WangNianyi2001 I've just tried now and it seems fine. Can you try refresh your page/browser if you haven't tried already.

If that doesn't work, is it one particular folder that cannot be deleted? Or any folder?

**Comment by WangNianyi2001** [comment]
@yaustar sry I made a silly mistake--I clicked on the orange cancel button instead of the gray delete button (facepalm)

**Comment by Maksims** [comment]
The orange button is definitely misleading.

**Comment by willeastcott** [comment]
cc @rawkas

**Comment by vkalpias** [comment]
I think the logic behind this design is that because it's a delete which you can't undo, it highlights the Cancel button because if you are going to click on a button accidentally it'd better be the Cancel instead of the Delete.

**Comment by vkalpias** [comment]
> The orange button is definitely misleading.
> Especially when using Delete > Enter keyboard combination, it does not work.

That is by design as we had people accidentally deleting the whole thing. So we made Delete a little more difficult to require conscious effort.

**Comment by willeastcott** [comment]
I think if we had a 'trash' that would allow you to undo an asset delete, it would solve this problem.

**Comment by Maksims** [comment]
> > The orange button is definitely misleading.
> > Especially when using Delete > Enter keyboard combination, it does not work.
> 
> That is by design as we had people accidentally deleting the wrong thing. So we made Delete a little more difficult to require conscious effort.

By clicking "wrong" button, it's ok, then probably should be highlighted equal, or at least the delete button to be actually red, so the user sees it is an important button.

But please, bring back "enter" hotkey, as hitting Enter after Delete button - is definitely a conscious action.



> I think if we had a 'trash' that would allow you to undo an asset delete, it would solve this problem.

That definitely would help. But it sounds complex:
1. Trashed assets should not be accessible by runtime (not added to `app.assets`).
2. Trashed assets should not be exported to the build.
3. Trashed assets should not be referencable by asset pickers.
4. Trashed assets should be respected by "unused" Editor system.
5. Moving to the trash and restoring from trash, for runtime should act as "delete/create" assets.
6. What about selecting trashed assets in Inspector, should it still be ok to edit them, etc?

**Comment by yaustar** [comment]
> By clicking "wrong" button, it's ok, then probably should be highlighted equal, or at least the delete button to be actually red, so the user sees it is an important button.

![image](https://user-images.githubusercontent.com/16639049/116550291-7e534000-a8ee-11eb-8406-cb0ae65f6a00.png)

It's a tough as both options make sense. 

> But please, bring back "enter" hotkey, as hitting Enter after Delete button - is definitely a conscious action.

IIRC, the typical pattern is to have 'cancel' as the preselected option, and the user can press tab to select the next option.

**Comment by Maksims** [comment]
I wouldn't say "typical" based on a single platform.

![image](https://user-images.githubusercontent.com/636263/116552760-0b53c480-a902-11eb-9853-9f0b06021564.png)

**Comment by yaustar** [comment]
Hm, I actually thought Windows defaulted to no. Bear in mind I'm thinking of other programs etc that I've used which annoyingly I now can't find an example of 😅 

Unity just deletes files without a warning which is surprising. 

Just tried Google Drive and it matches what Max is saying about the delete action being preselected for enter
![image](https://user-images.githubusercontent.com/16639049/116553748-5fef4380-a8f2-11eb-8956-b346b4fefb78.png)

**Comment by WangNianyi2001** [comment]
Maybe there would be a prefferable mixed solution: *highlight* the "delete" button while setting the default keyboard focus to "cancel". This avoids visual confusion & grant keyboard users access to actually performing the deletion.

BTW I think maybe we should create a new issue or forum post, since this one is already closed.
