### ISSUE TITLE
New anim state graph screen breaks whole animation component

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#300]
<img width="1393" alt="Screen Shot 2021-02-17 at 01 40 38" src="https://user-images.githubusercontent.com/7432641/108130837-58751800-70c1-11eb-9dd0-b94ffb8a626c.png">

I just opened that screen and changed one state's speed, and now it doesn't work at all. The character stays in T-pose mode in-game, it doesn't play any animation.

**Comment by yaustar** [comment]
The graph view shouldn't have changed any existing data beyond adding an ANY state if one didn't exist. Is this a project you are able to share for someone to take a look at?

**Comment by yaustar** [comment]
To help debug this, could you try creating a new Idle state and deleting the existing one? I'm wondering some data got corrupted?

**Comment by devcem** [comment]
@yaustar here is a video to show it :

I also tell what's wrong with it in video, so unmute video when you click the link.
https://streamable.com/x8q0ga

I also tried to reproduce it in an empty project but no luck. It works with empty animation state, I believe there is something wrong with my old animation state format or something.
If your username is yaustar, I can share the private project with you? So you can take a look.

Also here is a published demo to see, maybe that can also be helpful :
https://playcanv.as/b/Z0w3qHRj/

**Comment by yaustar** [comment]
@devcem Yes, `yaustar` is my username :) Can I fork privately and poke around with it please?

**Comment by devcem** [comment]
> @devcem Yes, `yaustar` is my username :) Can I fork privately and poke around with it please?

Yes, sir, I gave an admin access to your account.

**Comment by yaustar** [comment]
Thanks! We've a made a fork of the project and it looks like animation controller in the engine never leaves the START state.

We got around it by adding a new IDLE state and removed the existing one. @ellthompson is looking into the issue now to see what is really going on in the engine.

On a separate note, the project looks really nice!  

We are looking to get more feedback about the Anim Component and Graph Editor while it is in beta, would you be open to have a video chat with us?

**Comment by devcem** [comment]
> Thanks! We've a made a fork of the project and it looks like animation controller in the engine never leaves the START state.
> 
> We got around it by adding a new IDLE state and removed the existing one. @ellthompson is looking into the issue now to see what is really going on in the engine.
> 
> On a separate note, the project looks really nice!
> 
> We are looking to get more feedback about the Anim Component and Graph Editor while it is in beta, would you be open to have a video chat with us?

Yes, I'm open to that. You can reach me with this email: commention@gmail.com

**Comment by devcem** [comment]
@yaustar in order to continue my project, I need to revert it back to its previous working state. Can you tell me how exactly you deleted removed the existing one? For some reason, on my editor it doesn't show "remove" option on current idle state.

It only shows add transition option.

<img width="405" alt="Screen Shot 2021-02-17 at 20 40 09" src="https://user-images.githubusercontent.com/7432641/108244584-6463e700-7160-11eb-9039-078d4603e3ba.png">

**Comment by yaustar** [comment]
We believe this is fixed now. Please do let us know if it still happens
