### ISSUE TITLE
Be able to sort the scenes in alphabetical order

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#304]
If would be great if users could further sort and/or search their scenes 

Once users have a lot of scenes, it becomes harder to find a particular scene as they are ordered in update order.

![image](https://user-images.githubusercontent.com/16639049/108496266-bb250a00-72a1-11eb-937d-577ea894b55e.png)

**Comment by Maksims** [comment]
Small filter box would be really useful too!
I've worked on a project with dozens of scenes. They are sorted by last modification time, which makes list constantly changing (not cool). Default to alphabetical - would be more stable way to remember the order and search for right scene.

**Comment by yaustar** [comment]
Now deployed as alphabetical order only
