### ISSUE TITLE
Network Error ERR_CONTENT_LENGTH_MISMATCH in launch page

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#305]
I am frequently encountering a Network Error in the launch page:

![image](https://user-images.githubusercontent.com/697563/108608998-ad1ada80-73c2-11eb-8ffe-62d830b9ba24.png)

Today, I'm hitting it on maybe 50% of launches.

It's the `ERR_CONTENT_LENGTH_MISMATCH` error we have seen many times before. I was sure I'd opened an issue about this previously, but since I can't find it and this is quite a frustrating bug, I'm logging it anyway.

**Comment by yak32** [comment]
we upgraded our asset delivery system to use CDN and the is not happening anymore.
