### ISSUE TITLE
Be able to search/filter branches in the version control view

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#306]
If a user has many branches (especially in closed branches view), it can take a while to load all the pages to find a particular branch. Being able to perform a search would really help.

**Comment by nuggien** [comment]
+1

**Comment by ki11roy** [comment]
Any updates on this? BTW https://github.com/playcanvas/editor/issues/628 seems duplicate.

**Comment by yaustar** [comment]
Re-bumping

**Comment by yaustar** [comment]
Features we would like to have: 

- Be able to show branches that contain the string (case insensitive) in the search field
- (Bonus) Be able to search as the user types the string in the search field

**Comment by jiajasper** [comment]
Please see first draft of the design

![image](https://user-images.githubusercontent.com/30747200/163382586-33b33d88-e94f-4546-90c5-f3c1d15c7118.png)


And the search UX is exactly what @yaustar mentioned previously:
- Be able to show branches that contain the string (case insensitive) in the search field
- Be able to search as the user types the string in the search field

**Comment by yaustar** [comment]
We have a few options here:

- The simplest, change this from loading branches as 'pages' and just have a single call to get all branches. This makes the search bar relatively straightforward as it just filters the list below
- Create new API that does a simple query against the DB and matches on string
- Create new API and UX that searches as you type

Ideally, I would prefer the first option being really simple but conscious that having a large number of branches may cause the dialog to be 'slower' to open while parsing the branches? We should test against 50 open branches to see how it fares.

**Comment by jiajasper** [comment]
@yaustar I agree, the first one seems the best approach. @zachpeterpaul what do you think?

**Comment by Maksims** [comment]
> We have a few options here:
> 
> * The simplest, change this from loading branches as 'pages' and just have a single call to get all branches. This makes the search bar relatively straightforward as it just filters the list below
> * Create new API that does a simple query against the DB and matches on string
> * Create new API and UX that searches as you type
> 
> Ideally, I would prefer the first option being really simple but conscious that having a large number of branches may cause the dialog to be 'slower' to open while parsing the branches? We should test against 50 open branches to see how it fares.

There is no need to load full branch data when listing them. So only title, type and id is required. This is same as for assets, which even with thousands of them, works really fast.
So when opening version control, open list of all open branches, with only simple data. MongoDB can selectively only include necessary fields, so query will be fast. And then search can be instant through that list. If in type filter "closed" option is selected, then load closed branches, as a separate secondary index.
Full branch data (checkpoints) should be loaded when a specific branch is selected.

**Comment by jiajasper** [comment]
Please see visual designs for identifying different states of the branch and as well as a line of text where we indicate the user has reached the end of the list. 

![image](https://user-images.githubusercontent.com/30747200/164287172-f8b17dc6-fc19-4ab8-ae98-b659280f8402.png)

https://www.figma.com/file/kMiAhzD5xlSobeBuU6lxRy/Jasper-PlayCanvas-Hub?node-id=611%3A33578

**Comment by Maksims** [comment]
Icons are font-based.
For a closed branch, more dim text `closed` before the branch name, I believe would make it more apparent.
Also, as mentioned before, the default filter doesn't need to show closed branches. This is beneficial for performance reasons, especially with branch=feature workflow in long term. And based on people's workflows, there is different motivation to search for open or closed branches, and they are very distinct.

**Comment by yaustar** [comment]
> Also, as mentioned before, the default filter doesn't need to show closed branches.

That preview above is for the 'All' filter :) We be keeping the filters as they are as well as adding 'All' much for the same motivations as you said above

**Comment by yaustar** [comment]
Released in https://github.com/playcanvas/editor/releases/tag/v1.21.42
