### ISSUE TITLE
After recent update editor transform tools has problems

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#307]
After the recent update transform tools like translate, rotate and scale has some sort of layering issue.

As you can see in screens, they are under the model. They used to be on top of all layers.

From top :
<img width="538" alt="Screen Shot 2021-02-22 at 17 48 57" src="https://user-images.githubusercontent.com/7432641/108724468-68b04b80-7536-11eb-9966-2b820735de5a.png">

From bottom :
<img width="428" alt="Screen Shot 2021-02-22 at 17 49 05" src="https://user-images.githubusercontent.com/7432641/108724505-7239b380-7536-11eb-811e-c3fbc1a58d79.png">

**Comment by willeastcott** [comment]
Sorry about this. We're on it...

**Comment by Maksims** [comment]
I've noticed some random sorting issue with non transparent objects as well, where animated robot had parts appearing in wrong rendering order, like depth test was not on.

**Comment by willeastcott** [comment]
@Maksims Can you give us a specific repro please?

**Comment by willeastcott** [comment]
This was fixed by: https://github.com/playcanvas/engine/pull/2899

Sorry for any inconvenience!
