### ISSUE TITLE
Better progression status for Unwrapping within the 'Pipeline' for imported 'Models'

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#309]
(moved as requested: cf https://github.com/playcanvas/engine/issues/2870)

For now there are a couple of effects within Unwrapping of the UV1 map of models, that are less service minded. As a user I often question if this - solely server process - is crashed or not?

![image](https://user-images.githubusercontent.com/6838800/107938715-0d0a1f00-6f86-11eb-8515-f8161c28601f.png)

Often the problem rise with a human character model above 20 MB (having a large degree of detail), and it is therefore not a surprise that the unwrapping of such takes longer - but how much longer exactly should one expect?
I therefore bring forth two suggestions:

The first one is maybe a bit far reaching, as this would contain a 'local machine' solution. Instead of unwrapping serverside, would it then be possible to download and install a little 'Unwrapping sw', that can produce an unwrapping file, for then to upload to the editor? (this way it might be easier to recognize if process have crashed on local machine or not)
There is already a progression bar for the unwrapping process, but can this be expanded to include some sort of console data output? (maybe as in the launch 'Profiler') This way the user is more secure of what is going on serverside.

**Comment by mvaligursky** [comment]
Do you have problem with the process crashing, or is it just taking a long time and then finishes properly? If there is an issue with crashing / not finishing, we'd like to have a look at a case like that.

Implementing local solution with uploading some extra file is very complicated, considering the model file contains multiple meshes on different level of hierarchies. The far simpler solution would be to unwrap using something like Blender and have the data as part of the original mesh.

I'm also curious as to why do you unwrap a human character .. I assume it's not skinned and you need lightmaps on it?

**Comment by FutureFireplace** [comment]
Many of times the character will fit my/random environments fine by the initial UV0-mapping. There are, however, quite a lot of situations where I need to use the UV1-mapping, in order to handle/change textures by code in realtime. Here unwrapping is needed in order to get the correct result - regardless of what ever 'magic' I pull off in Blender before hand.

I some cases I can comprise, by splitting up the character into smaller FBX and/or GLB-parts. But this is far from optimal.

PS: there seem to be a browser-local limit to the file-size. Plus 10 mb files appears to be a banale size? (can memory be freed at browserlevel)

**Comment by slimbuck** [comment]
Hi @FutureFireplace,

Can you provide us with a model that fails to unwrap (or takes very long)? Otherwise it's quite difficult for us to investigate the issue.

> regardless of what ever 'magic' I pull off in Blender before hand
I would just like to point out that you should get very similar results using Blender's unwrapper compared to the PlayCanvas unwrapper. If you are seeing substantial differences then if you can provide us a repo that would be great.

> there seem to be a browser-local limit to the file-size
Can you explain a little more, where do you see this limit, when unwrapping uvs?

Thanks

**Comment by FutureFireplace** [comment]
Hmmm ... while trying to find a large plus-10mb character, it seems they all (right now at least) comes with 'UV1 available' from start at 'Pipeline' [maybe a repo/update have done some stuff already in this direction?]. 

I am thus, more interested in the "PS: there seem to be a browser-local limit to the file-size. Plus 10 mb files appears to be a banale size? (can memory be freed at browserlevel)"-question.

Otherwise I am a developer, that really wish for new 'feature request' approach. As I am trying to roll out a grand scheme of smaller PWAs/web apps, some feature requests are more important than others.
As such a voting-system for the developers would be great :-)

I am, for instance, more dependent on this feature request (for now only as a forum-thread):
https://forum.playcanvas.com/t/solved-audio-mutes-when-out-of-tab-focus-different-with-youtube/19346
- being realized, than this one {my requests have a hierarchy of priorities}

**Comment by yaustar** [comment]
> I am thus, more interested in the "PS: there seem to be a browser-local limit to the file-size. Plus 10 mb files appears to be a banale size? (can memory be freed at browserlevel)"-question.

I'm not aware of a browser limit on file sizes. I'm pretty sure that I've loaded files larger than 10MB.

If you have a reproducible of the issue that can be shared, please do so and in a separate GitHub issue.

**Comment by FutureFireplace** [comment]
ok, thanks - closing issue 

(for external/new readers: https://forum.playcanvas.com/t/solved-audio-mutes-when-out-of-tab-focus-different-with-youtube/19346 is treated/further-handled by yauStar at forumlevel)
