### ISSUE TITLE
Error While Saving Changes - Please Refresh The Editor

### ISSUE THREAD

**Issue by renegadels** [playcanvas/editor#311]
Hi, 
I've been experiencing an issue when I try to copy paste entities between scenes in a project, where a dialog comes up on the editor like so-

![image](https://user-images.githubusercontent.com/58387535/109481908-60f72680-7aa3-11eb-9caa-7b59f43b52c8.png)

This persists despite refreshing the page and/or restarting the browser. I've experienced this on Windows 10(Chrome), macOS Big Sur(Brave), and elementaryOS(Brave).

Please find the relevant forum link here - https://forum.playcanvas.com/t/possible-bug-while-copy-pasting-entities/18349

Thanks and Regards.

**Comment by yaustar** [comment]
What errors do you get on the console?

What type of assets are you trying to copy? 

I've been unable to reproduce on my projects so wondering if it's asset or project specific.

**Comment by renegadels** [comment]
Console doesn't show any errors for me. This happens when I try to copy paste entities not assets, and this can be any entity. I doubt it's project specific, since Leonidas had the same issue, as he said in his forum post.

**Comment by yaustar** [comment]
I've tried this with a basis entity (camera and a light), would you be able to provide an example project of entities that you were trying to copy and we can see if it's related to particular entities, components etc?

**Comment by renegadels** [comment]
https://user-images.githubusercontent.com/58387535/109508806-408c9380-7ac6-11eb-9139-18b3d11ac172.mp4

I've also added you to the project, so you can take a look.

**Comment by yaustar** [comment]
Looks like it is an issue to do the asset(s) being referenced. 
<img width="1267" alt="Screenshot 2021-03-01 at 15 01 15" src="https://user-images.githubusercontent.com/16639049/109515545-1e334f80-7a9f-11eb-91c5-4308570ca2ac.png">

Reimporting the model from FBX and referencing it again seems to make it work fine

**Comment by yaustar** [comment]
Created new bug ticket here: https://github.com/playcanvas/editor/issues/313

**Comment by renegadels** [comment]
> Looks like it is an issue to do the asset(s) being referenced.
> <img alt="Screenshot 2021-03-01 at 15 01 15" width="1267" src="https://user-images.githubusercontent.com/16639049/109515545-1e334f80-7a9f-11eb-91c5-4308570ca2ac.png">
> 
> Reimporting the model from FBX and referencing it again seems to make it work fine

I'll try this, thanks. Although, this model is from the Playcanvas asset store, so this may be an issue with that as well.
