### ISSUE TITLE
Tank asset from store has NaNs in the meta data

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#313]
Download the tank asset from the store:
![image](https://user-images.githubusercontent.com/16639049/109515793-681c3580-7a9f-11eb-9175-3e417dc34097.png)

See that the meta data has NaNs
<img width="1267" alt="Screenshot 2021-03-01 at 15 01 15" src="https://user-images.githubusercontent.com/16639049/109515843-736f6100-7a9f-11eb-8821-29a95881656c.png">

**Comment by Maksims** [comment]
At the time assets been added to store, there was no meta pipeline job on the server. Due to that, old assets can miss meta information. UI although, is not handling it nicely, just NaN's.

**Comment by willeastcott** [comment]
We now have a [new Asset Store](https://blog.playcanvas.com/announcing-the-new-playcanvas-asset-store) and this asset is no longer available. Closing.
