### ISSUE TITLE
Collision component to accept render asset type

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#314]
Currently only model can be dropped into Collision asset. This needs to be extended to handle Render asset as well.

![Screen Shot 2021-03-05 at 4 24 40 PM](https://user-images.githubusercontent.com/59932779/110143611-4e485e80-7dcf-11eb-8b3f-6e7818298dc8.png)

engine side: https://github.com/playcanvas/engine/issues/2944

**Comment by willeastcott** [comment]
Let's imagine I import an FBX with 100 mesh instances and I import to an asset template with 100 node with 100 render components. I wouldn't want to have to manually go and create 100 collision components and assign all the render assets. Would we automate that in the Editor somehow?

**Comment by willeastcott** [comment]
BTW, I think this is really an engine task rather than an Editor one, no?

**Comment by mvaligursky** [comment]
There's an engine equivalent issue linked in the description .. this part is the editor side - allowing render component to be dropped into collider component and similar.

I'm not sure how common the case of assigning lots of mesh colliders is .. typically there's a very few of them. We could in the future possibly have an import setting, and when the template is created during import, a colliders could be added automatically.

**Comment by mvaligursky** [comment]
this has been done
