### ISSUE TITLE
Projects with '#' in the name cannot be exported

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#319]
To reproduce, create a new project with `#` in the name like `Some #`.
Export from the projects view
Click on Download button
User is redirected to a 404

![image](https://user-images.githubusercontent.com/16639049/110786225-c85f6400-8263-11eb-822d-dbfd3aec1e85.png)

The same happens with the REST API too.

**Comment by vkalpias** [comment]
This should now be fixed.
