### ISSUE TITLE
Version control: conflict-overlay in view differences is misaligned

### ISSUE THREAD

**Issue by AaronLigthart** [playcanvas/editor#32]
Issue type: Text
Kind of issue: Overlap
Platform / Device: Chrome, Firefox

**Issue summary:**
When merging, and doing code reviews I use the view difference function to easily check new changes. Since a few days ago when I wanted to review some code I selected the changes since my last checkpoint and my first checkpoint. But then I noticed that the red, green and grey bars are on a different position then the lines that had been changed.
with a few lines of code it wasn't such an issue. but with large classes with multiple changes reading through the code became too confusing to read.
I tried changing to a different browser but I still had the same issue on firefox as I did on google chrome.

**Screenshot of the issue:**
![image](https://user-images.githubusercontent.com/5719804/77181948-4e6f2180-6acc-11ea-8256-532e68ba65ba.png)

**Comment by Maksims** [comment]
Can you verify if you had or had not any non 100% zoom in browser?

**Comment by AaronLigthart** [comment]
I had no zoom in on my browser, I also tried zooming in and out to see if everything would change but  the bars still remained on the wrong places.

**Comment by AaronLigthart** [comment]
I did just notice though! I had increased the font size in the code editor's preferences because I could then read it better. and if I shrank ik back 2 times the bars were in the right position, so I believe the bars dont take the font size into account

**Comment by yaustar** [comment]
Oops. Didn't see this ticket. This was fixed a month or so ago :)
