### ISSUE TITLE
Importing an .FBX with GLB enabled will not properly rename any included animation

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/editor#320]
### Description

In attempting to migrate our project to use GLB instead of JSON for FBX files, we have a cumbersome problem, in which any imported FBX that contains an animation, will have the generated animation file named Scene.glb.

When you import as JSON, it will correctly name the generated animation file as what the FBX was originally called. See attached screenshot.

![image](https://user-images.githubusercontent.com/5739868/106479964-2c477d80-64ab-11eb-83d9-5a1955374ef0.png)

Having to manually rename each imported animation is a daunting task when you have a lot of them.

### Steps to Reproduce

1. Drag in FBX file that has an animation in it, with Convert to GLB enabled.
2. Generated model .glb file will be named correctly as the .fbx file
3. Generated animation .glb file will NOT be named correctly as the .fbx file, but will instead always be named Scene.glb.

**Comment by yaustar** [comment]
We have decided a choice between the two naming conventions: 

Legacy: The FBX file name with a suffix if there's multiple 
Current: Take the name from the animation(s) in the FBX

**Comment by yaustar** [comment]
Thinking the options should be worded with a tooltip of an example and what this is for:

Animation import filename: "Use FBX filename | Use Animation name" (as a dropdown)

**Comment by yaustar** [comment]
This has been released with v1.15.19
