### ISSUE TITLE
Closed branches should be unfavourited

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#322]
When a branch is closed, it should automatically unfavourite the branch.

**Comment by vkalpias** [comment]
It looks like this is already what is happening?

**Comment by yaustar** [comment]
I've had a report that this wasn't happening? https://forum.playcanvas.com/t/cant-unfavorite-a-closed-branch/20593/2

**Comment by vkalpias** [comment]
Oh so when you close a branch it is unfavorited for you only not other users. Might be better to allow unfavoriting manually even if the branch is closed instead?

**Comment by yaustar** [comment]
Ah, that makes sense. Yeah, that sounds like the preferable option here.

**Comment by yaustar** [comment]
Released to production 1.18.12
