### ISSUE TITLE
Show model with material in preview

### ISSUE THREAD

**Issue by thisredone** [playcanvas/editor#323]
Right now the models are just white on the preview which makes it very difficult (or sometimes impossible) to discern.

![image](https://user-images.githubusercontent.com/1191844/111084103-12b93d00-8511-11eb-95e2-29e9a0f46797.png)

**Comment by willeastcott** [comment]
This has now been implemented:

![preview](https://user-images.githubusercontent.com/697563/199626853-ca802036-58e6-4335-978e-412b0b1fdb8e.gif)
