### ISSUE TITLE
Processing Quicksand Bold font has artifacts/gaps in the glyphs

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#326]
Forum post: https://forum.playcanvas.com/t/problem-with-importing-font/18900
Font: https://fonts.google.com/specimen/Quicksand?preview.text_type=custom

![image](https://user-images.githubusercontent.com/16639049/111462978-fd156480-8716-11eb-93b1-f9c42959ebd8.png)

Changing the intensity doesn't completely solve the issue.

**Comment by willeastcott** [comment]
Looks OK to me with an intensity of 0.19:

![image](https://user-images.githubusercontent.com/697563/221355995-db96baef-ed66-4ce8-b587-09d5c7953632.png)

Can we close this, @yaustar?

**Comment by yaustar** [comment]
There's still issues around importing some fonts and increasing the intensity can bring in other issues like:

![image](https://user-images.githubusercontent.com/16639049/221556718-0f61b665-8851-4144-b214-1bb2a86bed91.png)

However, I think this is a limitation of SDF and the fonts themselves. I wish we have a better solution to this but I don't think we will get to this unless we change how we process and render fonts.
