### ISSUE TITLE
For the developer.playcanvas.com search, users would like to exclude forum results

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#327]
Forum results were added so that we could drive users to the forum and use it as a 'wiki'. Unfortunately, they seem to be coming in above the User Manual and API references.

Some users would like these to be deprioritised or filtered out

**Comment by yaustar** [comment]
We might be able to use Results sorting based on meta tags? https://support.google.com/programmable-search/answer/2549537?hl=en&ctx=topic

**Comment by willeastcott** [comment]
The Developer Site has switched to Docusaurus that now uses Algolia for search. The results are much nicer now. Closing.
