### ISSUE TITLE
Show Asset Upload Date on Assets

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#330]
### Description

It would be nice if the assets detail panel included an upload date. I'm often working with different versions of assets and converting assets, so I find myself looking at the ID to figure out which version of an asset is the most recent.

For example:
![image](https://user-images.githubusercontent.com/6013871/111653620-6f9d4780-87de-11eb-9ef4-f9cb4ec43fbf.png)

Unlike the other properties on the right side, this information would not be in the asset registry and need to come from the editor state.

**Comment by yaustar** [comment]
Released to production 1.18.12
