### ISSUE TITLE
Preload setting on a folder doesn’t do anything at the moment

### ISSUE THREAD

**Issue by probitaille** [playcanvas/editor#331]
### Description

The preload setting on a folder doesn’t do anything at the moment. 

![image](https://user-images.githubusercontent.com/2374739/111783843-09bdc800-8891-11eb-8666-14bccbfba93f.png)

### Steps to Reproduce

1. Check the preload checkbox on a folder
2. Verify the preload setting of assets inside that folder (doesn't change)

### Solution

Maybe add a new use case to have it update the preload property of all assets included in that folder and sub-folders.

**Comment by Maksims** [comment]
Folder is very simple asset, and actually preload checkbox should not be visible for folder type asset.
If you set checkbox of folder to preload, but asset with folder to not preload, then should it preload, or not? And if you set folder preload to false, but asset preload to true, then should it load asset? It will create a confusion of why asset is not loaded, not obvious that it inherits preload of folder. Also, folder type asset is "thrown" away at runtime. It is simple asset just for organising in Editor.

**Comment by vkalpias** [comment]
We are no longer showing the preload field for folders.
