### ISSUE TITLE
Launcher overloads "hierarchy" load handler, breaking external URLs.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#332]
### Loading scene hierarchy using a custom URL is not possible in Launcher, due to a bug.

In Launcher, "hierarchy" loader is custom:
```js
SharedHierarchyHandler.prototype = {
    load: function (url, callback, settingsOnly) {
        var id = parseInt(url.replace("/api/", "").replace(".json", ""));
        if (typeof(id) === "number") {
            loadSceneByItemId(id, function (err, scene) {
                // ...
            });

        } else {
            // callback("Invalid URL: can't extract scene id.")
            this._handler.load(url, callback);
        }
    }
    // ...
};
app.loader.addHandler("hierarchy", new SharedHierarchyHandler(app, new pc.HierarchyHandler(app)));
```

And there is a condition:
```js
var id = parseInt(url.replace("/api/", "").replace(".json", ""));
if (typeof(id) === "number") {
```

If you provide any URL, then this always will be true, as parseInt return either a valid number or NaN, which `typeof(NaN) === true`. So `else` is never executed, making loading external URL scenes not possible.

Fix would be: 
```js
if (typeof(id) === "number" && ! isNaN(id)) {
```

Also check for `scene` handler just above `hierarchy` handler, same bug there.

**Comment by vkalpias** [comment]
This should now be fixed
