### ISSUE TITLE
Prevent scene viewport interaction when using Sprite Editor

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#334]
I noticed that when you use a Sprite Editor and zoom in on a sprite, you are also zooming in the viewport under it. Suggestion is to disable scene interaction while working in the Sprite Editor.

**Comment by yaustar** [comment]
Yep, related to https://github.com/playcanvas/editor/issues/77

**Comment by yaustar** [comment]
Fixed in #77

**Comment by NewboO** [comment]
Sorry for the necro but was it actually ever fixed? Zooming in the sprite editor still zooms in the viewport (and always had as long as I remember)

**Comment by willeastcott** [comment]
Thanks for highlighting this @NewboO. It looks like this was fixed for the _Curve_ Editor but not the _Sprite_ Editor. I have just submitted a fix that will likely be deployed next week. 🙏
