### ISSUE TITLE
Basis compression issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#335]
There is a project, where a mesh is using a non-POT non-square texture.  Here is the sample project:
https://playcanvas.com/editor/scene/1119862

After importing Basis library, I tried to compress it. After pressing Compress button, the texture icon doesn't turn to progress, but the compress button becomes not active. After that if the texture is deselected and selected again, the compress button is active again. There is also a warning message in the console:

![image](https://user-images.githubusercontent.com/5677782/112669838-d66ad280-8e68-11eb-8fda-b1ed5db2138f.png)

I also tried to turn on the legacy EC2 compression on, but get the similar behavior with the button being inactive/active. It would be nice if the asset would have a property that would clearly state if the texture is currently compressed or not.

**Comment by slimbuck** [comment]
Hi @LeXXik,

So sorry about this. It's actually a known issue with out-of-date editor UI on texture compression restrictions. We'll try fix this asap.

Thanks for logging the issue!

**Comment by LeXXik** [comment]
This has been fixed. Not sure by which one, probably #370 ? Closing.

**Comment by yaustar** [comment]
@slimbuck Did you mean to reopen this? It's still in the 'done' column

**Comment by yaustar** [comment]
Released to production 1.18.12

**Comment by yaustar** [comment]
Side note: Basis does support non POT textures but there's edge cases on what format and dimensions some older platforms can support that is a larger task than ensuring that the button is not active for POT textures
