### ISSUE TITLE
Animstategraph crash

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#343]
After adding a couple of animations to the state graph and closing it, I could no longer open the Animstategraph Editor. 

Console error:
![image](https://user-images.githubusercontent.com/5677782/113506564-4571b680-954e-11eb-96d9-6306fcc75936.png)

More details:
It looks like it crashes because the "defaultState" is missing. However, I am not sure what caused "defaultState" to not be available in the first place. I will see if I can reproduce.
![image](https://user-images.githubusercontent.com/5677782/113506622-8f5a9c80-954e-11eb-8ad8-6e53dbaadf57.png)

**Comment by yaustar** [comment]
I believe this is fixed
