### ISSUE TITLE
Pressing 'F' to focus on a 2D screen will focus on the containing elements rather than the screen dimensions

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#351]
Create a screen and place an image element to the top left. 
Select the screen entity and press F
Camera will focus on the element in the top left rather than the screen as a whole

This makes it a little more difficult to work on UI as most often than not, when the user selects the Screen entity, they want to frame the editor camera on the screen, rather than the elements that it contains.

**Comment by Maksims** [comment]
There are some issues, as currently, it can fail to calculate appropriate AABBs of elements that are disabled. This leads to incorrect AABBs, which often extends to the origin point.

**Comment by Maksims** [comment]
It's still an issue.

**Comment by willeastcott** [comment]
This function seems to be the issue:

```js
    editor.method('entities:aabb', (items) => {
        if (!items) {
            return null;
        }

        if (!(items instanceof Array)) {
            items = [items];
        }

        aabb.center.set(0, 0, 0);
        aabb.halfExtents.copy(defaultSizeSmall);

        // calculate aabb for selected entities
        for (let i = 0; i < items.length; i++) {
            const entity = items[i].entity;

            if (!entity) {
                continue;
            }

            aabbA.center.copy(entity.getPosition());
            aabbA.halfExtents.copy(defaultSizeSmall);
            calculateChildAABB(entity);

            if (i === 0) {
                aabb.copy(aabbA);
            } else {
                aabb.add(aabbA);
            }
        }

        return aabb;
    });
```

It needs a special case for entities that have a screen component.

**Comment by willeastcott** [comment]
OK, I think I've fixed this.

![screenaabb2](https://github.com/user-attachments/assets/d87ba232-4ae2-4ed0-82fb-29343e59f3ab)
