### ISSUE TITLE
Grid is pickable, material/cubemap drag to viewport issues.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#357]
### Description

Grid in Editor is pickable and affects picker selection, as well as dragging materials/cubemaps into the viewport.

### Steps to Reproduce

1. Create a new project from the Model Viewer Starter Kit
2. Create new cubemap
3. Drag cubemap onto an entity, with grid lines obstructing viewport

### Issue:
When the mouse is hovering grid, it will not pick entity, leading to flickering of the cubeamap preview between model and scene. If released while hovering grid, it will apply to Scene.

### Solution:
Make sure grid is not pickable.

**Comment by willeastcott** [comment]
I've submitted a fix for this. Should be deployed next week. Thanks for reporting! 😄
