### ISSUE TITLE
Gamma is wrong value for Model View Starter Kit

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#359]
### Description

Gamma in project settings is not defined for Model View Starter Kit

### Steps to Reproduce

1. Create new project from Model View Starter Kit
2. Open Editor
3. Go to Settings
4. Open Rendering Panel

### Issue:
"Gamma" has unselected value.

### Solution:

`editor.call('sceneSettings').get('render.gamma_correction')`
Equals to 2, but there are only two valid values:
`0` - 1.0
`1` - 2.2

So scene settings `render.gamma_correction` for Model View Starter Kit should be `1`.

**Comment by willeastcott** [comment]
Fixed. Thanks for reporting!
