### ISSUE TITLE
Read-only projects, not clickable thumbnails on asset pickers.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#36]
Any read-only project related.
In Inspector Panel, any asset picker thumbnail is not clickable, so navigating through referenced assets is not possible.
**Expected behaviour:** thumbnail to be clickable regardless of project permissions.

**Comment by willeastcott** [comment]
Thanks for the bug report @Maksims. We'll aim to fix this on Monday.

**Comment by willeastcott** [comment]
@ellt92 just deployed a fix for this. Enjoy! 😄
