### ISSUE TITLE
Unable to pick an asset for Render Component

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#367]
It looks like I am not able to select an asset for Render Component in the Editor. It simply doesn't see any assets in the folder, which contains GLB and JSON models. All of them can be used in a Model Component, though.

Edit:
Ok, I see, it is because it requires a container type of an asset. However, isn't the parsed FBX > GLB is a container? Or do I need to use pc.ContainerResource explicitly?
I also saw this forum topic:
https://forum.playcanvas.com/t/is-it-possible-to-add-rigid-body-and-collision-to-a-glb-file-which-i-have-generated-with-a-script/18487
I tried to set an attribute to binary, but it doesn't see the asset in the folder. I guess it is because the GLB is a parsed one and not the original? I tried to load it via loadFromUrl, and it complained about the GLB magic word in the header.

**Comment by yaustar** [comment]
IIRC, FBX -> Container will import a FBX into a GLB model assets, create a template of Entities hierarchy and a bunch of render assets per mesh instance. The render assets are used with the render component:
![image](https://user-images.githubusercontent.com/16639049/114678197-ef95cf00-9d02-11eb-89fb-6763d3e0a6fc.png)

**Comment by yaustar** [comment]
@mvaligursky Can detail more :)

**Comment by mvaligursky** [comment]
In the Settings, Asset Tasks, you need to have "Create Container Assets" ticket, which generates Render assets when you import FBX. Those can be assigned to the Render Component.
When you have that ticked, it also creates a single template asset .. which is the entity hierarchy + all render components set up .. so you normally drag & drop that to the scene.

**Comment by LeXXik** [comment]
I think it is ok, if I comment in this one, since it is related. Let me know, if you want a new issue.

As @mvaligursky pointed, I have enabled the Create Container Assets in the project settings in order to generate the render assets, but it breaks on import:
![image](https://user-images.githubusercontent.com/5677782/116064114-5f567300-a68e-11eb-9b87-955ce5bc9129.png)

The model is the bowling pin here, added you Martin as well:
https://playcanvas.com/project/788485/overview/editor-model-issue

**Comment by mvaligursky** [comment]
I created a new project, enabled import to templates and import your pin2.fbx without a problem, it renders correctly when I add the template to the scene as well.

**Comment by LeXXik** [comment]
Ok, so it appears there is a specific path needs to be taken in order to repro:

1. Open the shared project, select the model FBX file and copy it
2. Open new project, paste it there
3. Right click the FBX and select Re-import option

**Comment by mvaligursky** [comment]
Please do create a new issue as that's not related to the original issue.
