### ISSUE TITLE
Change non POT Basis warning

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#370]
![image](https://user-images.githubusercontent.com/16639049/114536559-1bed1500-9c49-11eb-9571-45e9285c4495.png)

The message implies that non POT textures will work but it actually falls back to a different format RGB565 (?).

We also need to add extra detail for the non tech savvy users. Eg This will affect WebGL 1 only devices such as iOS platforms.

**Comment by willeastcott** [comment]
I've fixed this. Should be deployed within the next 24 hours.
