### ISSUE TITLE
'Open with Viewer' doesn't work with GLB files in a branch

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#371]
![image](https://user-images.githubusercontent.com/16639049/114699270-f975fd00-9d17-11eb-9c01-38d0984cadcd.png)

![image](https://user-images.githubusercontent.com/16639049/114699327-0db9fa00-9d18-11eb-8b7c-40089b127a3c.png)

Create private project, open a branch that isn't master, try to view a GLB in the branch using the viewer.

**Comment by willeastcott** [comment]
I don't seem to be able to reproduce this problem:

![viewer-glb](https://user-images.githubusercontent.com/697563/115999700-a5ef9300-a5e4-11eb-906e-437092e269a6.gif)

What am I doing wrong?

**Comment by yaustar** [comment]
Maybe if it's in a branch and private or just private projects it doesn't work? 🤔

**Comment by willeastcott** [comment]
The project I screen recorded was private.

**Comment by yaustar** [comment]
Looks like if the asset only exists in the branch the issue happens. In your case, the assets existed in the master before branching and the viewer could be getting the asset from the master branch instead of your current branch?


Uploading Kapture 2021-04-25 at 19.36.03.mp4…

**Comment by yaustar** [comment]
Looks like this section of code doesn't handle the branchId param and value correctly in the viewer:

![image](https://user-images.githubusercontent.com/16639049/116005357-72216700-a5fe-11eb-8f8c-392b62f87873.png)

Just noticed that the URL is incorrect too, there's two `?` in the URL when there should be one:

`https://playcanvas.com/viewer?load=https://playcanvas.com/api/assets/46534368/file/BlankBitmoji-clone.glb?branchId=e6f4a527-8e0b-43bb-b74c-67385f55af52`

Should be:
`https://playcanvas.com/viewer?load=https://playcanvas.com/api/assets/46534368/file/BlankBitmoji-clone.glb&branchId=e6f4a527-8e0b-43bb-b74c-67385f55af52`

It looks like (from a quick look), branchId param isn't catered for

**Comment by yaustar** [comment]
Ah, did a bit more investigation. We should be using `encodeURIComponent` to encode the asset URL for a param:

So `https://playcanvas.com/viewer?load=https://playcanvas.com/api/assets/46534368/file/BlankBitmoji-clone.glb?branchId=e6f4a527-8e0b-43bb-b74c-67385f55af52`

Becomes `https://playcanvas.com/viewer?load=https%3A%2F%2Fplaycanvas.com%2Fapi%2Fassets%2F46534368%2Ffile%2FBlankBitmoji-clone.glb%3FbranchId%3De6f4a527-8e0b-43bb-b74c-67385f55af52`

Which does work in the viewer. This is an editor side fix.

**Comment by willeastcott** [comment]
OK, I submitted a PR to fix this. Awesome detective work! :smile:
