### ISSUE TITLE
When creating new button entity, should the text element default color be black?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#375]
From forum: https://forum.playcanvas.com/t/text-font-and-button-text-color-combo-suggestion/19559

![image](https://user-images.githubusercontent.com/16639049/115143169-9baa2380-a03d-11eb-9e2b-c1896f8b09d1.png)

By making the text element black in this case, the text against the white element will be immediately visible. At the moment, it's white on white.

I'm not entirely sure about this one as usually, an image is used for the button and black on a colored background doesn't look great and white text is a better color.

![image](https://user-images.githubusercontent.com/16639049/115143241-04919b80-a03e-11eb-91b4-393c824bed25.png)

**Comment by Maksims** [comment]
Black colour would be more in line with default colours for text in various systems.

**Comment by jpauloruschel** [comment]
Change has been merged and will be available on the next Editor release.
