### ISSUE TITLE
Localization loses file references

### ISSUE THREAD

**Issue by PHou81** [playcanvas/editor#38]
If I create a couple of json-files for localizaton, add them as assets in the localization section of the settings menu and then refresh the browser, the references appear as "Missing".
The localization still works if I change Locale in the Editor section, so I guess this is just a cosmetic thing?

![lost_references](https://user-images.githubusercontent.com/33447171/77834107-5d944600-7142-11ea-9cf3-fb3d3895ed5d.jpg)

**Comment by willeastcott** [comment]
Thanks for reporting this @PHou81. Yes, I suspect this is just cosmetic. We'll investigate further on Monday.

**Comment by willeastcott** [comment]
@ellt92 just deployed a fix for this. Enjoy! 😄
