### ISSUE TITLE
Glitch at left side of screen in Anim State Graph

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#383]
### Description
When you are in the edit mode of an Anim State Graph there is something missing at the left side of the screen. 
Below you can see what I mean.

![KT4yGtrmok](https://user-images.githubusercontent.com/52896137/117184833-75c0a500-add9-11eb-884d-95511ce3e131.gif)

### Steps to Reproduce
1. Create a new Anim State Graph
2. Go to edit mode
3. Check the left side of the screen

**Comment by ellthompson** [comment]
This has been fixed in production
