### ISSUE TITLE
Be able to remove Initial State of Anim State Graph

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#384]
I currently have a setup where I don't want to use the Initial State and Default Transition. It would be nice if I can remove them.

![d450b521e2c5ae835f31b917b4ac8fdc48cd2e09](https://user-images.githubusercontent.com/52896137/117186138-d4d2e980-adda-11eb-8167-c63d453aec22.png)

**Comment by yaustar** [comment]
This is not possible as when the state graph 'starts', it has to go to a state such as Idle. You don't have to use Initial State as your starting state. This can be changed to any of your other states.

**Comment by albertvanveen** [comment]
Thanks for your comment. It was not possible to change the Default Transition to another state, so I changed my setup and used the Intial State as one of my states. I think it is designed that way too.

![image](https://user-images.githubusercontent.com/52896137/117202328-fa1d2300-aded-11eb-9743-b98e97a86cfc.png)

**Comment by yaustar** [comment]
> It was not possible to change the Default Transition to another state

It *should* be, if you can't, that's a bug. The initial state should be changeable in the stategraph properties.

**Comment by albertvanveen** [comment]
> The initial state should be changeable in the stategraph properties.
That's working indeed, I was trying to make a new transition.
