### ISSUE TITLE
Confirmation dialogue when deleting

### ISSUE THREAD

**Issue by Delverino** [playcanvas/editor#388]
When I go to delete a scene or asset, I get a dialogue popup that says “Are you sure you want to delete this Scene/Asset?” I’m always a little bit nervous to click yes because I have a nagging feeling I’m deleting the wrong one. If it’d be easy to implement, I’d love it if the popup instead said “Are you sure you want to delete SceneName/AssetName?” with SceneName or AssetName being the actual name of the scene or asset I’m trying to delete. Thanks!

**Comment by willeastcott** [comment]
I've updated the scene deletion dialog to do this:

![image](https://user-images.githubusercontent.com/697563/117372807-0b376400-aec2-11eb-9101-ee29fd003f47.png)

**Comment by Delverino** [comment]
Wow that was fast, thanks!

**Comment by willeastcott** [comment]
I've also updated the asset deletion modal:

![image](https://user-images.githubusercontent.com/697563/117373744-c4e30480-aec3-11eb-8d23-c4a6072dfd62.png)

**Comment by Delverino** [comment]
Thank you!

**Comment by willeastcott** [comment]
You're welcome @Delverino. This should be deployed to the production server within a day or so.
