### ISSUE TITLE
Reimport option on a FBX should behave the same way as though it has been uploaded

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#389]
Related: https://github.com/playcanvas/editor/issues/244

At the moment, the only way to update settings such as sample rate, curve tolerance etc on an animation asset, is to reupload the FBX file.

**Comment by Maksims** [comment]
Ideally, there would be a way to override import settings per source/target asset.
But I do agree that re-importing by default should use current import settings in a project. As recently had to experiment with animation assets, and had to delete > upload it again. With larger files, and complex container context, this was annoying.

Also, on Animation asset, there is no re-import setting, which would run animation pipeline task again. For model assets - there is.

**Comment by willeastcott** [comment]
This has now been implemented and deployed. @slimbuck, please close this if you agree nothing is outstanding related to this.

**Comment by slimbuck** [comment]
Yup this has been done. Per-asset settings is next on the list.
