### ISSUE TITLE
Value change not always applied in Anim State Graph

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#394]
If you change a value of a Transition in Anim State Graph and you switch to another Transistion or State the change is not applied. Since a change is applied in a similar situation elsewhere in the editor, I think this is a bug.

![EZf9UXEHwq](https://user-images.githubusercontent.com/52896137/117548076-34c3cd00-b033-11eb-9801-09e122387fa3.gif)

**Comment by yaustar** [comment]
Re-bump as this is affecting a few users at the moment

**Comment by yaustar** [comment]
Confirmed this behaviour is different compared to the entity inspector
![Kapture 2021-07-28 at 10 13 26](https://user-images.githubusercontent.com/16639049/127296855-d82e9715-ce6b-4667-a818-9023747a3b38.gif)

**Comment by albertvanveen** [comment]
This problem is still present and very annoying.

**Comment by ellthompson** [comment]
A fix for this has been released to prod.
