### ISSUE TITLE
Exit Time works not correct in Anim State Graph

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#395]
### Description
I tried to set a very low Exit Time on a Transistion in Anim State Graph. If the Exit Time is lower than 0.05 the Exit Time in game is not correct anymore. I think in that case the Exit Time is set to 1. (If I set the Exit Time 0.05 or more it works only the first transition correct).

### Steps to Reproduce
1. Set the Exit Time of a Transistion on for example 0.02.
2. Check the Exit Time in game.

**Comment by yaustar** [comment]
What exit time do you get instead when it is set 0.02?

**Comment by albertvanveen** [comment]
At first I thought that it just didn't work at a low Exit Time and in that case the animation only changed after about 1 second, but now I notice that sometimes an animation does not change at all when an Exit Time is set. For me it is about Transition coming from the Any State. I will see if I can reproduce this in another project.

**Comment by albertvanveen** [comment]
I can reproduce this problem in the project below. Pressing and releasing the P key will change the animation after 0.5 seconds, but in this case this works only the first transition. (This is also the case in my own project when the Exit Time is higher then 0.05).

https://playcanvas.com/project/793490/overview/animation-exit-time

**Comment by yaustar** [comment]
I've forked the project and removed extra transitions and conditions to make the explanation easier: https://playcanvas.com/editor/scene/1147628

![image](https://user-images.githubusercontent.com/16639049/117551113-e9fa8300-b03b-11eb-83eb-06188e1d8caa.png)

The exit value is normalised between 0-1, where 1 is the full length of the animation and 0.5 is half the animation length.

In this example, there is a transition that goes from idle to punch with an exit time set to 0.5.

This means it will play half the idle animation before starting to blend and playing the punch animation which looks fine in my fork.

There does seem to be odd behaviour if the idle state is set to loop and the condition is met after the the exit time which I will need to talk to @ellthompson about what the expectation should be.

**Comment by albertvanveen** [comment]
Thanks for your explanation. Indeed, I had not understood it that way. Other than that, the Punch animation is also set to loop. So why the animation goes to the Punch State, but never goes back to the Idle State until I remove the Exit Time? (Also a Exit Time lower than 0.05 gives not the right result in my opinion).

**Comment by yaustar** [comment]
I think there is an issue with exit time and conditions/loops. Will raise with Elliott
