### ISSUE TITLE
Bug with unsaved highlight color in code-editor

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#397]
### Description
If you make a change to your script without saving it, the script name will be highlighted in orange. If you undo this change, the highlight is retained even if you save the script. I think there are two possible solutions: Remove the hightlight color automatic when there is no change anymore or remove the highlight color after saving, even if there was no change.

### Steps to Reproduce
1. Make a change in a script, for example type the letter A
- Script gets orange highlight color
2. Undo the change, or remove the letter A
- Script keeps orange highlight color
3.  Save the script
- Script keeps orange highlight color

**Comment by vkalpias** [comment]
This should now be fixed
