### ISSUE TITLE
Import Assets from project A into project B (same mechanism as playcanvas store)

### ISSUE THREAD

**Issue by FrantzVZ777** [playcanvas/editor#40]
Currently it is not convenient to copy assets from one project to another.
Let’s say I have:

- Project A with an HDRI environment
- Project B with a Car

It would be great to be able to import the assets from project A into project B without reseting the materials settings etc. Or vice versa.

I have seen that Playcanvas store actually allows to do something very similar: 
https://store.playcanvas.com/
Allowing you to import the files inside any of the playcanvas project within your account.

We would like to develop our own Private Store webpage (same as your store) listing all our projects hosted in playcanvas and let you import Projects assets into other projects.

Is there any script or method we could call in order to achieve this? Ideally without migrating projects outside from playcanvas.

**Comment by yarpskendaya** [comment]
Copying assets from project to project would be extremely useful!

**Comment by willeastcott** [comment]
This is in closed beta right now. We'll enable for everybody soon.

**Comment by willeastcott** [comment]
This feature is now implemented and deployed:

https://blog.playcanvas.com/copy-and-paste-assets-between-projects/
