### ISSUE TITLE
Editor crash with zero sized Image Element parent

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#404]
Steps:

1. Add a 2D Screen
2. Under it, add a new Entity with Image Element
3. Set image element's width and height to 0
4. Under it, add a new Image Element
5. Drag the Anchor arrows of the child image element in the viewport to change its size (might need to try couple of times, dragging different arrows)
6. Editor crashes

Repro: https://playcanvas.com/editor/scene/1163006

![image](https://user-images.githubusercontent.com/5677782/119341567-9b382480-bc9c-11eb-9b91-7481ab50dc56.png)

**Comment by jpauloruschel** [comment]
Fix has been implemented and will be live next Editor release.

**Comment by jpauloruschel** [comment]
The fix has been deployed and is now live 😄
