### ISSUE TITLE
import hierarchy - create folders?

### ISSUE THREAD

**Issue by alamboley** [playcanvas/editor#405]
Hey,

I love this new feature, this was really a missing part of PC.

PlayCanvas can import several FBXs at the same time. Due to the number of elements imported, it can be a real mess in the assets folder. Perhaps things should be putted together in a folder automatically?
Maybe add this as an option to tick like “import hierarchy” ? “create sub folder”?
Or perhaps just an option to hide / fold back those sub elements in the parent?

![unknown](https://user-images.githubusercontent.com/687978/119525950-3c97a700-bd7f-11eb-910d-99fc2200c6c9.png)

**Comment by Maksims** [comment]
A better folder structure is indeed sometimes wanted.
Mimicking folder structure based on a hierarchy of the model - would be a disaster in many cases. As hierarchies can be crazily structured, and that cannot be done, as some meshes can be used multiple times in various places of model tree.

But having a folder structure per type of things: materials, animations, models, etc. - that would be definitely a good thing to have. Something like:
- "materials" (folder)
- "meshes" (folder) (if exist in a container)
- "animations" (folder) (if exist in a container)
- "textures" (folder) (if exist in a container)
- "name of a file" (template)
- "name of a file" (source file)

That way you still can do re-imports, re-uploads, and drop multiple FBX files into the same folder, where files would be nicely sorted.

**Comment by yaustar** [comment]
+1 on being able to import a FBX into it's own folder or some sort of folder structure. I have 10 FBXs to import and right now, it's a pain doing one at a time while I create the folders.

**Comment by saadhaider78** [comment]
Bump

**Comment by yaustar** [comment]
+1 from a Snapchat games developer.

**Comment by yaustar** [comment]
Added in v1.21.28
