### ISSUE TITLE
Picked entity is not always scrolling to it in Hierarchy.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#406]
### Steps to Reproduce

1. Ensure you have a complex hierarchy with depth that can take longer than the height of hierarchy.
2. Select an entity by picking on the viewport.
3. Select another entity the same way that is located in a different place on the hierarchy.

### Issue: 

It is not always scrolling in the hierarchy.
EDIT: if any ancestor of the selected entity is not open in the hierarchy, it will not scroll to it on selection.

**Comment by vkalpias** [comment]
A simple test I tried seems to work fine - can you maybe share a hierarchy that this can be reproduced more easily?

**Comment by Maksims** [comment]
Here is a project: https://playcanvas.com/editor/scene/1111557
Managed to narrow down replication:
1. Ensure the picked entity is within another entity that is not "open" in hierarchy.

In this particular example:
1. Open "pedestal" entity in a tree
2. Click in viewport on the picture (ensure "pictures" entity is closed in the hierarchy):

![image](https://user-images.githubusercontent.com/636263/121320088-8357d600-c915-11eb-945f-1230da74013c.png)

### Issue:
If any ancestor entity is closed in the hierarchy, it will not scroll to it.
