### ISSUE TITLE
Problems uploading FBX files

### ISSUE THREAD

**Issue by Ailisax** [playcanvas/editor#409]
I tried to upload a file in FBX format, even though it was only 8M, but I couldn't upload it successfully. 
What's going on here? It seems to have crashed .
I also tried using GLB files, but the model ended up broken.Are there any requirements for uploading files to the model?

**Comment by willeastcott** [comment]
Is there any way you can share the FBX in question? Then we will be able to investigate.

**Comment by Ailisax** [comment]
I will reply to the relevant content in yesterday's email

> 有什么方法可以分享有问题的 FBX？然后我们就可以进行调查了。

I will reply to the relevant content in yesterday's email

**Comment by Ailisax** [comment]
I tried to add my model file in the email, but it seems that 18.9m exceeds the size limit of your email, do you have some other solutions



On 06/03/2021 23:58, 黑夏 wrote:




Hello guys


I have a problem ,I have a GLB file.When I checked with the 3D viewer in Win10, the model and animation were correct .




But after I import PlayCanvas, the model and animation will have problems, as shown in the picture below. 

Attached is my GLB file.

I hope you can give me some advice to solve this troublesome problem .

Thank you 




At 2021-06-02 23:46:53, "Will Eastcott" ***@***.***> wrote:

Is there any way you can share the FBX in question? Then we will be able to investigate.

**Comment by yaustar** [comment]
When it is working again, use https://catbox.moe/ please and email us the link please?

**Comment by Ailisax** [comment]
Hello guys




I have already uploaded the file , Can you help to analyze the cause of the problem?

After this GLB file is imported into PlayCanvas, the model and animation is wrong, 

It also cannot be loaded into the scene for editing .

Can you help me?

https://files.catbox.moe/d2trux.zip













At 2021-06-04 00:50:15, "Steven" ***@***.***> wrote:

When it is working again, use https://catbox.moe/ please and email us the link please?

**Comment by willeastcott** [comment]
That GLB file seems to load fine in the [glTF Viewer](https://playcanvas.com/viewer):

![image](https://user-images.githubusercontent.com/697563/120799805-1ae4af80-c537-11eb-8472-e2fc482db2e8.png)

Also, I thought you were going to provide the FBX file. Can you upload that as well please?

**Comment by Ailisax** [comment]
This time it's an FBX file. 

The previous GLB file is visible in the Gift Viewer, but the model is missing.

But when I see it in the 34Viewer of Win10, it is normal.

Is the GLB file not loaded into the scene editor?

https://files.catbox.moe/wq3cr8.zip







At 2021-06-04 20:17:52, "Will Eastcott" ***@***.***> wrote:

That GLB file seems to load fine in the glTF Viewer:

Also, I thought you were going to provide the FBX file. Can you upload that as well please?

**Comment by willeastcott** [comment]
It seems that there is a character being written to JSON file on import which is invalid. 

![image](https://user-images.githubusercontent.com/697563/120804958-1d4a0800-c53d-11eb-8d80-d2a99d3cfd0b.png)

@slimbuck - can you investigate when you get a moment please?

**Comment by Ailisax** [comment]
Is this a serious problem?



Is it a BUG or an FBX file error?  In the early stages of modeling and animation,

I have successfully imported a model .

Sorry to trouble you.Because I need to find a solution to this problem

 thank you 










At 2021-06-04 21:00:22, "Will Eastcott" ***@***.***> wrote:

It seems that there is a character being written to JSON file on import which is invalid.

@slimbuck - can you investigate when you get a moment please?

**Comment by slimbuck** [comment]
Hi @Ailisax,

This looks to be a problem with our pipeline.

It seems we're not escaping some unicode characters correctly for embedding in JSON.

For example I see:
![Screenshot 2021-06-04 at 14 22 12](https://user-images.githubusercontent.com/11276292/120807833-4a4bea00-c540-11eb-8696-c16f698a3879.png)

This is something we'll investigate on our end, but if you want to get it working quickly now, you could rename your FBX materials to not include the failing characters.

(Unfortunately I don't know yet -which- characters are not being correctly escaped)

Thanks!

**Comment by slimbuck** [comment]
The other material name that is failing is:

![Screenshot 2021-06-04 at 14 26 23](https://user-images.githubusercontent.com/11276292/120808365-e970e180-c540-11eb-84b8-6635712449c9.png)

**Comment by Ailisax** [comment]
So I just need to update the name of my material? Isn't it?
















At 2021-06-04 21:25:02, "Donovan Hutchence" ***@***.***> wrote:

Hi @Ailisax,

This looks to be a problem with our pipeline.

It seems we're not escaping some unicode characters correctly for embedding in JSON.

For example I see:


This is something we'll investigate on our end, but if you want to get it working quickly now, you could rename your FBX materials to not include the failing characters.

(Unfortunately I don't know yet -which- characters are not being correctly escaped)

Thanks!

**Comment by slimbuck** [comment]
Yes, rename these two materials. If that does work for you, please let us know :)

**Comment by Ailisax** [comment]
Uh-huh, I'll try to rename the material

Then see if the problem can be solved . 

Thank you










At 2021-06-04 21:28:45, "Donovan Hutchence" ***@***.***> wrote:

Yes, rename these two materials. If that does work for you, please let us know :)

**Comment by willeastcott** [comment]
We've fixed the original bug and this fix will be deployed to our production server early next week. But in the meantime, I hope the renaming of those materials resolved the problem.

**Comment by Ailisax** [comment]
Hello 

Please tell me that the FBX file has become much larger after parsing.

Is there any good way to solve this problem
















在 2021-06-05 07:31:41，"Will Eastcott" ***@***.***> 写道：

We've fixed the original bug and this fix will be deployed to our production server early next week. But in the meantime, I hope the renaming of those materials resolved the problem.

**Comment by willeastcott** [comment]
The size of the FBX will not match the imported GLB file.

What are the sizes you are noticing? Is there a project URL we can inspect?

**Comment by Ailisax** [comment]
Emmmm ，

I'm a beginner, and to be honest I don't really know how to figure out a URL，

You can try the link below, or if that doesn't work, you can use the Catbox link to download my favorite FBX file .

 want to make the GLB file generated after importing FBX smaller, could you give me a direction of optimization？




https://playcanvas.com/project/802490/overview/xxx

https://files.catbox.moe/xloaex.fbx










At 2021-06-07 04:45:53, "Will Eastcott" ***@***.***> wrote:

The size of the FBX will not match the imported GLB file.

What are the sizes you are noticing? Is there a project URL we can inspect?

**Comment by Ailisax** [comment]
My dear guys


Why is it that the texture I have in the modeling software, it is in alpha channel and it displays normally, 
but after importing PlayCanvas, the white part of the texture is not transparent? Just like the image below 。

Do I need to set anything on PlayCanvas? 







At 2021-06-07 04:45:53, "Will Eastcott" ***@***.***> wrote:

The size of the FBX will not match the imported GLB file.

What are the sizes you are noticing? Is there a project URL we can inspect?

**Comment by willeastcott** [comment]
Check the Opacity section for your material. If you have a PNG with alpha channel on the Diffuse texture slot, you must also ensure that the same PNG is set on the Opacity texture slot:

![image](https://user-images.githubusercontent.com/697563/121145536-f9394000-c836-11eb-8fd1-9928d47bbc55.png)

And also that you have a valid blend mode (Alpha is typically what you need) and that you specify opacity is read from the A channel in the image.

**Comment by Ailisax** [comment]
Yes ，thank you very much .
I found this setting late yesterday, but thank you very much for your help 。
















At 2021-06-08 15:54:14, "Will Eastcott" ***@***.***> wrote:

Check the Opacity section for your material. If you have a PNG with alpha channel on the Diffuse texture slot, you must also ensure that the same PNG is set on the Opacity texture slot:

And also that you have a valid blend mode (Alpha is typically what you need) and that you specify opacity is read from the A channel in the image.

**Comment by Ailisax** [comment]
Hello guys


Why does the model break after import? At the same time, I would like to ask is there any way to improve the display accuracy in pkayCanvas













At 2021-06-08 15:54:14, "Will Eastcott" ***@***.***> wrote:

Check the Opacity section for your material. If you have a PNG with alpha channel on the Diffuse texture slot, you must also ensure that the same PNG is set on the Opacity texture slot:

And also that you have a valid blend mode (Alpha is typically what you need) and that you specify opacity is read from the A channel in the image.

**Comment by Ailisax** [comment]
I’m so sorry .
But I found that although I made some model animations, 
many of them would disappear when I imported them into PLYACANVAS. 
I have no idea what happened. Could you please help me check it
















At 2021-06-08 15:54:14, "Will Eastcott" ***@***.***> wrote:

Check the Opacity section for your material. If you have a PNG with alpha channel on the Diffuse texture slot, you must also ensure that the same PNG is set on the Opacity texture slot:

And also that you have a valid blend mode (Alpha is typically what you need) and that you specify opacity is read from the A channel in the image.

**Comment by yaustar** [comment]
The messages you are sending don't show images or model attachments. Can you please share the models that are causing you issues please?

**Comment by Ailisax** [comment]
This is the model link, and I need to put them in a scene and the first image is what it looks like in my C4D, 
and the other link is what it looks like when it's done.
The third link is what I wanted, but the animation is just the red car moving, everything else is lost.
I have no idea which way to adjust these problems. Thank you very much



https://files.catbox.moe/8j41yo.zip



https://playcanv.as/b/6GQcBhKC/

https://files.catbox.moe/p20r6y.mp4

At 2021-06-17 20:10:40, "Steven" ***@***.***> wrote:

The messages you are sending don't show images or model attachments. Can you please share the models that are causing you issues please?

**Comment by yaustar** [comment]
I've tried an import of the models and it looks fine to me with all the animations playing: https://playcanvas.com/project/805992/overview/model-import-issues

Uploading Kapture 2021-06-17 at 13.35.21.mp4…

**Comment by Ailisax** [comment]
I opened it blank, maybe you didn't post it?
















At 2021-06-17 20:36:26, "Steven" ***@***.***> wrote:

I've tried an import of the models and it looks fine to me with all the animations playing: https://playcanvas.com/project/805992/overview/model-import-issues

Uploading Kapture 2021-06-17 at 13.35.21.mp4…

**Comment by yaustar** [comment]
Both the link and video should work. Can you look at the issue page on GitHub please? It is a lot easier to view the contents there: https://github.com/playcanvas/editor/issues/409

**Comment by Ailisax** [comment]
I can see that. Thank you very much. 
I want to know, is there any way to improve the accuracy of the display, or can I only change the model?













At 2021-06-17 20:44:08, "Steven" ***@***.***> wrote:

Both the link and video should work. Can you look at the issue page on GitHub please? It is a lot easier to view the contents there: #409

**Comment by yaustar** [comment]
What do you mean by accuracy? What is inaccurate?

**Comment by Ailisax** [comment]
B: well... I mean, to make the model look more refined, to make the face on the model less clear, you know what I mean?
Things like these in the picture can get smoother 










At 2021-06-17 21:21:45, "Steven" ***@***.***> wrote:

What do you mean by accuracy? What is inaccurate?

**Comment by yaustar** [comment]
The images in your email don't show up in GitHub issues. You will need to post directly to GitHub for us to see it.

**Comment by Ailisax** [comment]
> 您电子邮件中的图像不会出现在 GitHub 问题中。您将需要直接发布到 GitHub 以供我们查看。
![捕获](https://user-images.githubusercontent.com/85242553/122408890-4a72cd80-cfb5-11eb-948e-7861842367f7.PNG)
Is that all right now？

**Comment by yaustar** [comment]
That issue is also in the FBX so it's something to discuss with your modeller. It's not my speciality but I think it's to do or related to smoothing groups on the mesh.

**Comment by Ailisax** [comment]
OK， i know ，thank you very much .if i have other questions ,I'll come to you for help 













At 2021-06-17 21:50:46, "Steven" ***@***.***> wrote:

That issue is also in the FBX so it's something to discuss with your modeller. It's not my speciality but I think it's to do or related to smoothing groups on the mesh.

**Comment by yaustar** [comment]
Yep, if you can, please post in the forums for general help: https://forum.playcanvas.com/

**Comment by Ailisax** [comment]
Hello guys


I found the emissive setting ,
But can PlayCanvas add the effect of object glow and spread?
Like the glow in the picture below







Thank you 

At 2021-06-17 22:11:12, "Steven" ***@***.***> wrote:

Yep, if you can, please post in the forums for general help: https://forum.playcanvas.com/

**Comment by yaustar** [comment]
@Ailisax This type of question is best posted on the forums: https://forum.playcanvas.com/

Can you post here please with the image (we can't see the image on GitHub)?

**Comment by leonidaspir** [comment]
Hi @Ailisax, check the bloom post process effect, here is an example:

https://playcanvas.github.io/#/graphics/post-effects

**Comment by Ailisax** [comment]
Hello 
I created the question and uploaded the picture, but the account temporarily on hold 













At 2021-09-10 21:34:17, "Steven" ***@***.***> wrote:

@Ailisax This type of question is best posted on the forums: https://forum.playcanvas.com/

Can you post there please with the image (we can't see the image on GitHub)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ailisax** [comment]
Hi guys


Open the link and you can see my post and you can see the pictures




https://forum.playcanvas.com/t/about-object-glow/21846










At 2021-09-10 21:34:23, "Leonidas" ***@***.***> wrote:

Hi @Ailisax, check the bloom post process effect, here is an example:

https://playcanvas.github.io/#/graphics/post-effects

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
