### ISSUE TITLE
Alpha Test option disappears

### ISSUE THREAD

**Issue by Alb3rt1990** [playcanvas/editor#41]
### Description
The Alpha Test option in Opacity settings of a material is not visible if you have selected multiple materials but with diffrent texture on it. I don’t know if this is a bug or feature.

### Steps to Reproduce
1. Select a material and you can find the Alpha Test option in the Opacity settings
2. Select a second material with a diffrent texture and the Alpha Test option dissapears

**Comment by vkalpias** [comment]
Should be fixed now.
