### ISSUE TITLE
Add project-wide settings for JSHint

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#415]
When working in IDE, today some projects can safely make a decision to target ES6+ platforms, using more modern JS features described in ECMA releases.

Also working in teams, gets affected even more with such an approach, as IDE currently using JSHint is not handling ES6+ features well by default.

# Feature Request:

Implement Project-wide settings (affecting all users in a project) for JSHint, which would include some popular options:
`esversion` - to specify ES* version.

**Comment by marklundin** [comment]
This would be useful for the [PlayBuild](https://github.com/wearekuva/playbuild) too. At the moment if you import a 3rd party module that contains some code that JSHint doesn't like such as a reference to `sessionStorage`, it will bundle and run correctly, but the jshint script parser will flag an error. And as it originates from a 3rd party module it's not possible to add an inline directive. A global jshintrc or similar would solve this

**Comment by willeastcott** [comment]
I believe this issue was logged before the Code Editor was updated to Monaco. It is now no longer locked to an old version of JS and doesn't complain to the user if modern JS is used. Closing.
