### ISSUE TITLE
Can't create ParticleSystem in editor

### ISSUE THREAD

**Issue by alamboley** [playcanvas/editor#416]
Hello,

When trying to create a ParticleSystem in editor, I've this issue:
![image](https://user-images.githubusercontent.com/687978/121560549-ecc00d80-ca17-11eb-8ac6-6f970593e615.png)

Javascript console:
```
Powered by PlayCanvas 1.42.0 d57e59d instrument.ts:129:35
messenger connected instrument.ts:129:35
WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization. 2
Error: invalid:exception: Invalid path for: .components.particlesystem.renderAsset
```

**Comment by yaustar** [comment]
Thanks, we are looking at this now

**Comment by yaustar** [comment]
We have fixed this now, please refresh the editor and try again

**Comment by alamboley** [comment]
Perfect, thanks!
