### ISSUE TITLE
Particle System editor missing screenSpace flag

### ISSUE THREAD

**Issue by Sarletor** [playcanvas/editor#421]
Particle System editor missing screenSpace flag
![image](https://user-images.githubusercontent.com/37019196/122898733-c8d3c480-d353-11eb-970c-05c8a6d605fd.png)

https://developer.playcanvas.com/en/api/pc.ParticleSystemComponent.html#screenSpace

**Comment by mvaligursky** [comment]
this has been implemented, but not released .. the relevant flag is 'hasUIParticles'

**Comment by yaustar** [comment]
This is on Production Editor now
