### ISSUE TITLE
Editor broken in Edge

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#43]
Throws exception on this line:
```
        constructor({ customUpdate, ...args } = {}) {
```
Outputs:
```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

**Comment by halvves** [comment]
Hey @willeastcott. What version of Edge is this in?

**Comment by willeastcott** [comment]
![image](https://user-images.githubusercontent.com/697563/78813319-c0989f00-79c4-11ea-8afb-fee7be409b63.png)

**Comment by willeastcott** [comment]
It's either a problem with the spread operator or default arguments, I guess.

**Comment by mvaligursky** [comment]
I have latest Chromium based Edge, and Editor loads fine on these two versions I had:
Version 80.0.361.111 (Official build) (64-bit)
Version 81.0.416.58 (Official build) (64-bit)

It seems version 44.XXX is not Chromium based, and that's what's having a problem.

**Comment by mvaligursky** [comment]
please update your Edge browser to latest Chromium based version.
