### ISSUE TITLE
Multiselect, then deselect - doesn't deselects in hierarchy.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#44]
### Steps to Reproduce

1. Create new project
2. Select multiple entities
3. Select any entity or deselect by clicking in viewport (not hierarchy)
3b. Or select anything in assets panel, deselection will not be reflected in hierarchy

### Issue

Selection change, is not reflected properly in hierarchy. It simply deselects single entity (last one that was selected), instead of all of them.

**Comment by vkalpias** [comment]
Yeah this looks like it's because when calling `selector:clear` that instantly clears the internal array so subsequent selector:remove events set the selector type to null because the internal array length is 0. Will figure something out.

**Comment by vkalpias** [comment]
This should now be fixed.
