### ISSUE TITLE
Bug with highlighting the code with string interpolation and template literals

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/editor#443]
![image](https://user-images.githubusercontent.com/10512039/123769245-c0d6d000-d8d1-11eb-90f9-e558e9ed655b.png)

### Steps to Reproduce
Simply copy/paste this code into the code-editor: 

```
const PROGRESS_NAMES = Object.freeze({
    watering: (name) => `Watering ${name}`,
    fishing: () => `Fishing`,
    place_new_item: (name) => `Placing new item ${name}`,
    place_unique_in_friends_garden: (name) => `Placing new item ${name} in friends garden`
});
```

**Comment by willeastcott** [comment]
It seems this is no longer an issue:

![image](https://github.com/playcanvas/editor/assets/697563/b5674c4c-f049-40ca-bc6b-4603e1f24465)

Closing...
