### ISSUE TITLE
Can we make listing checkpoints in version control faster?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#448]
In some cases, the listing/retrieving checkpoints can be slow when opening version, especially with large projects.

Could we make this faster or identify the bottleneck(s)?

**Comment by yaustar** [comment]
What would be great as well is if we can 'cache' checkpoints that we already gotten from the server. This would allow us to more easily/quickly go back and forth between branches.


https://user-images.githubusercontent.com/16639049/124500134-21c14500-ddb7-11eb-8f30-66925f31ec59.mp4

**Comment by Maksims** [comment]
Even this amount of data should be returned very quickly, make sure there are all necessary indices are in place in db.

**Comment by yaustar** [comment]
Improvements released with https://github.com/playcanvas/editor/releases/tag/v1.18.21
