### ISSUE TITLE
Editor Suggestions Not Appearing

### ISSUE THREAD

**Issue by renegadels** [playcanvas/editor#45]
Recently, all the suggestions do not appear when part of a keyword is typed into the code editor. Forum link - https://forum.playcanvas.com/t/editor-suggestions/12644

![image](https://user-images.githubusercontent.com/58387535/79066486-d7e1d000-7cd5-11ea-957b-2e931e9fdb37.png)
Example - In this image, findByName does not appear as a suggestion.

**Comment by vkalpias** [comment]
This should now be fixed.
