### ISSUE TITLE
Shadow appears/disappears on mouse over

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#459]
At certain zoom levels, the shadow appears/disappears when the mouse is over the 3D viewport. @mvaligursky says it is related to the picker.

https://user-images.githubusercontent.com/16639049/125606895-a627d09c-1af9-4601-941b-a472e54f03c9.mp4

**Comment by willeastcott** [comment]
Yes - I noticed this two days ago. Feels like 'new' behavior so presumably tied to a recent engine update.

**Comment by mvaligursky** [comment]
We had this issue in some form for a long time, but we should fix it.

Related issues:
https://github.com/playcanvas/editor/issues/268
https://github.com/playcanvas/editor/issues/337
