### ISSUE TITLE
Change only visible after browser refresh

### ISSUE THREAD

**Issue by Alb3rt1990** [playcanvas/editor#46]
### Description
If I add an entity with an element and I make an adjustment in the element, this adjustment is only visible after I refresh the browser. I experience that with several things.

### Steps to Reproduce
1. Create a entity and add a image element
2. Image not visible until you refresh the browser
3. Change the opacity of the image element
4. Change not visible until you refresh the browser

**Comment by willeastcott** [comment]
Already logged against the engine here: https://github.com/playcanvas/engine/issues/1985
