### ISSUE TITLE
Be able to select older engine versions in the Editor and Launch tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#467]
Request to make this an easy to use drop down in the Editor: https://forum.playcanvas.com/t/engine-release-v1-45-0/21142/18?u=yaustar

Given the quick likes to the forum post, it is something that many users will appreciate.

**Comment by slimbuck** [comment]
@yaustar this can be closed now?

**Comment by yaustar** [comment]
As a team, we agreed that supporting older engine versions for the Editor could cause issues if the Editor is dependent on engine features
