### ISSUE TITLE
Editor Viewport rendering/lighting differently to runtime

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#472]
Example projects:
https://playcanvas.com/project/437633/overview/changing-scenes

![image](https://user-images.githubusercontent.com/16639049/126639856-daf3a98a-dadc-4694-961a-ef7e1a85512a.png)

![image](https://user-images.githubusercontent.com/16639049/126639879-ffd05f0c-3967-4eb7-899a-56e196190b6e.png)

https://playcanvas.com/project/438429/overview/camera-following-a-path
![image](https://user-images.githubusercontent.com/16639049/126639967-815f91d4-c835-434d-9f35-419843dc01a2.png)
![image](https://user-images.githubusercontent.com/16639049/126639981-602cca2f-db91-4d80-bbfc-776561c35081.png)

**Comment by willeastcott** [comment]
I can't repro this:

![image](https://user-images.githubusercontent.com/697563/199686835-b37f17fe-fbe8-4f94-98c9-3c1e691562b7.png)

Is this now resolved, @yaustar?

**Comment by yaustar** [comment]
Looks like it, I can't remember how this was solved, it was an editor release or something :thinking
