### ISSUE TITLE
Be able to preview animations in the viewport

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#473]
The old animation component allowed users to play animations from the component in the viewport 

![image](https://user-images.githubusercontent.com/16639049/126651834-9509492e-f7aa-4d6c-ab48-ee29054b6ca2.png)

Could we add something like this in the animation - state mapping of the anim component? That would help a lot :)

Similar to: https://github.com/playcanvas/editor/issues/437

**Comment by yaustar** [comment]
Had a chat with @ellthompson, it's a bit more difficult than we would have liked because it would require changing the the entity's transforms in the hierarchy and setting it back to a 'default' state could be tricky.

We would instead think about adding a previewer in the inspector for the animation asset and that could open up extra features such as timeline controls without cluttering the entity inspector.

**Comment by Maksims** [comment]
Well, hierarchy in viewport is independent from hierarchy data in Editor.

**Comment by yaustar** [comment]
Closing this in favour of https://github.com/playcanvas/editor/issues/437
