### ISSUE TITLE
Mouse hover assets, display full name?

### ISSUE THREAD

**Issue by alamboley** [playcanvas/editor#475]
Hello,

In my project I've many sprites and fonts, most of them share in part the same name:
- SourceSansPro-Black.ttf
- SourceSansPro-BoldItalic.ttf
- btn-blue-big.png
- btn-blue-pale.png
- btn-blue.png

I use mostly grid view (small) for my assets. On an entity, when selecting a font/texture/material/sprite for linking with assets it would be nice that a title (like html title) appears on long name.

**Comment by yaustar** [comment]
Fixed via 1.20.0 release. 

https://user-images.githubusercontent.com/16639049/141805798-2ac344ba-b751-4bf0-8ee1-018eef47dd3e.mp4
