### ISSUE TITLE
Entity property values not always being brought over during merge

### ISSUE THREAD

**Issue by mikestonecodes** [playcanvas/editor#482]
make master branch with test script with attributes
make test branch 

make a bunch of changes in master branch , and different checkpoints, adding / removing attributes of script
make a bunch of changes to test branch and change order, amount of attributes

merge changes from master branch into test branch

entity property values that are same property name from master branch not copying over to test branch

https://playcanvas.com/project/817658

**Comment by yaustar** [comment]
Where there conflicts when you merged? It's possible that values were lost in the conflict. Here's an attempt at a repro below.

There was an attribute conflict on dfdfd2 where it was a string in the branch and a boolean in master so the value set was lost.


https://user-images.githubusercontent.com/16639049/127868454-4a84a07b-71ac-466c-bcb1-84a1587a3554.mp4

**Comment by mikestonecodes** [comment]
No conflicts

**Comment by yaustar** [comment]
@mikestonecodes Can I add myself to your project and attempt to do the merge myself and look at the state of the branches?

**Comment by mikestonecodes** [comment]
yes

**Comment by yaustar** [comment]
Thanks! I've had a look at the version control graph from the project and it looks to how I would expect. No attributes seemed to have been lost.

Can you look over the diagram and let me know if something looks unexpected or wrong please?
![image](https://user-images.githubusercontent.com/16639049/127872538-3ee2c8f5-cce0-4b5d-ae69-a3044c832fee.png)

**Comment by zachpeterpaul** [comment]
Please make sure you parse the script and create a checkpoint after parsing in both branches before the merge. Until you parse your new version of a script may be inconsistent with the old attribute value stored in the scene document, or the old parsed type. You may need to parse after merge again in some cases, because a merge doesn’t trigger a parse automatically. Internally attributes are represented in 3 different places (js, script asset doc (type), scene (value)), so only a new parse can synchronize them.

**Comment by mikestonecodes** [comment]
@zachpeterpaul I just merged my test branch after parsing both. The param "port" on Root-Box should say "good" but it doesn't. I tested twice.

**Comment by zachpeterpaul** [comment]
Can you paste the branch names and the checkpoint ids that you merged? Also please note that when you merge the same branches for a second time after a restore , your second merge is affected by the first. Can I add myself to your project?

**Comment by mikestonecodes** [comment]
yes its a test project with no data

**Comment by mikestonecodes** [comment]
branch name : master   / new branch test

master checkpoint : c136fe4  test branch test checkpoint : 2c9ca7c

**Comment by mikestonecodes** [comment]
I haven't used any restores

**Comment by mikestonecodes** [comment]
@yaustar I'm pretty sure where it says "1776448 merge with no changes", it should have changes.

**Comment by yaustar** [comment]
@mikestonecodes No changes according to version control.

No changes were made on master from the latest checkpoint (master 4ac1c13) at the time, so when master was merged to new branch test, no changes where applied.

![Kapture 2021-08-02 at 16 22 52](https://user-images.githubusercontent.com/16639049/127885487-65a52b2d-785e-476c-8586-ab43c4814284.gif)

**Comment by mikestonecodes** [comment]
@yaustar not sure how that graph works 100% , but the state of the port property  value was "bad", on master it was "good" so it should of changed to "good"

**Comment by mikestonecodes** [comment]
actually ideally, it would let me choose which one I want, instead of just saying "no changes"

**Comment by yaustar** [comment]
Version control (git, perforce, etc) doesn't work that way.

As the 'good' checkpoint (1776448) was used to branch 'new branch test', unless new checkpoints (commits) have been made on 'master', there's no new changes to be applied when merging 'master' to 'new branch test' as there are no new changes from the branch/last merge.

**Comment by yaustar** [comment]
Also looking at the checkpoints on 'new branch test', I can't see where in the scene, value of the port attribute was changed as it wasn't done in the 'ok' checkpoint 2ad578d

**Comment by mikestonecodes** [comment]
@yaustar  sorry I'm confused... this is really easy to recreate

1) go to master branch and make a checkpoint ,port and hash are set to "good" 
2) go to new branch test 
3) set the value of hash and port to random value
4) merge from master

no changes found

**Comment by mikestonecodes** [comment]
Also, if I just do this and open a new project, it works, but if I do it in the one I sent, it doesn't

**Comment by mikestonecodes** [comment]
I tried doing this same thing on github, maybe I am testing this wrong, but it always tries to resolve based on the current state of whatever commit you trying to merge into , not based on the  relative changes. I have to go in and resolve the conflict.

**Comment by zachpeterpaul** [comment]
You need to create a checkpoint in both branches before you merge. It merges the latest checkpoints, not the active state

**Comment by yaustar** [comment]
I've just tried this. I started by merging master to new branch test to get a 'clean' state of both branches and followed your steps above @mikestonecodes 

Does this look right to you?

https://user-images.githubusercontent.com/16639049/127892400-89bba049-e7cf-4d69-b546-c0bc47f88623.mp4

**Comment by mikestonecodes** [comment]
No, because the state of "hash" at that commit is "good" , but that doesn't get carried over

**Comment by mikestonecodes** [comment]
Here is new test that doesn't work 

go to master branch and make a checkpoint ,port and hash are set to "good"
go to new branch test
set the value of hash and port to random value
create checkpoint on new branch test
merge from master

**Comment by yaustar** [comment]
Still looks as expected to me where during the merge, I had the choice to choose whether I wanted new branch test changes or masters?

https://user-images.githubusercontent.com/16639049/127897530-40c6f2d0-9b49-4a5f-b6b8-803be9abdfea.mp4

**Comment by mikestonecodes** [comment]
No , you didn't follow my instructions and you changed the values on master to "good_good" instead of leaving it on "good" . I will try to get the master branch in a state where its history and the current state of the branch are not aligned again so you can see the problem.

**Comment by mikestonecodes** [comment]
here you go 

go to new branch test
set the value of hash and port to random value
create checkpoint on new branch test
merge from master

**Comment by mikestonecodes** [comment]
I didn't change the value since 2ad578d , almost first checkpoint

**Comment by yaustar** [comment]
As there are no new checkpoints on master from the last merge point since b0b785d on new branch test, when merging master to new branch test, no changes will be applied to new branch test because there hasn't been any changes on master.

This is as expected. Here's a clip on what GitHub does in the same scenario:

https://user-images.githubusercontent.com/16639049/127899357-068296be-2d99-49e5-9548-b0795e63d24b.mp4

**Comment by yaustar** [comment]
Going back to the original diagram:
![image](https://user-images.githubusercontent.com/16639049/127900381-fd1d97e3-beda-44fd-9622-73df990f17cd.png)

There seems to be an expectation because master has the value of 'good' in 4ac1c13, it would be applied when merging into new branch test.

This is not the case because this checkpoint was used to create the branch in the first place.

**Comment by mikestonecodes** [comment]
ok its marked as merged already thanks

**Comment by yaustar** [comment]
We are working on making this easier to understand such as a graph view and being able to track when changes have been made in a file.

**Comment by mikestonecodes** [comment]
@yaustar thank you

**Comment by yaustar** [comment]
That's very generous, thank you 🙏
