### ISSUE TITLE
Removing Render Component does not clear User Material references

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#484]
### Steps to Reproduce

1. Create a new entity
2. Add render component
3. Attach previously unused render asset
4. Attach previously unused material asset
5. Remove render component from the entity
6. Alternative way for the same issue: unset render asset (X on asset picker) while the material is used

### Issue:

The material still has "used" state, and the context menu has a Reference to the previously used entities.

### Solution:

Ensure unused index is updated when removing render component for materials.

**Comment by yaustar** [comment]
Fixed in v1.19.9
