### ISSUE TITLE
When clicking on "+ parameter" in Anim State Graph, the panel Parameter should expand

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#487]
We probably do this in a few other places where there's an action on the top of the panel (eg layers in the same image below) and it's not clear that the panel has been collapsed

![image](https://user-images.githubusercontent.com/16639049/128679690-addcd514-e016-4109-9549-b6c95fef8463.png)

**Comment by ellthompson** [comment]
This has been released to prod.
