### ISSUE TITLE
Entity with Element Component and Script Component, should not render Scripts Icon

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#49]
### Description

Entity with Element Component and Script Component will render Element mesh as well as Script icon in viewport.
It should only render Element, like with every other component that is rendered.

**Not good:**
![image](https://user-images.githubusercontent.com/636263/79140272-629ef980-7dc0-11ea-8ff2-c51cd1240e57.png)

**Good:**
![image](https://user-images.githubusercontent.com/636263/79140317-76e2f680-7dc0-11ea-86f4-b36c0b16ce11.png)

**Comment by ellt92** [comment]
Hi @Maksims, thanks for posting this! I've just released it to prod.
