### ISSUE TITLE
VSCode Extension that works in place of the online Code Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#497]
Similar to playcanvas-sync but much easier to setup (maybe via a URL link in the Editor that opens VS Code directly?)

**Comment by briancullinan** [comment]
+1

I love this idea. Maybe priority could be given to compatibility with 
https://john-millikin.com/extending-vscode-with-webassembly

i.e. https://vscode.dev/

and only the layout engine / code editor / language server web-worker features are appreciated here.

**Comment by willeastcott** [comment]
Done:

https://github.com/playcanvas/vscode-extension
