### ISSUE TITLE
Pressing F2 no longer highlights the name field of the selected object

### ISSUE THREAD

**Issue by RipcordDev** [playcanvas/editor#5]
### Description

Using PlayCanvas editor in Chrome v79.  Pressing F2 on the keyboard no longer highlights the name field of the selected object.  This was working fine until a couple of weeks ago.  I believe this corresponds to an update to the editor.

### Steps to Reproduce

1. Open PlayCanvas editor in browser
2. Select any object
3. Press F2 on keyboard

Result:
Nothing happens.

Expected:
Name field of selected object becomes highlighted for editing.

**Comment by willeastcott** [comment]
We have deployed a fix for this. Try it out! 😄 If you still find any problems relating to this, please re-open the issue. Thanks!
