### ISSUE TITLE
Dragging the same material that it has already to a mesh in the viewport makes it white

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#502]
Could be an engine issue?

https://user-images.githubusercontent.com/16639049/129346818-1449c181-6958-4871-b2cb-a468d4517ec8.mp4

**Comment by vkalpias** [comment]
Cannot reproduce this one can you check again?

**Comment by yaustar** [comment]
Cannot reproduce. Maybe fixed with the last release? Closing
