### ISSUE TITLE
CSS changes for iOS 14 and 15

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#506]
# Current Issues with iOS 14
- [ ] Window is not filled in landscape

~~# Potential Issues with iOS 15~~
~~- [ ] Canvas is resized when navbar is hidden/shown~~
~~- [ ] Every touch on the page shows/hides the navbar~~
 
# Extra proposed changes
- [ ] Fix Samsung browser canvas stretch (https://github.com/playcanvas/engine/issues/2386)

For the PlayCanvas team, please see internal doc

**Comment by yaustar** [comment]
Testing plan:
- [ ] Test on Safari 14 with one tab (landscape -> portrait -> landscape -> portrait)
- [ ] Test on Safari 15 with one tab (landscape -> portrait -> landscape -> portrait)
- [ ] Test on Safari 14 with two tabs (landscape -> portrait -> landscape -> portrait)
- [ ] Test on Safari 15 with two tabs (landscape -> portrait -> landscape -> portrait)

- [ ] Test on iOS Chrome with one tab (landscape -> portrait -> landscape -> portrait)
- [ ] Test on iOS Chrome with two tabs (landscape -> portrait -> landscape -> portrait)

**Comment by yaustar** [comment]
Early test for iOS 14 fixes: https://yaustar.github.io/ios14test/

**Comment by willeastcott** [comment]
Note that enabling `viewport-cover` for iOS makes safe areas an issue with PlayCanvas apps. So, some questions:

* Should this be an option that is togglable by the developer?
* When `viewport-cover` is enabled, what's the mechanism to query the safe area to correctly position UI (whether it's DOM based or element component based)?

**Comment by yaustar** [comment]
We could make it an option in the project settings for the Editor. @vkalpias mentioned that perhaps we should do this.

To query the safe seems to be CSS based or it can be assumed on displays with certain aspect ratios (very tall or very wide displays) https://developer.mozilla.org/en-US/docs/Web/CSS/env()

**Comment by willeastcott** [comment]
We'll probably want to have documentation covering safe areas to accompany this change (particularly for the element component scenario).

**Comment by yaustar** [comment]
> We'll probably want to have documentation covering safe areas to accompany this change (particularly for the element component scenario).

Added a published build (with the viewport=cover) and safe areas: https://playcanv.as/e/b/YkURYjjt/

Project: https://playcanvas.com/project/828118/overview/mobile-ui-safe-areas

Will look to add this to the user manual

**Comment by yaustar** [comment]
@willeastcott Added documentation here: https://github.com/playcanvas/developer.playcanvas.com/pull/297

**Comment by yaustar** [comment]
Fixed in v1.19.9
