### ISSUE TITLE
It's possible to move around in the anim state graph of someone else's project

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#509]
### Description
It's possible to move around in the _anim state graph_ of someone else's project. 
By this I mean moving _states_ and _transitions_ of the _anim state graph_ while you are not a member of the team.

### Steps to Reproduce
1.  Go to the _anim state graph_ of a random project.
2.  Click and drag a _state_ or _transition_.

**Comment by yaustar** [comment]
Looking at this, while I can move it around, it resets itself back to the original position which I think is fine as you aren't modifying the project.

As a side effect, it can be useful if trying to work out where the arrows are going as they can overlap a bit:


https://user-images.githubusercontent.com/16639049/129959271-b0080d9f-bf12-413b-9f2b-b304379beb63.mp4

**Comment by albertvanveen** [comment]
I see. I didn't release that mouse button because I didn't want to change someone else's project without permission.
