### ISSUE TITLE
Editor option for default asset preload setting

### ISSUE THREAD

**Issue by szevvy** [playcanvas/editor#51]
By default, preload is enable for assets when they are created.  We would love for there to exist an editor option that changes the default to be off.  This will help reveal issues that our titles have when assets aren't being preloaded early.

Thanks!

**Comment by ellt92** [comment]
Hi @szevvy. Thanks for posting this, i've just released this to prod. You can now find the option under asset tasks in the settings panel: 
![image](https://user-images.githubusercontent.com/1721533/81012230-1d1a9d00-8e51-11ea-94c7-d35d1eddc148.png)
