### ISSUE TITLE
Fog editor toggle issues.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#518]
Fog preview is not working for a selected scene camera in corner preview:

![image](https://user-images.githubusercontent.com/636263/131371849-5c550281-4010-4e50-b99f-2830ea5083ca.png)

Also, by default, when toggling fog for - nothing happens. Because default setting for a fog - is disabled. Also, it disables it for scene cameras, which is even worse. So for the user, it might appear as for is not working.
By default it should not be disabled otherwise it appears that fog does not work for the user when toggling it.
It should remember setting for fog toggle per cameras: perspective, top, left, etc. And by default disable for only for axes cameras, but not for perspective one.
Also, toggle should be close to fog settings, otherwise unless known - no way newcomers will figure out to read every setting in other tabs to find relevant toggle.

syau: Moved below feature request to: https://github.com/playcanvas/editor/issues/519

> Additionally, it would be great to add it to viewport toggles, as an easy shortcut:
> ![image](https://user-images.githubusercontent.com/636263/131372146-9424cd1e-8b13-442c-b135-ea50514cb808.png)

**Comment by yaustar** [comment]
Found the issue with the camera preview. PR in progress.

**Comment by yaustar** [comment]
Fixed released
