### ISSUE TITLE
Add a folder refresh button

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#521]
Sometimes when you delete a folder or an asset, the Asset panel still shows it, as if it wasn't deleted. The console doesn't have any errors, except a bunch (80+) of same warnings: `Elements will not get any input events because this.system.app.elementInput is not created`, that are most probably not related.

If you refresh the window, the Asset panel correctly shows the remaining folders/assets with the previous one removed. This is probalby a bug, or some network dragons. Can we have a folder refresh button for such and similar cases? That would be faster than refreshing the whole project.

![image](https://user-images.githubusercontent.com/5677782/131663295-0b471696-e32c-40bc-b655-3ea919c78baf.png)

**Comment by Maksims** [comment]
We should avoid adding refresh button in this case, and ensure removed asset is deleted accordingly.

Refreshing Editor - is a workaround, but reasons for it should be eliminated.

**Comment by LeXXik** [comment]
I will make a separate issue for the bug then.

**Comment by yaustar** [comment]
> Sometimes when you delete a folder or an asset, the Asset panel still shows it, as if it wasn't deleted. The console doesn't have any errors, except a bunch (80+) of same warnings: `Elements will not get any input events because this.system.app.elementInput is not created`, that are most probably not related.

Sounds like this issue? https://github.com/playcanvas/editor/issues/479

**Comment by yaustar** [comment]
#479 was fixed in a recent editor release. Closing for now
