### ISSUE TITLE
Expose Ambient Occlusion and Soft Shadow baking in the Editor

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#523]
API on a LightComponent and a Scene from this PR should be exposed in the Editor
https://github.com/playcanvas/engine/pull/2838

**Comment by mvaligursky** [comment]
This has been done and released I believe, @yaustar ?

**Comment by yaustar** [comment]
Yes 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/16639049/185082005-23ec8d15-5e73-49ec-8ff0-3c3556634d8f.png">
