### ISSUE TITLE
Broken game links: Blast Arena io and Mini Royale 1

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#525]
On https://playcanvas.com/explore, Blast Arena and Miniroyale.io are dead links.

Forum: https://forum.playcanvas.com/t/some-invalid-website-links/21700

**Comment by Maksims** [comment]
Miniroyale is moved to https://miniroyale2.io/ and is growing and actively developed project.

**Comment by willeastcott** [comment]
Fixed (deployment should happen this week sometime).

**Comment by RandomPandaStudios** [comment]
If I may say so, I think this post is still relevant to the issue topic:
https://forum.playcanvas.com/t/solved-some-invalid-website-links/21700/5
