### ISSUE TITLE
Add Fold All and Fold options and hotkey shortcuts to the Code Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#526]
Forum: https://forum.playcanvas.com/t/code-folding-shortcut/21758

Current options
![image](https://user-images.githubusercontent.com/16639049/132194456-f2b43ff4-b3d5-4734-adad-465743a58052.png)

**Comment by willeastcott** [comment]
Fold All is available in the Command Palette.

![fold](https://github.com/playcanvas/editor/assets/697563/6bd06d01-240d-4982-9451-3ea39a79888d)

Closing.
