### ISSUE TITLE
Diff of source file doesn't have the red/green sections aligned with the lines

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#53]
### Description

![image](https://user-images.githubusercontent.com/16639049/79617347-27bdfe00-80ff-11ea-8bec-13a7839bc421.png)

**Comment by vkalpias** [comment]
This seems to happen when you have changed your font size in the code editor preferences. Can you verify?

**Comment by yaustar** [comment]
Yes, that looks about right. Default is 12pt right? I had it at 14pt. Changing back to 12pt fixes this issue.

**Comment by yaustar** [comment]
Could we temp fix this by forcing the diff viewer to us the default height? Or do you think it be better to fix it properly and use the user's preference of font height?

**Comment by vkalpias** [comment]
I think we should fix this properly should not be too hard to update the positions based on the font size.

**Comment by yaustar** [comment]
In PR

**Comment by yaustar** [comment]
Deployed
