### ISSUE TITLE
Add cherry-picking to version control

### ISSUE THREAD

**Issue by ki11roy** [playcanvas/editor#534]
It would be nice to have a cherry-picking feature, similar to git one, to merge changeset from "theirs" branch into "ours" (current) as a separate commit.
![image](https://user-images.githubusercontent.com/1812070/132373003-fea224b0-3abb-48d8-9190-b465f1929da9.png)

**Comment by yaustar** [comment]
Closed as duplicate of https://github.com/playcanvas/editor/issues/492
