### ISSUE TITLE
UV channels are lost when importing FBX file

### ISSUE THREAD

**Issue by heretique** [playcanvas/editor#536]
Environment: Windows 10, Firefox 92

### Description

When importing the attached FBX file (exported from Blender) only two UV channels are available on all the meshes inside the generated GLB file in PlayCanvas (one of them should have 4).
I've also attached the generated GLB file from PlayCanvas and also another one exported from Blender.
[test bug multiUVs.zip](https://github.com/playcanvas/editor/files/7128453/test.bug.multiUVs.zip)

**Comment by willeastcott** [comment]
The glTF 2.0 spec only supports up to 2 sets of texture coordinates:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes

I'm not sure we can do anything about this beyond document the limitation better.

**Comment by heretique** [comment]
It is not really clear for me that the specs specifically says that only two sets of texture coordinates are allowed, I haven't seen that anywhere, instead this 
```
Client implementations must support at least two UV texture coordinate sets, one vertex color, and one joints/weights set. Extensions can add additional property names, accessor types, and/or accessor component types.
All indices for indexed attribute semantics must start with 0 and be continuous positive integers: TEXCOORD_0, TEXCOORD_1, etc.
```
makes me think that two are the minimum required but you can have more
Since Blender exports more than two UV channels and viewers like https://gltf-viewer.donmccurdy.com/ can read those I assume the spec allows it or it is flexible enough for this.

**Comment by willeastcott** [comment]
Yeah, good point. I'll defer to @mvaligursky on this.

**Comment by mvaligursky** [comment]
relevant forum discussion
https://forum.playcanvas.com/t/support-for-multiple-uv-channels/21807

**Comment by heretique** [comment]
If it helps you could export the model as .gltf so that the json could be inspected as I attached the .blend file as well.

**Comment by mvaligursky** [comment]
We have a fix to this thanks to @slimbuck and it should be deployed within next week. Thanks for the report and the repro @heretique ! Here's the created glb file based on your repro, and it contains 4 uv sets now:

```
      "primitives": [
        {
          "mode": 4,
          "attributes": {
            "NORMAL": 1,
            "POSITION": 0,
            "TEXCOORD_0": 2,
            "TEXCOORD_1": 3,
            "TEXCOORD_2": 4,
            "TEXCOORD_3": 5
          },
          "indices": 10
        }
      ]
```

[test bug multiUVs_glb.zip](https://github.com/playcanvas/editor/files/7142927/test.bug.multiUVs_glb.zip)

**Comment by heretique** [comment]
Wow, that was really fast guys, kudos and thank you.

**Comment by willeastcott** [comment]
I believe the fix is now deployed. 

https://github.com/playcanvas/editor/releases/tag/v1.19.11

Closing.
