### ISSUE TITLE
Read-only projects, Publish button is visible.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#54]
On read-only projects "Publish" button is visible, and even clickable. Of course it does not publish, but should be hidden if user does not have write/admin access.

![image](https://user-images.githubusercontent.com/636263/80140752-179b9800-85b1-11ea-9dd2-620ecfd8a0c8.png)

**Comment by yaustar** [comment]
In PR

**Comment by yaustar** [comment]
Deployed
