### ISSUE TITLE
Editor fails to create new checkpoint - "Failed to create new checkpoint. Internal server error"

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/editor#543]
### Description

For the past week and a half or so, we have experienced a rather consistent issue where the first attempt at creating a checkpoint will fail, with the error message _"Failed to create new checkpoint. Internal server error"_.

![image](https://user-images.githubusercontent.com/5739868/133048911-a6854abc-f8f8-4318-8948-73d7e4106940.png)

Occasionally it will fail even after two or three attempts. It is also rather annoying the UI does not have go back button or reattempt checkpoint. One is forced to select a different branch, and go back, or reopen the version control window, meaning you always have to retype your commit message, if you didn't anticipate it to fail and copied your text beforehand.

### Steps to Reproduce

1. Do a commit
2. It fails
3. Repeat new checkpoint, and it may fail a couple of times more, before it succeeds.

**Comment by yaustar** [comment]
One possibility is that somehow another user is still making changes to the branch while the checkpoint is being made (in which case we should have a better error message and a retry button as you mentioned).

Would it be possible to have (email me if you need to) the project id and some branch ids with the checkpoint ids where it eventually succeeded please? I hoping our team can find something in the logs to a specific cause.

**Comment by h0lmiew** [comment]
I have experienced this issue even for branches where I have confirmed no other users have been active in at all.

The project ID is 670315 we have experienced it in several different branches including master. 

Today specifically I had the error several times in branch m_about_popup (4f929a4c-a33a-4884-9711-337f8b10a548). I also managed to get a checkpoint to work on the first attempt right now, so it apparently is not 100% the case that the first attempt fails - it has felt like that though previously.

**Comment by ki11roy** [comment]
We are having the same issue since yesterday. Project 803958.

**Comment by ki11roy** [comment]
Project build is also failed first time, maybe it is connected to this issue, branch id is: 71db86f2-5393-40c5-b2d9-7d48abe5982e

**Comment by mikestonecodes** [comment]
I have been getting this since sep 6. have to keep trying until it works.

**Comment by yaustar** [comment]
We have someone on the team looking at this.

For the short term, we will look at implementing the suggestions from @h0lmiew regarding retry button.

We believe the issue is that between the checkpoint request and the actual creation, the project state has changed (perhaps an asset task that is still running, some automated task via REST API or a change by another team member) but will do more investigation.

**Comment by ki11roy** [comment]
Some scripts from aws are not accessible, maybe it is connected somehow 
![image](https://user-images.githubusercontent.com/1812070/133300211-d6ba0790-1321-439d-9db3-e65f248f4474.png)

**Comment by yaustar** [comment]
> Some scripts from aws are not accessible, maybe it is connected somehow
> ![image](https://user-images.githubusercontent.com/1812070/133300211-d6ba0790-1321-439d-9db3-e65f248f4474.png)

Moved to new ticket

**Comment by h0lmiew** [comment]
Small update: We have been getting an error more frequently today when making a checkpoint (often needs more than 3 attempts to succeed), and the text now says _Consistency validation failed_.

![image](https://user-images.githubusercontent.com/5739868/133767844-9cf079d8-ff79-4202-8bb7-7afd95522ff6.png)

**Comment by yaustar** [comment]
The error message above confirms that the issue is what was mentioned earlier: https://github.com/playcanvas/editor/issues/543#issuecomment-919320094

The engineer is working on some changes to the messaging to show what has changed in the project between the request for the checkpoint and the checkpoint has been created.

In the meantime, I will try to get a retry button prioritised for this to at least make this a little less frustrating

**Comment by h0lmiew** [comment]
Thanks, and yea I figured the more specific error message was related to that post, but strange that we are seeing the error occur more now. 

I don't think we did any changes to our workflow, and we tend to almost always be one person per branch. Not sure what assets may still be doing something in the background if it is that which is causing it, because I have seen it even if only script changes have been done since the last checkpoints.

Could it be that the consistency check is doing something across project, beyond just individual branches?

**Comment by yaustar** [comment]
I have to leave that in the hands of @zachpeterpaul who is investigating this. The work that they are doing to show what the changes are should help in knowing more.

**Comment by yaustar** [comment]
We have pushed out an update that should reduce the failure rate. Please let us know if that helps

**Comment by h0lmiew** [comment]
Hi Steven, we have not experience this issue at all recently, so I would consider the issue fixed :)

**Comment by yaustar** [comment]
@h0lmiew Awesome to hear, thank you for reporting back!
