### ISSUE TITLE
Copy and paste particles doesn't update particle render (requires refresh)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#548]
Create two particle systems.
Make changes to one.
Copy particle system component 
Select other system
Paste particle system component
Particle system in the view port doesn't show correctly

https://user-images.githubusercontent.com/16639049/133263394-60506fa2-c7e2-4768-b2a3-15f403113b60.mp4

**Comment by yaustar** [comment]
Model components are also affected by this

**Comment by Maksims** [comment]
Would be good to replace the Settings Cog icon, with the simple 3 Dots `⋮` button commonly used in this context, as this is not a setting, but the additional menu.

**Comment by yaustar** [comment]
Fixed in v1.19.13
