### ISSUE TITLE
Basis WASM scripts from aws are not accessible from playcanv.as

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#550]
Some scripts from aws are not accessible, maybe it is connected somehow 
![image](https://user-images.githubusercontent.com/1812070/133300211-d6ba0790-1321-439d-9db3-e65f248f4474.png)

_Originally posted by @ki11roy in https://github.com/playcanvas/editor/issues/543#issuecomment-919332160_

**Comment by willeastcott** [comment]
Isn't that just because `MessagePack.min.js` has been uploaded to a PlayCanvas project and it externally references the map file `MessagePack.min.js.map`, which obviously won't be found?

**Comment by Asjpik** [comment]
@yaustar just sent the wrong screenshot. We have a problem with the publish function after adding a compression basis module.
![image](https://user-images.githubusercontent.com/18084046/133595020-79263d82-1460-44d2-8960-53fb68280142.png)

**Comment by yaustar** [comment]
Are you able to share/DM me a publish link of the build please to look at?

**Comment by Asjpik** [comment]
https://playcanv.as/b/TsrYOkD5/

**Comment by yaustar** [comment]
Thanks, we have managed to reproduce the issue 1 out of 5 ish reloads. Does that match with what you are getting as well?

**Comment by Asjpik** [comment]
So far, we haven't seen a pattern. But yes, sometimes we do manage to load normally. By disabling caching or using the Firefox browser. I'm not sure if this is useful information.

**Comment by mikestonecodes** [comment]
When this happens I've just been republishing and then it works on new link

**Comment by yaustar** [comment]
@mikestonecodes Just to check, this issue doesn't happen on the new builds/link?

**Comment by yaustar** [comment]
We are getting the error consistently with devtools in Chrome closed but cannot reproduce with devtools open. Is this the same for you?

**Comment by yaustar** [comment]
We found what is causing this issue and it appears to be some sort of race condition between the Basis WASM module being loaded by the `__modules__.js` script and the lazy loading method in the engine.

To fix this (and this is the recommend path) is to disable preload for all Basis related WASM files. This will mean that Basis WASM will be loaded by the engine on a background thread when the first Basis texture is loaded.

![image](https://user-images.githubusercontent.com/16639049/134177269-4f3798a6-f0c0-46bd-8b60-dacbce8c9ebe.png)

---
For the engine team: 

Error message: 
```
C7Y9afc9:1 Access to XMLHttpRequest at 'https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/C7Y9afc9/files/assets/55746861/1/basis.wasm.js' from origin 'https://playcanv.as' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The issue can be reproduced in this project: https://playcanvas.com/editor/scene/1235227 with this build: https://playcanv.as/b/C7Y9afc9/

A build with the preload ticked on the Basis WASM modules: https://playcanv.as/b/axW3X9Jk/

**Comment by yaustar** [comment]
If that's the case, should make it so that it's no longer an option to be preloaded?

**Comment by willeastcott** [comment]
I don't see any easy way to do that. But I'll defer to @slimbuck.
