### ISSUE TITLE
Not possible to disable legacy audio

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#56]
For very old project using the legacy `pc.AudioSourceComponent` (audiosource), you see this in the Settings Inspector:

![image](https://user-images.githubusercontent.com/697563/80550911-9598de00-89b9-11ea-95bf-601e8242e291.png)

There are a couple of things wrong here:

1. The AUDIO group appears above the Scene Name. These should be swapped.
2. More seriously, if you deselect 'Use Legacy Audio' and refresh the Editor, the option will be selected again.

**Comment by ellt92** [comment]
A fix for this is now out on prod!
