### ISSUE TITLE
Replace material asset feature is not replacing materials

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#565]
Thread: https://forum.playcanvas.com/t/urgent-replace-feature-isnt-working/22286
Repro: https://playcanvas.com/project/837707/overview/material-replace-feature

Video:

https://user-images.githubusercontent.com/16639049/136164536-8b5347b4-33b8-4a21-a136-bdb43f166d41.mp4

**Comment by yaustar** [comment]
This seems to be specific to the render component. Replace works fine with the model (legacy) component

**Comment by willeastcott** [comment]
A fix for this has now been deployed.
