### ISSUE TITLE
Editor/Launch tab crashes when opening - Clear cache temporary fixes this 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#566]
Thread: https://forum.playcanvas.com/t/playcanvas-crashing-when-starting-game/22275/

This has been seen by myself (once only so far), the forum users and some of our paid users too.

So far it has been reported on:

- Chrome only (including latest version)
- All platforms, Linux, Mac and Windows

It doesn't seem to be extension specific (my first thought as Spector.js but not all reported users have this installed)

**Comment by yaustar** [comment]
For me, it seem to be related to the WebGL context as sometimes only that crashes and I just don't get a viewport.

**Comment by Maksims** [comment]
Based on description from forum, he is referring to loading not appearing?
We did experience inconsistent loading times sometimes too. Where it loads in a snap, and sometimes it wont even start loading. Quick refresh fixes it. If waited long enough - will eventually load.

**Comment by yaustar** [comment]
In our cases, it either breaks the whole page 'aw snap' or kills the WebGL context. Not sure if the WebGL context being killed is related to my GPU specifically though

**Comment by yaustar** [comment]
> I have more experience with long loading times that can be inconsistent.

I've been getting that a bit too as well. Wonder if it's related now 🤔

**Comment by yaustar** [comment]
Video of the issue:

https://user-images.githubusercontent.com/16639049/136192651-4090e29a-ef18-42a3-9fa4-032ff233a1c7.mp4

**Comment by yaustar** [comment]
I had this happen again on my Mac with logging. 

Tried to launch with older version  of the engine (1.30.0) and it still doesn't load.

Trying to find something in the logs and the following lines look odd:

```
[29351:259:1006/123156.967277:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000502 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setStorage:1036.
[29351:259:1006/123211.809932:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000502 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setStorage:1036.
[29351:259:1006/123216.761764:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000502 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setStorage:1036.
```

**Comment by fotik333** [comment]
I have the same problem with latest version of Chrome on Windows 10, after pressing 'Play' editor window totally freezes.

**Comment by yaustar** [comment]
@fotik333 Do you have a WASM library in the project? Ammo or Basis?

**Comment by fotik333** [comment]
> @fotik333 Do you have a WASM library in the project? Ammo or Basis?

Yeah I have both.
I am using branches; if I create new branch from current, everything is OK on some time

**Comment by yaustar** [comment]
@fotik333 A temp workaround is to copy the launch tab URL and open it in a tab that has devtools open and Disable Cache ticked under the network tab.

I'm still getting to the point of a reliable repro and trying to narrow down the cause

**Comment by yaustar** [comment]
We believe it is WASM and cache related given what has been said in the thread

https://forum.playcanvas.com/t/playcanvas-crashing-when-starting-game/22275/33?u=yaustar
> Faced this again. After some digging, I noticed that the JS heap memory is not freed after refresh. A new tab just keeps asking for more.

**Comment by yaustar** [comment]
Submitted bug to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1257249

**Comment by yaustar** [comment]
This bug has been fixed by the Chrome team
