### ISSUE TITLE
Asset panel fails to remove multiple files

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#569]
When multiple assets follow some naming pattern, the Editor fails to remove them, if it is done via selection.

To repro:

1. Import Ammo library
2. Enter the imported folder and select all files in it
3. Press Del to remove the files and accept the prompt

Expected: all files are deleted
Actual: only single file is removed

**Comment by vkalpias** [comment]
Hi - I'm not able to reproduce this, maybe I'm doing something wrong? Could you maybe share a video?

**Comment by LeXXik** [comment]
Hi, @vkalpias ! Yeah, after testing a bit, there is one additional precondition - I did select one of the assets, before selecting them all. I do select with CTRL+A and remove with DEL.

https://user-images.githubusercontent.com/5677782/136658387-9649a6e6-9b12-44b8-9367-8f82aa5111e1.mp4
