### ISSUE TITLE
Error loading texture(s) in launch page

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#58]
It is a reasonably common occurrence to see the following error when loading a scene via the launch page:

![image](https://user-images.githubusercontent.com/697563/80584442-95c0ca00-8a09-11ea-9b1c-3dae89620d06.png)

Please leave a 👍 reaction on this issue if you've also seen this error message from time to time.

A browser refresh normally resolves it.

**Comment by highvrahos** [comment]
👍

**Comment by willeastcott** [comment]
I meant a reaction rather than a reply. Replies will spam watchers of the repo. 😄

**Comment by highvrahos** [comment]
[sorry couldn't resist 👍 😇  ]

Not much to add: while doing everyday Playcanvas dev the error will come up from time to time, but there are no repro steps. 

It seems completely random and yes a refresh with fix any issue.

**Comment by willeastcott** [comment]
I believe this issue has been resolved by work @yak32 did on the back-end. I haven't seen the error in many months. Closing.
