### ISSUE TITLE
Report a broken link.

### ISSUE THREAD

**Issue by yushimatenjin** [playcanvas/editor#581]
### Description
Report a broken link.
When I try to open the API reference, I get 400BAD REQUEST.

### Steps to Reproduce
1.  Hover over the properties of a component.
2. Click the API Reference.
3. 400 Bad Request (link:https://developer.playcanvas.com/api/pc.CameraComponent.html#clearDepthBuffer)
<img src="https://user-images.githubusercontent.com/39250588/137424094-bff7ba93-9cc0-48b9-954c-634f675d4f4e.png" width="400px">
<img src="https://user-images.githubusercontent.com/39250588/137424158-d601cd3e-ced4-4583-b20e-9d788875bfb7.png" width="400px">

**Comment by yak32** [comment]
i am deploying the fix today.

**Comment by yak32** [comment]
the issue is fixed, closing the issue.

**Comment by yushimatenjin** [comment]
Thank you !
