### ISSUE TITLE
Code editor adds a large number of tabs when you write a new line

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/editor#582]
Code editor adds a large number of tabs when you write a new line.
Bug appears randomly in a random file, reloading page and cleaning cache does not help.
Bug can disappear after some time or appear in another file.

https://user-images.githubusercontent.com/41446646/137905299-68ca68eb-b73a-4c8f-b53c-a3ce777ff798.mp4

**Comment by yaustar** [comment]
Yeah, it looks like it is related to the `?` operator 🤔 

We should see what we can set to the Code Mirror config to avoid this

**Comment by yaustar** [comment]
We have been thinking about moving to Monaco instead. We have created the [playcanvas-sync](https://github.com/playcanvas/playcanvas-sync) to help with the 'surrender the IDEs' bit. 

It's still not as easy as setup as we would like though.

**Comment by Maksims** [comment]
Monaco - is great!

**Comment by yaustar** [comment]
We are now on Monaco so this shouldn't happen anymore :)
