### ISSUE TITLE
console.log in Editor - freezes the Editor

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#583]
### Steps to Reproduce:

1. Open Editor
2. Open Dev Tools > Console
3. Execute `console.log(pc);`

### Issue:
It freezes the Editor
The issue seems to be related to sentry, it tries to sanitize provided log data but falls somewhere in an infinite cycle.

**Comment by yak32** [comment]
the issue is fixed and merged, will be deployed with the next release of the editor
