### ISSUE TITLE
Asset contextmenu > delete - is not working

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#584]
### Steps to Reproduce:

1. Open Editor
2. Select entity, or deselect everything
3. Right-Click on asset for context menu
4. Click on "Delete" option

### Issue:
The asset does not get deleted.

It only happens when the selector type is not an asset.

It happens, because in `editor/assets/assets-context-menu.js`, it matches current selection against `currentAsset` (clicked by contextmenu). But when selector is empty, it does not take it in account.

### Solution:
If selector is empty, just delete `currentAsset`.

**Comment by vkalpias** [comment]
This should now be fixed.
