### ISSUE TITLE
To delete a folder on the sidebar of the assets panel requires selecting it twice

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#587]
Repro:

1. Create 2 folders
2. Select a folder that wasn't selected before in the side bar
3. Right click to open the context menu and select delete
4. The folder cannot be deleted
5. Left click on the same folder again in the side bar
6. Right click to open the context menu and select delete
7. The folder can be deleted

https://user-images.githubusercontent.com/16639049/138681330-5fe3116e-85d3-46d1-9399-7e7333fbbacd.mp4

**Comment by vkalpias** [comment]
This should now be fixed.
