### ISSUE TITLE
CTRL / CMD Key stuck down when changing tabs

### ISSUE THREAD

**Issue by benunbnd** [playcanvas/editor#59]
This is a super small issue but minorly annoys me on a daily basis. Basically if you have an entity selected in the hierarchy, then use CTRL + TAB to change tabs, and then return to the Editor tab by clicking on the tab, the CTRL key will stay in a ‘down’ state in editor. If you click on any other entities in the hierarchy it will multi-select those entities, making me have to press either CMD or CTRL to unstick the key.

This has been reported as an issue on Firefox and Chrome on Mac and Windows, as well as Edge.

**Comment by willeastcott** [comment]
I just tried to reproduce this but was unable to. Can you double check your steps to reproduce this and confirm that's all you need to do?

**Comment by benunbnd** [comment]
I can confirm this is no longer an issue on the latest version of the editor. 🥳
