### ISSUE TITLE
Rigidbody restitution description

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#590]
The current description of the rigidbody restitution property in Editor is misleading. It states that the property describes the amount of energy lost when 2 bodies collide with each other. Since this is a coefficient in 0-1 range, then it can be assumed, that setting it to 1 would make the object lose the most energy.

The restitution coefficient actually defines how much kinetic energy remains in object, after two bodies collide. Setting it to 1 would keep the most of the energy, making it bouncy.

**Comment by willeastcott** [comment]
I've updated this to:

```
Controls the amount of energy lost when two rigid bodies collide. The restitution of two colliding bodies are multiplied together and this value is then used to scale each body's velocity. You can informally think of restitution as a measure of how bouncy a body is.
```

It will be released with the next deployment.
