### ISSUE TITLE
Removing the environment map from a material doesn't remove it in the viewport

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#591]
1. Create a material
2. Add the material to a mesh in the scene
3. Add a cubemap to the material
4. See the cubemap effect in the viewport
5. Remove the cubemap from the material
6. The cubemap effect is still in the viewport
7. Requires a tab refresh to apply the change to the viewport

https://user-images.githubusercontent.com/16639049/140062474-66419d90-02b6-4cde-89aa-df3f0333388e.mp4

**Comment by willeastcott** [comment]
I can no longer reproduce this issue. @yaustar - do you want to retry reproducing this yourself or can I just close?

**Comment by yaustar** [comment]
Yep, CNR
