### ISSUE TITLE
Cubemap skybox loading is different in launch tab vs published build

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#593]
1. Add a skybox to the scene
2. Untick preload from the 6 individual faces
3. Load the launch tab. Note that the faces are being rendered here and that `pc.app.scene.skybox` is not null
4. Create a build and open it. Note that it is use prefiltered map and that `pc.app.scene.skybox` is null

Project: https://playcanvas.com/editor/scene/1265078
Launch tab: https://launch.playcanvas.com/1265078?debug=true
Build: https://playcanv.as/e/b/P1QCt6Mb/

I'm not sure if this is an Engine issue where loading the skybox at mip level 0 should invoke a load of the 6 faces or if the Editor needs to reflect the Engine behaviour.

**Comment by slimbuck** [comment]
What's happening in the build:
- Cubemap is preloaded (without faces) and prefiltered cubemap is used on the skydome
- Once loaded, this line https://github.com/playcanvas/engine/blob/dev/src/framework/application.js#L1622 flags faces for loading.
- Cubemap handler loads faces correctly, but
- Skybox is never rebuilt after faces are finished loading

In the case of launch page, `Application.setSkybox()` is being called before the cubemap is finished preloading and this happens to result in correct loading behavior.
