### ISSUE TITLE
Is there a bug in the 'Exclude'-certain-files function (in the editor's right side/below file settings)

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#597]
Hello there seem to be an issue with the (I guess quite) new 'Exclude'-certain-files function in the editor.

![image](https://user-images.githubusercontent.com/6838800/140603497-c9a9b82b-ceb0-4809-8359-05c8981198f4.png)

Within https://playcanvas.com/editor/scene/1243514 (that is my MP4-version for all-but-IOS version), I need to exclude all my .MOV video files.
And within https://playcanvas.com/editor/scene/1266913 (that is my MOV-version for all-other-platforms version), I need to exclude all my .MP4 video files.

Unfortunately, the exclude-settings seem to carry over, from scene to scene? (while all other settings can be 'auto-saved' from scene to scene, I read this as a bug)

**Comment by yaustar** [comment]
It's a project wide setting
