### ISSUE TITLE
Cannot open animation state graph after editing with latest editor release 

### ISSUE THREAD

**Issue by heretique** [playcanvas/editor#598]
Environment:
Windows 11, Firefox  94.0.1, Edge 5.0.1020.44
I assume Editor version is v1.19.35

After creating an animation state graph inside the PlayCanvas Editor and doing some editing, when I launched the game and I wanted to edit the state graph again, the launch/game window started flickering (some messy animation is displaying) and I cannot open that animation state graph anymore, even after restarting the browser.
Check the attached video for details.

https://user-images.githubusercontent.com/139596/140914391-e854559f-9b1a-4ac5-925b-669f4ca4107c.mp4

I'm also getting this in console when attempting to open the graph editor:

![image](https://user-images.githubusercontent.com/139596/140914843-faa99b76-2c4a-467c-9ff9-305b7ffbff63.png)

**Comment by yaustar** [comment]
Would it be possible to share the project for us to take a look at please?

**Comment by heretique** [comment]
I'm not sure, I'll have to ask around as it contains non-public company related work. If not possible to share I'll try to create a smaller project and try to repro there.

**Comment by yaustar** [comment]
If you removed all the models, animations, code etc and just leave the state graph, does it still not open?

You can also add `yaustar` to a private fork of the project if privacy is an issue?

**Comment by heretique** [comment]
I'm seeing very strange behavior with that state graph, like here's what's showing me in the inspector when I have it selected, after I removed all animations from it's states (it want's to open it in the viewer)

![image](https://user-images.githubusercontent.com/139596/140925127-e8020e2e-3387-4f23-a482-1ac637fc8e09.png)

After I reload the page in the browser it shows the proper "Open Graph Editor" button but it just doesn't work.

![image](https://user-images.githubusercontent.com/139596/140925505-fdc23a85-4947-4b5f-bae3-ec85d78acf8a.png)

Is there a way to download the state graph? Can it be copied to another project?

**Comment by yaustar** [comment]
> Is there a way to download the state graph? Can it be copied to another project?

You can select the asset, right click on the asset in the panel -> copy. Go to another project, right click in the asset panel -> paste

**Comment by heretique** [comment]
I created a repro project here https://playcanvas.com/project/849132/overview/repro-issue-598
It has only the state graph that I copied over from the other project. I cannot open the graph inside the new project either.

**Comment by yaustar** [comment]
Thanks, I pass this to @ellthompson to investigate

**Comment by yaustar** [comment]
Full callstack when trying to open the graph editor:
```
TypeError: Cannot read properties of undefined (reading 'name')
    at pcui-graph.js:42178
    at Array.forEach (<anonymous>)
    at pcui-graph.js:42175
    at Array.forEach (<anonymous>)
    at new GraphViewNode (pcui-graph.js:42160)
    at GraphView.addNode (pcui-graph.js:42977)
    at Graph.createNode (pcui-graph.js:44498)
    at pcui-graph.js:44171
    at Array.forEach (<anonymous>)
    at Graph._buildGraphFromData (pcui-graph.js:44151)
    at new Graph (pcui-graph.js:44113)
    at AnimstategraphView._createGraph (editor.js:78628)
    at AnimstategraphView.link (editor.js:78775)
    at AnimstategraphAssetInspector.openFullscreenMode (editor.js:80565)
    at AnimstategraphAssetInspector.link (editor.js:80638)
    at editor.js:77706
    at Array.forEach (<anonymous>)
    at AssetInspector.link (editor.js:77693)
    at Editor.<anonymous> (editor.js:90591)
    at Editor.Events.emit (observer.js:107)
    at Editor.<anonymous> (editor.js:60229)
    at Editor.Events.emit (observer.js:107)
    at Selection.<anonymous> (editor.js:29885)
    at Selection.Events.emit (observer.js:107)
    at api.js:3762
    at sentryWrapped (bundle.min.js:2)
```

**Comment by yaustar** [comment]
Second report from Discord: https://discord.com/channels/408617316415307776/408617316415307778/907616747786502155

**Comment by yaustar** [comment]
Another report: https://forum.playcanvas.com/t/animation-state-bug-on-editor/22788/2

**Comment by yaustar** [comment]
Fixed has just been deployed :)

**Comment by heretique** [comment]
I'd say this only fixes part of the problem, I can now open the graph editor but the issue with the animations being messed up when I open the graph editor or select one of the states still remains:

https://user-images.githubusercontent.com/139596/140980960-09bd294d-b187-4ac3-887f-e70dea542940.mp4

**Comment by yaustar** [comment]
Created a new ticket for this: https://github.com/playcanvas/editor/issues/599
