### ISSUE TITLE
Duplication of multiple entities in hierarchy does not select new entities correctly

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#60]
Test case: few entities in Scene View.

Correct case: Select single entity, and Duplicate it. Old entity is deselected and new entity is selected after duplication.
Incorrect case: Select two entities, and Duplicate them. Expected: Old entities should be deselected and new entities selected. Actual: Mix of old and new entities are selected.

Usually you want to duplicate selected, and have duplicates selected, so that you can group move them or similar.

**Comment by vkalpias** [comment]
This should now be fixed.
