### ISSUE TITLE
Import Hierarchy doesn't add RootNode to hierarchy

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#602]
Thread: https://forum.playcanvas.com/t/animation-errors-with-new-import-hierarchy-workflow/22820
Project: https://playcanvas.com/project/849912/overview/animation_test

When importing this model as a model asset, the hierarchy has an Entity named 'RootNode' added:
![image](https://user-images.githubusercontent.com/16639049/141344795-56977a42-f314-4040-a0ae-4e26dabaadf2.png)

However, as Import Hierarchy with render assets, this node is missing/not added
![image](https://user-images.githubusercontent.com/16639049/141344882-cab6da1a-c4f7-4b66-9178-e1ce545141d0.png)

The animation file has paths that uses the RootNode which leads to incorrect animation being played.

Example animation path
```
RootNode/Ausschalecke/Ausschalecke_Root/Ausschalecke_Ecke_4_Root/Ausschalecke_Ecke_4/Ausschalecke_Ecke_4_4/
```

**Comment by DarkKelt** [comment]
Good day, when I try import runtime glb like as binary, my glb  not have "RootNode" in skeleton, when I export, and I cant use old animations with binary-glb, it's affect new characters for miniroyale.

**Comment by yaustar** [comment]
@DarkKelt for the short term, can you use https://developer.playcanvas.com/api/pc.ContainerResource.html#instantiateModelEntity instead? Or does that have the same problem?

**Comment by yaustar** [comment]
@DarkKelt Just to also check, are the GLB binaries that you load at runtime, are they models only or animations as well? If you can share a project or the files, that would really help too

**Comment by DarkKelt** [comment]
> instead? Or does that have the same problem?

instantiateRenderEntity work good runtime. I check containers, after some actions i get correctly created model. When your importer FBX create glb model from source how i understood you change bone hierarchy and connections with vertexes. I check imported fbx and other glb from other source with hierarchy.

**Comment by DarkKelt** [comment]
> @DarkKelt Just to also check, are the GLB binaries that you load at runtime, are they models only or animations as well? If you can share a project or the files, that would really help too

When I import raw binary glb, it's not have "RootNode" and animation not worked corectly. That's why I asked Max about convertation pipeline.

**Comment by yaustar** [comment]
Another related forum post on this: https://forum.playcanvas.com/t/problems-with-anim-binder/26883
