### ISSUE TITLE
Code editor `i` is not rendered correctly in the file tabs

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#603]
There is a render error between 'i' and 'l' in the code editor tabs:
![image](https://user-images.githubusercontent.com/6838800/141675004-80e64270-91b7-4cd9-9995-15d6e369b0e6.png)

 - a bit annoying that I can't tell the difference between the i's and the l's in the tabs above, so I hope this will be fixed - obt

**Comment by yaustar** [comment]
Do you have either the browser page scaled or the display resolution scaled?

On Windows at 1:1 pixel size, it looks fine:

![image](https://user-images.githubusercontent.com/16639049/141684043-e151c115-69b8-4198-8dba-f37a0e05e75d.png)

**Comment by FutureFireplace** [comment]
classic :-s ... yes that was actually the problem (thought you/most-of-admins'n'devs were using other OS like linux or not-windows)
