### ISSUE TITLE
Code Editor Monaco: Variable names syntax colour to be different to function names

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#604]
Example of Code Mirror on the right where `data` variable is a different colour to other code like function names
<img width="2242" alt="Screenshot 2021-11-12 at 12 44 45" src="https://user-images.githubusercontent.com/16639049/141832212-574cb901-44b8-4f91-8769-9ac899bfa460.png">

**Comment by willeastcott** [comment]
I'm going to assume Vaios was correct and that this is not possible in Monaco. Closing.
