### ISSUE TITLE
Code Editor Monaco: when undoing editor will not scroll at changes

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/editor#606]
I'm fairly certain in the old code editor (code mirror) when undoing/redoing the editor would scroll and zoom at the line that got edited.

At least that's what I expected today when I tried this :)

If that wasn't the case, it might make a good feature request.

**Comment by yaustar** [comment]
Another report/request of this via the blog post

**Comment by Maksims** [comment]
It is common to edit something, then scroll around to read, then to get back do: undo, redo. And it will scroll yo that place. Very convenient.

Please add that feature back.

**Comment by willeastcott** [comment]
A fix just got merged for this. It'll go out with the next deploy to production which shouldn't be too long. 😄

**Comment by yaustar** [comment]
Released in 1.20.1
