### ISSUE TITLE
All generated GLBs are named model.glb

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#610]
With the new Import Hierarchy mode of model import, all GLBs generated from an FBX import are named `model.glb` on disk. In the Editor UI, they are named after the FBX. So, for example, if you import `avocado.fbx`, you get `avocado.glb` created in the Assets Panel. But if you run the Launch Page and open the Networking panel, you'll see the file that actually gets loaded is called `model.glb` instead of `avocado.glb`. This is different to the pre-Import Hierarchy behavior which generated a file on disk that matched the FBX name.

One of the reasons this is problematic is that it makes app optimization extremely hard. If an app loads 500 GLB files, if you open Dev Tools to see which GLBs could be optimized for size, or maybe removed from a project because they're actually unused, it's impossible to trace them back to the project. Or imagine downloading an exported and and unzipping it. There's no way to differentiate one GLB from another apart from explicitly viewing each one in the viewer.

To repro:

* Import an FBX (ensuring Import Hierarchy is enabled).
* Add the template to the scene.
* Run launch page and view the Networking panel to see the GLB is named `model.glb`.

**Comment by vkalpias** [comment]
Asset name will be used now instead of model.glb
