### ISSUE TITLE
Copy-pasting entity between branches stopped working

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#612]
One may no longer copy an entity from one branch and paste in another. Nothing happens. An entity can be empty. After a few seconds, console gives error:

![image](https://user-images.githubusercontent.com/5677782/142245281-da60257d-b257-41b2-8873-cf8c186aa547.png)

**Comment by yaustar** [comment]
Hmm, I can't reproduce in a simple project. Maybe it's specific to what is being copied and pasted?

**Comment by LeXXik** [comment]
Just checked, and it works in a new project. Hmm. In project 810527 we can't use copy-paste between branches, and I get the above error.

**Comment by yaustar** [comment]
Just coming back to this. @LeXXik would it be okay if I cloned the project to see if it happens in a fork? Or can I add myself to the project?

**Comment by LeXXik** [comment]
@yaustar yes, you can make a private clone or add yourself to the project.

**Comment by yaustar** [comment]
I've copied UI/Home entity from Scribble scene on branch master to the Scribble scene on branch syau without crashes or an issue.

**Comment by LeXXik** [comment]
@yaustar try to copy some entity from master to physics branch.

**Comment by yaustar** [comment]
Same entity UI/Home entity from Scribble scene on branch master to the physics branch was fine

**Comment by LeXXik** [comment]
Erm. It is now working... I am pretty sure it was not yesterday, as I checked again before answering you :) Not sure what fixed/changed it, but we can close this.
