### ISSUE TITLE
Missing materials on imported models.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#62]
Here is FBX file: [Door_In.zip](https://github.com/playcanvas/editor/files/4571426/Door_In.zip)
When importing it into assets panel, JSON or GLB, it will have some materials missing. And it is different ones every time. So seems like there is some racing condition in pipeline.
Either material is missing or it should be used on both mesh instances, but not set for some reason.

![image](https://user-images.githubusercontent.com/636263/80923341-c303d400-8d8b-11ea-895c-3ba05e6198e6.png)

**Comment by slimbuck** [comment]
Thanks for reporting this @Maksims and providing the sample file.

A fix is now deployed, please let me know if you see any more issues.
