### ISSUE TITLE
Code Editor with Monaco cannot be used with Chrome 76.0.3809.136

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#629]
Thread: https://forum.playcanvas.com/t/does-anyone-know-whats-wrong-with-my-code-editor/23119/

![image](https://user-images.githubusercontent.com/16639049/143961117-446fa468-6076-44d2-be87-9e9631446064.png)

Normally I wouldn't bug this.

Chromebooks have a lifespan on how long they can have updates for.

In this case, it had stopped after version 76.

There is an argument that we should try to support where we can, especially if education is a sector we want to expand on and since not every school can afford upgrades.

**Comment by willeastcott** [comment]
I'm going to make an executive decision here that we won't guarantee support for a browser that's from July 2019. It's so rare to find users that are on a locked version of Chrome. Closing.
