### ISSUE TITLE
GLB meta: number of vertices is wrong

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#63]
Number of vertices in Meta panel, of GLB files is wrong, and from observation it is multiplied by number of meshes.
Model for test: [Door_In.zip](https://github.com/playcanvas/editor/files/4571436/Door_In.zip)

Here is JSON (correct):
![image](https://user-images.githubusercontent.com/636263/80923402-3d345880-8d8c-11ea-93b6-8bdd0000de7e.png)

And GLB (incorrect):
![image](https://user-images.githubusercontent.com/636263/80923414-53421900-8d8c-11ea-8f3b-97fcb9c6b497.png)

**Comment by slimbuck** [comment]
Thanks for this @Maksims, fix is in the works.
