### ISSUE TITLE
Add model meta stats to render assets

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/editor#631]
The model asset includes a number of useful stats, namely vertices, triangles and attributes.

![image](https://user-images.githubusercontent.com/29543178/144199012-2fa906c5-9482-463f-ae09-4e108c1ed623.png)

The newer render asset doesn't include most of that info, it would be great to have it back in some way.

**Comment by willeastcott** [comment]
It seems to have it now!

![image](https://user-images.githubusercontent.com/697563/221357444-44a71c44-079a-4ee4-b8de-ded604745f73.png)

Closing. Please reopen if you feel I am incorrect here.
