### ISSUE TITLE
Fix syntax errors for ES6 async/await

### ISSUE THREAD

**Issue by johncpalmer** [playcanvas/editor#64]
Using async/await inside the PlayCanvas IDE causes red syntax errors that say 'missing semicolon.' However, this code apparently works and runs fine. It would be great to update the IDE to remove these errors.

Context: I’m trying to set up a PlayCanvas project that talks to a Nakama server for realtime multiplayer functionality. The Nakama Docs using async/await calls widely throughout. I know Nakama is used by Snapchat to power their multiplayer games, so I do think this is an important thing to consider.

**Comment by yaustar** [comment]
The red syntax errors is just the linting expecting ES5 JS code. They are more hints rather than actual errors. 

Reference: https://forum.playcanvas.com/t/using-async-await-inside-initialize/12977/4

**Comment by yushimatenjin** [comment]
How about a solution to update the version of JSHint?

It looks like JSHint is being used in PlayCanvas.

ES7, ES8 and ES9 are supported in JSHint 2.10.0 or later versions.
https://github.com/jshint/jshint/releases

The latest version is 2.12.0.

I was able to run the latest version of JSHint in my code editor.

1. delete the existing JSHint
```
window.JSHINT = null
```

2. copy the latest version of JSHint
jshint-2.12.0/dist/jshint.js
```
window.JSHINT = ....
```

3. change from esversion 6 to esversion 9 in the code editor

![スクリーンショット 2020-10-29 12 13 28](https://user-images.githubusercontent.com/39250588/97521289-99e19a80-19e0-11eb-9b19-b290c8f45754.png)

Now you can use async / await.


![スクリーンショット 2020-10-29 12 13 33](https://user-images.githubusercontent.com/39250588/97521285-9817d700-19e0-11eb-8548-85774685770e.png)

**Comment by PolVegaTPM** [comment]
I'm trying to reproduce the solution into my PlayCanvas project. I'm not getting what to do with the dots in `window.JSHINT = ....`. 

I have copied the full _jshint-2.12.0/dist/jshint.js_ file into a new .js file in my project. Then, in one initialise method I write `window.JSHINT = null`. But after that I don't know exactly how to make it work.

Can someone help? Thanks!

**Comment by PolVegaTPM** [comment]
Answered in: https://forum.playcanvas.com/t/using-async-await-inside-initialize/12977/11

**Comment by Maksims** [comment]
Would love to have JSHint updated for the Editor.

**Comment by yaustar** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/16639049/170091649-cd6c22a2-d364-4943-9112-3326b3e66253.png">

No longer an issue
