### ISSUE TITLE
When downloading textures, force the browser to download the image rather than open in new tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#642]
Either browser or Editor/Backend change has changed the behaviour for downloading textures where before, it used to download the image but now opens in a new tab.

https://user-images.githubusercontent.com/16639049/145805685-0eab3c71-199d-4279-8ba4-b55fd7be804f.mp4

Could we add a `download` attribute to the link to the image? https://stackoverflow.com/questions/2408146/href-image-link-download-on-click

**Comment by yak32** [comment]
resolved
