### ISSUE TITLE
In code editor, find in files only works if a tab is open

### ISSUE THREAD

**Issue by mikestonecodes** [playcanvas/editor#643]
to recreate
1) press control - i to open code editor
2) go to edit -> find in files
3) type something and press find

nothing happens

was confused why it wasn't working for a while :)

**Comment by vkalpias** [comment]
Hi, this is actually a decision we made early on because finding in files is executed on the client side and searching all files would actually have to open and download all of them. A more accurate description of the feature would be Find In Open Files.

**Comment by yaustar** [comment]
Fixed in v1.21.4
