### ISSUE TITLE
Exclude files from code editor

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/editor#644]
Is it somehow possible to exclude files/directories from the code editor?
I have 2000 JSON files in my projects and some commands take a too long time to execute.
For example, Go To File loads all the files so the code editor freezes for up to 10 seconds.
Or search in files searches in all the JSONs.

**Comment by yaustar** [comment]
I'm think of whether we should exclude these files or find some way to make Go to files a lot quicker. Even with 2000 strings, looking for a file of X name shouldn't take _that_ long 🤔
