### ISSUE TITLE
Able to drag png into Loading Screen Slot in settings

### ISSUE THREAD

**Issue by TheShoes** [playcanvas/editor#647]
![bug image](https://user-images.githubusercontent.com/7997186/147578675-d72883d6-2557-444f-bd1b-64cd0a1e24a7.JPG)

I am able to drag in a png into the loading screen script sport in settings.  
Not much more else to say besides that :).
let me know if you need me to create a repo but figured it was easy enough to reproduce that I did not need to.

**Comment by willeastcott** [comment]
A fix for this (that limits the asset type of that picker to scripts) has been merged and will be deployed shortly. Thanks so much for reporting. Closing...
