### ISSUE TITLE
Fast and precise mouse editing of float parameters in inspector

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#65]
Inspired by other editors, where you can mouse over a field descriptor in Inspector. At that point the mouse cursor changes to left-right arrow. When you mouse click at that point and move it left or right, the value of the field smoothly changes. Precision should be related to value of the field - for small values, increments should be small, for large values increments are large.

**Comment by Maksims** [comment]
Good idea.
Using Pointer Lock API probably, with some nice visuals.
Also with select elements, just like in Assets Panel on filters field, you can mousedown > select > mouseup. Would be nice to have in Inspector such feature too. Actually I believe it used to work that way.
