### ISSUE TITLE
Math in Inspector fields

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#66]
Many editors, especially CADs, support simple arithmetic in fields.
Often I want to **add** or **substract** some value, lets say move object by 4 units. Writing +4 to existing value in a field, would be very convenient way of doing it.

**Simple arithmetic could support:** addition, subtraction, multiplication, division, and scopes.

It should avoid using `eval`.

**Comment by ellthompson** [comment]
This feature is live on production now. Closing the issue.
