### ISSUE TITLE
Allow to show/hide script attributes

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#664]
Script attributes are often used for exposing some logic values to Editor for quick access. It is often a case, where one script attribute depends on another, e.g. this will change that only if that option is selected. If would be nice if we could show/hide attributes, to simplify the inspector view, which currently has to show a complete list.

**Comment by yaustar** [comment]
Duplicate of https://github.com/playcanvas/editor/issues/278?

**Comment by LeXXik** [comment]
I can't even recall my own feature requests :D
