### ISSUE TITLE
Allow private launch page to be accessed without logging in

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#669]
Use case from Discord: Developer is making a web app for Echo Show but they can't log into PlayCanvas to test so that have to publish each time for testing on device.

Can we think of a way to be able access the site such as an auth token that is limited to read only access that can be passed in URL param?

**Comment by Maksims** [comment]
This is a recipe for a disaster.
I had to run Launcher in various weird platforms, and there always was a way to authenticate for development purposes.

**Comment by yaustar** [comment]
Closed in favour of https://github.com/playcanvas/editor/issues/791
