### ISSUE TITLE
Script editor does not save your position when opening through 'find in files'

### ISSUE THREAD

**Issue by Slasmir** [playcanvas/editor#676]
Forum link: https://forum.playcanvas.com/t/code-editor-not-saving-active-line-number/24131

If you use Ctr+Shift+F to find a line in the code, then click that line to open the correct code file, the line will not be saved, meaning if you then change to another code tab and back you will be left at the top (or where you last saved a line selection) of the file. This leads to quite a lot of confusion when following references in the code.

This happens in all browsers

### Steps to Reproduce

1. Open script editor
2. Open Find in files Ctr+Shift+F
3. Search for something you know is in the project.
4. Find a occurrence at a line number further down then 55.
5. Click it, and go to the occurrence.
6. Go to another code tap.
7. Go back to the tap you came from
8. The code editor is now at line 1 and not at the place you where send to through Ctr+Shift+F

**Comment by jpauloruschel** [comment]
Thank you for the suggestion! This functionality has now been implemented and will be available on the next Editor release.
