### ISSUE TITLE
Preview animation only works on first selection

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#680]
Video: 

https://user-images.githubusercontent.com/16639049/152215654-043fe60e-a747-4737-b729-66342b8c552a.mp4

Test Scene: https://playcanvas.com/editor/scene/1325553

Repro steps:

1. Select the Scene.glb animation in the assets panel under Animations/Reload
2. Preview is showing correctly
3. Select the floor in the 3D scene
4. Select the Scene.glb animation again
5. Preview is not playing nor rendering correctly

**Comment by ellthompson** [comment]
A fix for this has been released to the production version of the Editor.
