### ISSUE TITLE
[Bug] Skybox intensity affects all cubemaps in project

### ISSUE THREAD

**Issue by maungers** [playcanvas/editor#683]
![image](https://user-images.githubusercontent.com/22077882/152404465-5429548a-10fe-4e44-acc1-268a86ab4faa.png)
![image](https://user-images.githubusercontent.com/22077882/152404422-c1d999f2-ecb5-44cb-8350-cd8c2d5b5e74.png)

https://playcanvas.com/editor/scene/1327573

1. Open settings.
2. Set intensity value to 0.
3. All cubemaps in the project are now black.

**Comment by yaustar** [comment]
Closed as it is more likely to be an engine issue? https://github.com/playcanvas/engine/issues/3979
