### ISSUE TITLE
Enable Multi-threading/processing via Express response header

### ISSUE THREAD

**Issue by Steveorevo** [playcanvas/editor#686]
### Description
Didn't want this to fall through the cracks; so documenting in hopes this easy fix gets implemented (just add the response header in the express app please). 

Applications delivered on playcanvas.as could use 'Origin-Agent-Cluster' in the response header; without it, multi-iframe applications are single process/threaded and cause blocking. Please add Origin-Agent-Cluster with value '?1'. See the video below for an example of blocking which causes momentary hand/headset tracking stutters and 'hiccups'. 

This issue is more likely to occur on *published* apps using one or more processor intensive iframe "background" processes. This is less likely (but can occur) in the Editor -> Launch; because of the editor overhead, and "pre-emptive browser resource heuristics" make it less likely. For an explanation on how the solution using Origin-Agent-Cluster resolves this, please review: https://web.dev/origin-agent-cluster/

Video showing the problem is here:
https://www.youtube.com/watch?v=V0i9CKdIV-g

* Oculus/Meta native browser in Quest 1 & 2 headsets and most likely all Chromium based browsers. 

This issue ***and it's solution*** is fully documented at:
https://forum.playcanvas.com/t/solved-multi-threaded-operations-in-webxr-editor-vs-published/24199/6

**Comment by slimbuck** [comment]
Thanks so much for posting this issue and the additional info @Steveorevo. We'll investigate over the next few weeks. @yak32 @jpauloruschel

**Comment by Steveorevo** [comment]
Note: Oculus just updated their browser and the "issue" no longer appears. They've changed the heuristics so that iframes get their own process thread in the problem examples I've furnished links to. Users with older browsers will still experience the issue but updates rollouts and no opt-outs (and with well over 40% market share in VR) means that this is less likely to be a problem. 

Just thought I'd keep you updated. Though it might still be a good idea to include Origin-Agent-Cluster in response headers to allow webxr devs to fine tune resource allocation. 

May also want to keep the issue open (and I can test) to test against Wolvic (formerly Firefox Reality); as it looks like they are nearing release.

**Comment by yak32** [comment]
hi @Steveorevo, thanks for reporting this! 
My thoughts  - the header is experimental, works in Chrome only and I can't predict how it would affect other published apps. Also, you mentioned that Quest's browser fixed this - so how important is it for you now? 

Agree, let's keep this issue open and keep an eye on this header adoption. Please post if anything changed on your side.

**Comment by yak32** [comment]
closing this, please open another issue if needed
