### ISSUE TITLE
More powerful hierarchy search

### ISSUE THREAD

**Issue by davidpox** [playcanvas/editor#69]
As whydoidoit's [Playcanvas Editor Plus](https://chrome.google.com/webstore/detail/playcanvas-editor-plus/ebedfcjmndjbaboecddbbjjjoleddfap) extension no longer works, one feature I used a ton and would like to see implemented is the hierarchy search, supporting regex, component search, searching for entities that use a script, and searching that only searches the "hierarchy" branch you've currently selected.

**Comment by yaustar** [comment]
@davidpox Looks like the extension has been updated in Oct 2020 😲

**Comment by yaustar** [comment]
Related to https://github.com/playcanvas/editor/issues/262

**Comment by damvad** [comment]
*bump* This would be great to have. As of now, when I'm looking for an unknown Entity with a certain script, I use console.log to print the name, then put that name into the search field in the editor to find that Entity. Kind of a hassle... 😄

**Comment by jiajasper** [comment]
Hi, after some testing and discussion, the V1 of this search upgrade will include:
1. Search by Name
2. Search by Component
3. Search by Attached Script Name
4. Search by Tags
5. Toggle for Smart Search (fuzzy search)

https://user-images.githubusercontent.com/30747200/178498899-9198cb44-05d1-429f-a271-aa56ff5f759a.mov

Figma Link:
https://www.figma.com/file/USwW0a6rU12PJkcz4wfwzg/PlayCanvas-Editor?node-id=231%3A24353

**Comment by willeastcott** [comment]
Wow, this looks *really* great! Nice design, @jiajasper

**Comment by jiajasper** [comment]
> ![image](https://user-images.githubusercontent.com/16639049/178521336-c1cb521b-989f-489d-9c72-6c4607102b0c.png)
> 
> A concern here would be the speed of creating the query. Maybe if the '+' button is close to where the new field will pop up (eg, if the are added to the bottom, that's where the '+' button should be).
> 
> Maybe for V2, we could have saved and/or history of queries too so users don't have to set it up each time.
> 
> The advantage of having a search query that is purely text based like PlayCanvas Editor Plus is that it's very easy to change and save queries somewhere (eg clipboard history)

Yes I think the add button would be better off placed on the bottom especially when a user has lots of conditions set up! The top right corner could instead be a "clear all" button.

And for the search queries, I do share the same feeling as well. I think if a user needs this level of search power, maybe a more technical approach could benefit their workflow more than a pure UI solution. I will ask the forum for some feedback.

**Comment by jpauloruschel** [comment]
V1 has been merged and will be available on the next Editor release (v1.21.81).

**Comment by willeastcott** [comment]
Since v1 has been out has been available for some time now, I am closing this issue. For any requests regarding further improvements, please open a new issue.
