### ISSUE TITLE
Undo doesn't reset child elements when undoing the addition of a layout group compoment

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#690]
Video:

https://user-images.githubusercontent.com/16639049/153392571-c59354aa-d684-4604-beb1-7fcbb8f184a2.mp4

Fork this project: https://playcanvas.com/editor/scene/1333045
Add layout group component on entity 2D Screen/Group
Note that the child elements are moved to the layout group position 
Undo the addition of the layout group position  
The child elements are still in the layout group position rather than the previous position

**Comment by jpauloruschel** [comment]
Fix is done and will be available in an upcoming Editor release.
