### ISSUE TITLE
Add project name to launch tab

### ISSUE THREAD

**Issue by renegadels** [playcanvas/editor#695]
Hello team,

I feel it would be beneficial to add the project name to the title of the launch tab, just like Editor or Code Editor. For example - 

![image](https://user-images.githubusercontent.com/58387535/154830716-4a29cdb3-63e7-4b3d-a0d4-c1ffddd26a5c.png)

That way, if we have multiple launch tabs from different projects open, it would help us differentiate between them.

**Comment by willeastcott** [comment]
Great suggestion! I've submitted a fix for this (and also done the same for the Code Editor). Hopefully it can be deployed in the next few days.

**Comment by yaustar** [comment]
released in 1.21.29
