### ISSUE TITLE
Camera movement problem with wheel button of mouse

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#7]
### Description

Editor's camera movement has a problem. It stuck at start point when I start to move my mouse. It can be something on mouse down and up events. Because it appears if I do that movement quickly.

Here is a GIF to show how it looks like : https://gyazo.com/77a49b30cbf9f11c2a78270dbc8550a9

### Steps to Reproduce

1. Open PlayCanvas editor in Chrome browser
2. Move camera with wheel button of mouse.

**Comment by slimbuck** [comment]
Managed to reproduce this, but on occasionally on chrome and firefox on macos.

**Comment by slimbuck** [comment]
Also happens using shift+left mouse button.

**Comment by slimbuck** [comment]
@devcem we have a fix for this which will hopefully be released today.

Thanks!

**Comment by willeastcott** [comment]
The fix was just deployed @devcem so I'm closing this. Sorry this affected you!
