### ISSUE TITLE
Materials lose textures when Editor reconnects

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#70]
If the Editor becomes disconnected after some time (if tab is deactivated, for example), it will try to reconnect again and reload the scene. However, textures seem to fail to reload and you see something like this:

![image](https://user-images.githubusercontent.com/697563/81715536-400c0900-9470-11ea-9da4-f015574ea281.png)

You have to hit F5 to refresh the Editor to restore everything:

![image](https://user-images.githubusercontent.com/697563/81715668-6467e580-9470-11ea-8c03-4165b048a01d.png)

**Comment by yaustar** [comment]
Are they basis compressed? Might be related to the issue that this PR fix here: https://github.com/playcanvas/engine/pull/2070

**Comment by willeastcott** [comment]
They are Basis compressed actually. But I'm very confident that's not the issue since this has been a problem since before we had Basis integration.

**Comment by willeastcott** [comment]
I've not seen this in a while, so I'm closing.
