### ISSUE TITLE
Change favicon in launch tab so it looks different to the Editor tab

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#701]
![image](https://user-images.githubusercontent.com/16639049/156390343-82038bca-d64e-4d2d-992a-f650890df124.png)

The Code Editor tab has a different favicon so it be nice for the launch tab to have one for easy/quick glance

**Comment by Maksims** [comment]
Published projects, have favicon generated from Thumbnail, this could be an option for Launcher too. It will allow to differentiate it easily, even between projects.

**Comment by willeastcott** [comment]
Definitely one for @jiajasper 😄

**Comment by jiajasper** [comment]
I agree with @Maksims that it'd be nice to have favicon generated from thumbnail!

For a quick fix, here is my proposed icons
![image](https://user-images.githubusercontent.com/30747200/164712006-e0a58720-935d-45fb-8b92-3d48e004a570.png)

**Comment by willeastcott** [comment]
I like the launch icon - like a play button. Nice.

**Comment by jiajasper** [comment]
To whom may take on this ticket, here are the png files 


![Image](https://user-images.githubusercontent.com/30747200/174855807-6cca1c64-3ee4-4772-9f8d-8e615152981b.png)
![Image](https://user-images.githubusercontent.com/30747200/174855806-2db8f2b4-2d32-4687-9e1b-72434d7daa41.png)
![Image](https://user-images.githubusercontent.com/30747200/174855809-a2335402-de43-4462-aca7-65b673887bb8.png)

**Comment by jiajasper** [comment]
@josflesan could be a quick one to take on too

**Comment by yaustar** [comment]
Added in https://github.com/playcanvas/editor/releases/tag/v1.21.70
