### ISSUE TITLE
Create FBX folder only works with files with lower case '.fbx'. '.FBX' will not create the folder

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#702]
Create FBX folder will only create a folder if the file has `.fbx` (all lower case) in the file name extension.

If it's `.FBX` for example, the folder will not be created

**Comment by yaustar** [comment]
Fix made, waiting for next editor release

**Comment by willeastcott** [comment]
This is now deployed.

![fbx](https://user-images.githubusercontent.com/697563/221358056-6b4a0a22-0a0d-4034-a67b-d955cdf4a79d.gif)

Closing.
