### ISSUE TITLE
Materials always set to 0 length after changing Render asset

### ISSUE THREAD

**Issue by erikdubbelboer** [playcanvas/editor#709]
### Description

After importing an fbx, putting the template into the scene and changing the Render asset the Materials array always has 0 materials even though the same Render on another entity does have Materials.

This is after the recent update to fbx imports.

### Steps to Reproduce

1. Download and import https://dubbelboer.com/example.fbx into an empty project
2. Put the `example` template into the scene.
3. Notice that the first `path` entity has `path` as asset and the second `path` entity has `path1` as asset.
4. Notice both have 1 material.
5. <img width="1637" alt="Screenshot 2022-03-14 at 08 41 49" src="https://user-images.githubusercontent.com/522870/158128160-ab1b0d97-6d92-4a4c-8b13-d4b12266f80f.png">
6. Change the second `path` entity's asset to `path` (instead of `path1`).
7. Now the second `path` Render has 0 materials (even though the same Render on the first `path` has 1 material).
8. <img width="324" alt="Screenshot 2022-03-14 at 08 42 12" src="https://user-images.githubusercontent.com/522870/158128169-e0f90c95-23f3-4ada-9781-5cc684e517b0.png">

**Comment by erikdubbelboer** [comment]
Any update on this? Can it at least be confirmed?

**Comment by yaustar** [comment]
Can confirm. @mvaligursky or @ellthompson, would you be able to look at this please?

**Comment by willeastcott** [comment]
Yes, ideally, can somebody investigate on Monday please? @slimbuck can you 'own' this and figure out who is best placed to take it on please?

**Comment by willeastcott** [comment]
OK, I saw a fix for this get merged this today (thanks to @ellthompson!). We are planning to deploy the fix to production tomorrow. Thanks for your patience while we fixed this. 😄

**Comment by willeastcott** [comment]
And the fix is live! 

https://github.com/playcanvas/editor/releases/tag/v1.21.39

Enjoy! 🎉

**Comment by erikdubbelboer** [comment]
Confirmed, thanks!
