### ISSUE TITLE
[Bug] assets are created at top level instead of the current folder (via context menu)

### ISSUE THREAD

**Issue by thisredone** [playcanvas/editor#71]
When creating assets (and folders) via right-click menu assets are created at the top level `/` instead of the current folder. As far as I can tell this regression was introduced in the last couple of days

![image](https://user-images.githubusercontent.com/1191844/81736665-2c27cd80-9497-11ea-846f-650f2d026252.png)

This only happens when clicking on the empty space - not when right-clicking an item in the tree view on the left

**Comment by vkalpias** [comment]
This should now be fixed.
