### ISSUE TITLE
Build config file contains extra data

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#710]
It seems the config file has grown recently, as most assets now include similar fields:
![image](https://user-images.githubusercontent.com/5677782/158216243-7056930b-46dc-4e4f-bf53-ad63889095cd.png)

Probably related to the assets history feature? Raising it as a bug, as those are not needed for the application to run, but increase its size.

**Comment by yaustar** [comment]
@zachpeterpaul, is this something we could omit in the publish step?

**Comment by yaustar** [comment]
Actually, we should look at what data we can strip here. I don't think it's all needed at runtime 🤔

**Comment by LeXXik** [comment]
Some or all of that data could possibly be used elsewhere (maybe uploading a project zip to restore a project?). If so, maybe we could have an option for a light config file for runtime only.

**Comment by yaustar** [comment]
Fixed in release of v1.21.61 that we are aiming to release on Monday/Tuesday
