### ISSUE TITLE
HTML and CSS files are served as mimetype text rather than text/html or text/css

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#716]
Run: https://launch.playcanvas.com/481136?debug=true

See in console:
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/16639049/158591519-29c52d16-4337-4af4-b332-6a66a1bad899.png">

**Comment by willeastcott** [comment]
@yak32 might have some thoughts here...

**Comment by yak32** [comment]
engine problem - we request assets.html, server correctly returns test/html mime type, engine expects Http.ContentType.JSON for some reason.

**Comment by willeastcott** [comment]
Seems fixed. Warnings no longer present. I've checked the Network tab. .css is served with Content-Type text/css and .html has text/html.

![image](https://github.com/user-attachments/assets/9820860f-b073-4e3d-bc30-6d8635568776)

Closing.
