### ISSUE TITLE
Feature Request: List view in the Assets pane

### ISSUE THREAD

**Issue by thisredone** [playcanvas/editor#72]
Between "Large" and "Small" there isn't a mode where you can actually see the whole filenames without hovering or clicking on the assets.
On many occasions (like when you have prefixes) the important part of the filename is not directly at the beginning + the thumbnails for models don't include the material so they're often not very descriptive. It would be useful to be able to see the names of the models and have the thumbnail show up on hover (if at all).

**Comment by vkalpias** [comment]
Hi - we actually have this in Beta testing right now:

https://twitter.com/vkalpias/status/1248290766209921028

Would you like me to whitelist you?

**Comment by thisredone** [comment]
awesome! Yeah, whitelist me :)

**Comment by vkalpias** [comment]
Can you tell me your PlayCanvas username?

**Comment by thisredone** [comment]
redka :)

**Comment by vkalpias** [comment]
OK you should be whitelisted now if you refresh the Editor

**Comment by thisredone** [comment]
Thanks, very cool

**Comment by vkalpias** [comment]
Let us know if you notice any issues :)
