### ISSUE TITLE
Uploading assets by drag'n'drop from archive, produces weird results.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#729]
When uploading assets by drag'n'drop and they come from an archive, it leads to weird results, which confuses a developer. Tested on Windows and Chrome, using default archive explorer.

### Steps to Reproduce

1. Open archive in Windows Explorer
2. Drag'n'drop FBX file to assets

### Issue

Created asset, looks similar to source file FBX, but has `runtime` flag.

### Expected

Either to work from archive or don't work and notify a developer about that file: it is 0 bytes, so surely it is not correct.

### Example archive

[SK_Fantasy_Witch_01.zip](https://github.com/playcanvas/editor/files/8351055/SK_Fantasy_Witch_01.zip)

### Screenshot

![image](https://user-images.githubusercontent.com/636263/160134181-dd46b15d-64bf-45b4-8881-5d9d14555079.png)

**Comment by yaustar** [comment]
This has happened again in Discord: https://discord.com/channels/408617316415307776/408617316415307778/960898017093898311

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/16639049/161768753-0479c3b7-3db8-4384-9882-e3f207b8bfe2.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/16639049/161768781-3216dcc0-2018-403d-8e81-ebdf3901962c.png">

I can imagine users doing this a lot as it's common to get FBXes and other assets as zips

**Comment by yaustar** [comment]
This is fixed in release 1.26.0
