### ISSUE TITLE
RenderComponent when Asset is set, not adding a material slot.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#730]
I have a FBX file, which when uploaded creates template, which has an entity with render component in it, and material slot.

But when creating new Entity then add RenderComponent to it and set uploaded asset, it will not create Material slot.

### Steps to Reproduce

1. Upload FBX file
2. Create new Entity
3. Add Render Component
4. Set Render Asset

### Expected

Material slot to be added.

### Issue

Material slot is not created for it.

### Example file

Don't forget to unpack it first. [SK_Fantasy_Witch_01.zip](https://github.com/playcanvas/editor/files/8351126/SK_Fantasy_Witch_01.zip)

Actual vs Expected
![image](https://user-images.githubusercontent.com/636263/160134929-0ee63dc7-2053-4918-b310-7231884ef29a.png) ![image](https://user-images.githubusercontent.com/636263/160135250-be4012b1-278b-4a6d-a52f-d218bf42818e.png)

**Comment by erikdubbelboer** [comment]
Similar to https://github.com/playcanvas/editor/issues/709

**Comment by yaustar** [comment]
Closing as duplicate
