### ISSUE TITLE
Model Viewer Starter Kit Orbit Camera script error

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/editor#735]
### Steps to Reproduce

1. Create a new project:

![image](https://user-images.githubusercontent.com/5236548/161923991-d3736205-4961-41b0-b361-487126eddac1.png)

2. Run the project:

![image](https://user-images.githubusercontent.com/5236548/161923295-e0230d05-615d-416f-b65c-acddb7676385.png)

Solution:

Fix `OrbitCamera#_buildAabb`, from:

```js
        var models = entity.findComponents('model');
        for (i = 0; i < models.length; ++i) {
            meshInstances = models[i].meshInstances;
            for (j = 0; j < meshInstances.length; j++) {
                allMeshInstances.push(meshInstances[j]);
            }
        }
```

To something like this, not trying to iterate `null`:

```js
        var models = entity.findComponents('model');
        for (i = 0; i < models.length; ++i) {
            meshInstances = models[i].meshInstances;
            if (!meshInstances) {                
                continue;
            }
            for (j = 0; j < meshInstances.length; j++) {
                allMeshInstances.push(meshInstances[j]);
            }
        }
```

**Comment by yaustar** [comment]
Odd, I've just forked it and it works fine here 🤔

**Comment by yaustar** [comment]
I've added the null checks regardless as it's good to protect against it :)

**Comment by yaustar** [comment]
What's on the cone? Is it a model component or a render component?

**Comment by kungfooman** [comment]
Apparently I added a model component (I didn't even remember):

![image](https://user-images.githubusercontent.com/5236548/161952398-3d864f7e-0fc0-4105-93ff-52dd5fb5ea70.png)

I tried to load a GLB, e.g. by dropping `statue.glb` in different locations (like the model component), but I just couldn't figure it out (to test the decal system with a non-trivial model).

Then I just tried to launch the project and run into that error.

**Comment by yaustar** [comment]
GLB import is not supported in the Editor yet. If you need to load a GLB file, it has to be done at runtime eg https://developer.playcanvas.com/en/tutorials/loading-gltf-glbs/

Ah yes, adding an empty Model Component of type asset will cause the exception you saw (no meshintances). I've updated the project to protect against that using your recommendation
