### ISSUE TITLE
Sound component tutorial link broken

### ISSUE THREAD

**Issue by saadhaider78** [playcanvas/editor#737]
The tutorial popup for sound component leads the user to the following URL , which doesn’t exist:

https://developer.playcanvas.com/en/tutorials/beginner/basic-audio/ 

Related forum post:
https://forum.playcanvas.com/t/broken-link-audio-tutorial/25143

**Comment by yaustar** [comment]
Released in https://github.com/playcanvas/editor/releases/tag/v1.21.42
