### ISSUE TITLE
Code Editor - Keep scroll position in find all results when going to a different tab 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#738]
Repro steps:

1. Do a find all in the code editor where the number of results is large (searching for `}` works well)
2. Scroll down to a result and double click on it 
3. Go back to the find all results, notice that the scroll position has been rested to the top

https://user-images.githubusercontent.com/16639049/162703717-86064db5-068e-4bf2-bfc7-1594526e765a.mp4

**Comment by jpauloruschel** [comment]
This functionality has been implemented and will be available on the next Editor release.
