### ISSUE TITLE
[Feature] Middle click on the scene browser to open in a new tab

### ISSUE THREAD

**Issue by vmwxiong** [playcanvas/editor#748]
Extremely minor request, but I'd love to be able to middle click open scenes in a new tab, to facilitate @yaustar's workflow of having a template editor in one tab, while having a main scene in another.

**Comment by yaustar** [comment]
Fixed in release of v1.21.61 that we are aiming to release on Monday/Tuesday

We've decided to go with a drop down option to make it more visible to users 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/16639049/176896329-26b627e2-3940-49cd-9064-5fe4a46fb37a.png">
