### ISSUE TITLE
'preserve material mapping' when re-importing a FBX does not work

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#749]
When re-importing the FBX, duplicate materials and mappings are created even when the setting is set

**Comment by slimbuck** [comment]
Do you have a repro project/steps? I created a scene specifically to test this and works fine. Will need a repro to investigate further.

**Comment by yaustar** [comment]
Unable to reproduce with the following steps, reaching out to the client that reported this:

- Created a custom material
- Applied the custom material to the model asset 
- Re-imported the FBX into the same folder as the existing FBX
- Material maps are preserved and the materials/FBX/model was not duplicated

**Comment by yaustar** [comment]
Closed as it's only on a private client project
