### ISSUE TITLE
Manifest file cannot be loaded from the /b published link

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#756]
Forum: https://forum.playcanvas.com/t/manifest-not-loading-at-playcanv-as/25534

Example link: https://playcanv.as/b/lVNnHrTx

Error loading the manifest file is seen here: 
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/16639049/166501072-dea3c882-3a29-403d-9726-a7bfcfe5c14d.png">

Looking at the request, looks like a forward slash is missing:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/16639049/166501120-103fe73a-1e63-4f5c-827e-3a3a6c9dcae5.png">

`https://playcanv.as/b/lVNnHrTxmanifest.json` should be `https://playcanv.as/b/lVNnHrTx/manifest.json`?

**Comment by willeastcott** [comment]
Fixed by @yak32! Closing. 😄
