### ISSUE TITLE
Make database paths selectable in the status bar

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/editor#757]
The easiest way to find the right path for use with item get/set methods, is to toggle a property in editor and watch the status bar render the right path saved to the database.

The only thing missing is the ability to select and copy that path to use in your editor API enabled scripts. Right now that text isn't selectable making the process hard.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/29543178/166522525-fc929951-3139-4add-9b3a-d56ba4178241.png">

**Comment by willeastcott** [comment]
I've just submitted a PR to address this. We'll deploy next week.
