### ISSUE TITLE
Downloading GLB from the editor uses incorrect mapping filename

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#76]
When downloading a GLB asset from the the Editor, the materials mapping file is `modelName.glb.mapping.json` when `app.assets.loadFromUrl` is expecting `modelName.mapping.json`

**Comment by FutureFireplace** [comment]
Throwing in a comment ... this could be really nice if fixed (a rigid optimization of glB-handling, could even be perfect) :-)

**Comment by vkalpias** [comment]
This is now fixed.
