### ISSUE TITLE
FBX import doesn't create a valid GLB if it has `%20` in the filename

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#761]
This FBX import used to work at some point but now no longer creates a valid GLB https://playcanvas.com/project/924340/overview/invalid-glb

**Comment by yaustar** [comment]
The issue is with the symbols in the FBX name. If you remove the `%20` in the file name and replace them with ` `, the render asset is created correctly

**Comment by yaustar** [comment]
The reason why it 'used to work' was that when I downloaded the FBX from the original project, it URL encoded the filename for the download and replaced the `%20` for all the spaces

**Comment by yak32** [comment]
filenames are not encoded in editor, but encoded on the launch page.

**Comment by willeastcott** [comment]
Perhaps this has since been fixed. The model imports and displays correctly in both the Editor and Launch Page now:

![image](https://github.com/user-attachments/assets/4b6549ca-37e3-4f87-86e1-b74013808599)

Closing.
