### ISSUE TITLE
Zooming in the Editor 3D viewport with a trackpad

### ISSUE THREAD

**Issue by vrhermit** [playcanvas/editor#768]
This issue relates to using a trackpad in the 3D viewport of the PlayCanvas Editor while working on a scene. Zooming in and out while focused on an object works as expected when working with a traditional mouse with a scroll wheel. I have some physical issues that make using a mouse difficult, so I use the trackpad on my MacBook Pro as my primary pointing device. Zooming in and out with the trackpad has an exaggerated effect, making it difficult to position my view while working on a scene.

### Steps to Reproduce

1. Open any project
2. Focus on a 3D object in the viewport
3. Use a trackpad to zoom in or out

This gif shows the issue in action. I'm making the smallest movements possible and getting this reaction.
![scroll-trackpad](https://user-images.githubusercontent.com/97741130/168909742-0e57b177-b88d-461a-9137-fb7abc8afe1f.gif)

Possible solution: I have no idea if you can even determine if a user is using a trackpad. If not, how about a new Editor setting for zoom sensitivity?

**Comment by yaustar** [comment]
We have a feature request on zoom sensitivity:
https://github.com/playcanvas/editor/issues/679
https://github.com/playcanvas/editor/issues/352

Out of interest, what is your tracking speed? I've not had this problem on my Macbook so interested to see what setting differences are.

**Comment by yaustar** [comment]
Interesting, it's the same settings as mine 🤔

**Comment by yaustar** [comment]
In the meantime, you can use WASD to move the camera around like a first person shooter and hold right mouse button to look around.

**Comment by yaustar** [comment]
Closing other tickets as duplicates

**Comment by yaustar** [comment]
Added in https://github.com/playcanvas/editor/releases/tag/v1.21.70
