### ISSUE TITLE
Zooming in/out on the curve editor can affect the Editor view

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#77]
If zooming in/out over the Editor view and curve editor overlap area, affects both views.

![Kapture 2020-05-18 at 10 03 07](https://user-images.githubusercontent.com/16639049/82194766-3ad71000-98ef-11ea-913e-a50ef32db6ca.gif)

**Comment by vkalpias** [comment]
I am not able to repro this - is it still happening for you?

**Comment by ellthompson** [comment]
I believe this was fixed in Monorepo pull request 282
