### ISSUE TITLE
Moving multiple entities shows positions at 0, 0, 0

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#79]
They should show any values that the same (in this case the Y value) and the other should be `...`
![Kapture 2020-05-20 at 15 27 03](https://user-images.githubusercontent.com/16639049/82458654-dcf12680-9aae-11ea-82d0-9e1f1001e96e.gif)

**Comment by ellthompson** [comment]
This fix is live on production now. Closing the issue.
