### ISSUE TITLE
Reimporting FBX doesn't update Materials array for the Render asset

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#792]
Forum: https://forum.playcanvas.com/t/material-array-does-not-update-after-fbx-update/26135/

Assets:
[20220614-144053.zip](https://github.com/playcanvas/editor/files/8900848/20220614-144053.zip)

Steps:

1. Upload before/MaterialTestObject.fbx
2. Create an entity with a render component, add the render asset to it
3. Note that it has 2 materials in the material array
4. Upload after/MaterialTestObject.fbx to overwrite the render asset, glb etc assets
5. The render component created earlier still only has 2 materials instead of the expected 3
6. Add the model template to scene, note that the render component with the render asset has 3 materials in the array

https://user-images.githubusercontent.com/16639049/173608279-79e5ee46-5d8f-4c9d-9bab-dd059780282e.mp4

**Comment by mvaligursky** [comment]
I wonder if @zachpeterpaul know something about this? Is this on a template side if things or not? I remember you did some handling of fbx reimport for render assets.

**Comment by yaustar** [comment]
Cannot reproduce now 

https://user-images.githubusercontent.com/16639049/217598338-566c9867-ab8a-42dd-bafc-ca6cd8945c78.mp4
