### ISSUE TITLE
Memory usage explosion when searching in all files

### ISSUE THREAD

**Issue by rafern** [playcanvas/editor#796]
### Description

When searching in all files, memory usage sometimes increases to huge amounts. Maybe its searching files that it shouldn't? If this happens, the search will also freeze.

https://user-images.githubusercontent.com/15365765/174808920-96d51325-b31d-41a5-a42c-a6777275e374.mp4

### Steps to Reproduce

1. Open the code editor
2. Search for something in the Find in files tab (ctrl+shift+f)
3. Memory usage explodes and the search freezes

**Comment by rafern** [comment]
@yaustar This is using the search for all files in the project, so I'm not sure which of them is causing the issue. There are JSON files, glb models, textures, code etc... But the problem only started recently after adding more models to the project. Maybe that's what's causing the issue?

**Comment by rafern** [comment]
Never mind, GLB files aren't searchable in the editor. I tried your suggestion and filtered by file type. A large (~7MB) JSON file was causing the issue, but its still weird that searching that file was causing a memory usage of +16GB

**Comment by yaustar** [comment]
It's definitely something we should investigate, hopefully the find in files will mitigate it a bit in the meantime 🤞

**Comment by yaustar** [comment]
@slimbuck Would this be fixed by your changes that made find in files much faster?

**Comment by slimbuck** [comment]
Possibly. Worth checking.

**Comment by yaustar** [comment]
Assumed fixed with slimbuck's changes to faster search
