### ISSUE TITLE
Animation states all disappear when the editor has been idle for too long

### ISSUE THREAD

**Issue by camelCaseSensitive** [playcanvas/editor#799]
### Description

When I leave the editor open in another tab for too long and return to it the page appears to reload and when it does all the animations (.glb) I have populated the animation component with are gone.

### Steps to Reproduce

1. Create an entity with an animation component and animation state graph.  
2. Create some new animations states
3. Drag and drop some .glb files to the animation states. 
4. Leave the editor open in a new tab for maybe 30 minutes
5. Click on the tab to go back to the editor and if the page reloads the animations will all be de-populated from the anim component

**Comment by yaustar** [comment]
This is due to the Editor disconnecting from our realtime services I believe. 

Potentially related to https://github.com/playcanvas/editor/issues/301 and https://github.com/playcanvas/editor/issues/576

**Comment by camelCaseSensitive** [comment]
It just happened again :(

**Comment by yaustar** [comment]
I've just reproduced this. I believe you have to leave the tab idea with entity that has the anim component in the inspector and just leave the window idle (not as a background tab)

**Comment by yaustar** [comment]
Released 1.23.8
