### ISSUE TITLE
Line break in text element string field is broken

### ISSUE THREAD

**Issue by SophieRefshauge** [playcanvas/editor#8]
One can no longer use line breaks in the text editors string field.

Expected result:
- When pressing Shift+Enter, I expect to introduce a line break.
- When copy pasting text with a line break included from a text editor, i expect the line break to be transferred too.
- When inserting two "spaces" I expect a line break to be created.

**Comment by slimbuck** [comment]
Confirmed on prod

**Comment by halvves** [comment]
Hi @SophieRefshauge, just checking in and getting some clarification. I see that `shift`+`enter` isn't behaving as expected (and already have a fix staged for it), but pasting into the text area seems to carry over line breaks properly for me. Is that also not currently working for you?

The "two 'spaces'" creating a line break part confuses me a bit. I don't recall ever having a behavior like this. Do you mind elaborating on this one?

**Comment by SophieRefshauge** [comment]
Hi @halvves,

Thanks for the update.
I just tested, and pasting into the text area works for me now.
Glad to hear that it's being fixed soon.

Don't worry about the double space - I must have misunderstood my programmer.

**Comment by willeastcott** [comment]
Fixed by @halvves. Enjoy!
