### ISSUE TITLE
Unable to assign texture to cookie of point light

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#800]
Currently I am unable to assign a texture to cookie of point light.

![image](https://user-images.githubusercontent.com/52896137/175808604-b30fb38d-ea2b-4659-9b69-88f6a4b02e58.png)

**Comment by yaustar** [comment]
For point lights, as it is spreading light from a single point, it is needs to be a cubemap (which isn't clear in the Editor)

Spotlights use normal textures.

Closing this ticket and creating a new one to make this clearer
