### ISSUE TITLE
Rename Point light to Omni light

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#801]
When I was looking to information about point light, I discovered this is not available anymore. I guess the name of point light is renamed to omni light? In that case, the name has not yet been updated in the editor and some other places.

**Comment by willeastcott** [comment]
Can you list the places you still notice 'point' instead of 'omni' and we'll get them updated. Thanks!

**Comment by albertvanveen** [comment]
- The light component in the editor itself
- Manual page: https://developer.playcanvas.com/en/tutorials/controlling-lights/
- Manual page: https://developer.playcanvas.com/ru/user-manual/packs/components/light/

**Comment by yaustar** [comment]
We also call it a point light in the Editor
<img width="523" alt="image" src="https://user-images.githubusercontent.com/16639049/175818425-eb3b8c23-037f-4520-a914-39dd01ff660c.png">

**Comment by willeastcott** [comment]
That was @albertvanveen's first bullet. 😄

**Comment by willeastcott** [comment]
@mvaligursky Can you confirm that the language 'point light' should be globally replaced with 'omni light' (across all our docs/source/interfaces)?

**Comment by mvaligursky** [comment]
Correct, all 'Point light' should be converted to 'Omni light', to match the engine.

**Comment by willeastcott** [comment]
@yaustar I've fixed the Editor front-end. Do you want to update the tutorials mentioned above?

**Comment by yaustar** [comment]
Sure, I will update

**Comment by willeastcott** [comment]
The Editor UI has now been updated to only refer to Omni lights. There is also a [PR](https://github.com/playcanvas/developer.playcanvas.com/pull/447) to update the Developer Site. Therefore, I'm closing this issue. If you find any more instances of 'point light', do let us know! 😄
