### ISSUE TITLE
Framing is incorrect for entity with collision after selecting a 2D screen

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#802]
Project: https://playcanvas.com/project/950740/overview

Select Player in the scene hierarchy
Press F
Camera frames the entity correctly
Select the 2D screen
Select the Player again
Press F
Camera framing is incorrect

https://user-images.githubusercontent.com/16639049/175818936-4eb0d50c-50d0-4750-9a2d-119cb1d023f2.mp4

**Comment by sri-30** [comment]
https://github.sc-corp.net/PlayCanvas/monorepo/pull/1574
