### ISSUE TITLE
New Project Dialog - Disabling thumbnail drag

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/editor#808]
Not critical, but would be great to disable the thumbnail from being dragged as shown in the video

https://user-images.githubusercontent.com/30747200/177125289-b16e657f-efb5-4861-a3a2-b33b5576a77c.mov

**Comment by willeastcott** [comment]
Seems this has been fixed:

![drag](https://user-images.githubusercontent.com/697563/221358415-de3df4d3-086b-42f4-84a6-d301bf69341b.gif)

Closing.
