### ISSUE TITLE
Make it clear from the Editor UI what settings are saved per user and what are saved for the project

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#819]
For example, asset tasks is per user but layers and render is for the project

**Comment by brianruggieri** [comment]
I wish I could give this a few more thumbs up. Working with a team of artists importing assets to a project it can be tricky to ensure some consistency with the asset/model import options. Asset tasks are the most obvious per-user settings, but I have been curious what/if other project settings are as well.

**Comment by jiajasper** [comment]
Please see figma link for design: https://www.figma.com/file/USwW0a6rU12PJkcz4wfwzg/PlayCanvas-Editor?node-id=1105%3A44738&t=NoYINfde1Yhi0Vav-1

Designs include
1.Added icons to indicate global vs per user settings
2. Added tooltips over the icons
3. Reordered the list and put per user settings at the top and right next to one another - this is for better viewing experience for the users.

**Comment by yaustar** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/16639049/201397027-e62e3c80-e207-4c00-8c6b-ca62cbbc6d97.png">

**Comment by yaustar** [comment]
Wondering if we should call these 'project settings' or something that doesn't mention users
<img width="472" alt="image" src="https://user-images.githubusercontent.com/16639049/201397266-5b4792a5-74ef-4f17-8ef9-412b96c6077e.png">

Reading that without context could make users think these settings apply across branches (which they don't)

**Comment by yaustar** [comment]
Fixed in 1.23.3 release https://github.com/playcanvas/editor/releases/tag/v1.23.3
