### ISSUE TITLE
Selection highlights in hierarchy panel not working consistently

### ISSUE THREAD

**Issue by RipcordDev** [playcanvas/editor#82]
### Description
Using PlayCanvas editor in Chrome v81-v83. Selection highlights on objects in the project hierarchy stop working as expected.  Some item names will not receive a black background highlight when selected, making it difficult to tell which item is selected.  Sometimes item names will retain a dark grey background whether selected or not.  The item icons continue to change from grey to white as expected.

![selection1](https://user-images.githubusercontent.com/60748378/82934050-e5d37380-9f58-11ea-97e6-d34ed42ac1ea.jpg)
**Templates** item is selected.  Black selection highlight and white icon as expected

![selection2](https://user-images.githubusercontent.com/60748378/82934150-0bf91380-9f59-11ea-84fe-55ec790ed889.jpg)
**Button** item is selected.  Only the icon turned white, the background turned dark grey which is the same as other items in the hierarchy.  Not sure why some of the items have a dark grey highlight.

### Steps to Reproduce
This seems to happen after a project has been open for some time.  The hierarchy selection behaves as expected when I first open a project.  This has been seen in multiple projects over the last couple of weeks.

Open PlayCanvas editor in browser
Select any object in the project hierarchy.

_Unfortunately I haven't figured out if there's something specific I'm doing to cause this behaviour.  I'd be happy to update this report if I can pinpoint some reproducible steps._

Expected:
Item name receives a black background highlight.  Item icon turns from grey to white.  Previously selected item name returns to normal state (no highlight, grey icon).

**Comment by vkalpias** [comment]
Hi thanks for reporting this issue. I haven't been able to reproduce it yet but please let us know if you figure out any specific steps as it would help us a lot!

**Comment by willeastcott** [comment]
I've been seeing this a lot too. I'll see if I can repro the steps.

**Comment by RipcordDev** [comment]
@vkalpias I haven't been able to figure out any specific steps yet.  I've been working in PlayCanvas for a few hours this morning and noticed that it started happening again on a few of the items in my hierarchy.  

I've been doing a lot of linking work with UI elements, dragging to make them children of other objects, assigning them as the "Image" for buttons, etc.

I've kept the console open in Chrome in case there were any errors popping up, but nothing yet.  I'll keep you posted if I'm able to reproduce this more consistently.

**Comment by willeastcott** [comment]
No reliable way to reproduce this was ever reported. And I have not noticed this phenomenon for a long time. Closing. Please reopen if you believe this still to be a problem.
