### ISSUE TITLE
Camera dropdown list no longer scrolls

### ISSUE THREAD

**Issue by brianruggieri** [playcanvas/editor#821]
### Description

This may be a bit of an edge case with how my team sets up many cameras in a scene, but a long list of cameras is now limited by the height of the scene view canvas. From what I recall, this list used to scroll. It would be beneficial for us if that functionality was restored.

### Screenshots

![Screen Shot 2022-07-07 at 7 57 21 AM](https://user-images.githubusercontent.com/2104689/177768142-db637142-b6c4-4666-9b76-6856e67c0b3d.png)
![Screen Shot 2022-07-07 at 7 57 27 AM](https://user-images.githubusercontent.com/2104689/177768155-a0703994-f188-4200-8948-c26617da1990.png)

**Comment by jiajasper** [comment]
I like Steven's suggestion, if no camera is selected in hierarchy, "Camera" would not show up in the dropdown.

We also have a ticket regarding using the dockable camera viewport to entire "Camera" view
#795

**Comment by yaustar** [comment]
> I like Steven's suggestion, if no camera is selected in hierarchy, "Camera" would not show up in the dropdown.

I didn't make this suggestion 😅 The camera has to be enabled otherwise the editor view doesn't render correctly when the camera is selected

I think it would be better if the editor view did render as though it was enabled as it makes editing/positioning cameras easier without having to enabled/disable cameras

**Comment by yaustar** [comment]
Oh wait, you don't want any cameras in the list at all? That's a big UX departure from the current known behaviour now 🤔

**Comment by yaustar** [comment]
I don't think we can do that till with have https://github.com/playcanvas/editor/issues/262 in place to filter all the cameras in the hierarchy view at least

It's also an extra step to find the camera in the hierarchy view first when now, it's an easy to find list under the view dropdown

**Comment by jiajasper** [comment]
We can rename "Camera" to "Selected Camera" and make it a generic option (which means that it would not read camera entity's name)

if no camera is selected, the "Selected Camera" option still shows up in the dropdown, but it would be disbled. When hovered over, our tooltip will prompt users to select a camera entity first. Once a camera is select from the hierarchy, then "Selected Camera" option in the viewport will become enabled to be selected.

**Comment by yaustar** [comment]
@brianruggieri - What do you think about the above proposal as your team is a power user of the current dropdown?

**Comment by brianruggieri** [comment]
@yaustar for our use case, I think we like the option of all cameras listed in the separate dropdown to avoid digging through the hierarchy. Ultimately we disable all the cameras in our scene but do typically have them enabled as we set up all these different "views". The amount we use just becomes a problem if that list can't scroll. 

Great to know about that workaround. I was not aware of that feature with the camera preview.

**Comment by yaustar** [comment]
Fixed in https://github.com/playcanvas/editor/releases/tag/v1.21.70

**Comment by rstander-EL** [comment]
Thank you for fixing that guys
