### ISSUE TITLE
Select Text > Find in Files - not working anymore

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/editor#829]
Previously selecting some text in IDE and then hitting `Ctrl + Shift + F` would open Find in Files and search for selected text. After changes in Find in Files this feature has been lost.

### Steps to Reproduce

1. Open Editor IDE
2. Select text
3. Hit `Ctrl + Shift + F`

Expected: new tab (Find in Files) with searching of selected text.
Actual result: it opens new tab (Find in Files), but does not use selected text.

**Comment by yaustar** [comment]
Did it use to work? I don't remember this but have found the absence of this annoying!

**Comment by slimbuck** [comment]
Me too!

**Comment by OlegGedzjuns** [comment]
> Did it use to work? I don't remember this but have found the absence of this annoying!

Yeah, this worked before.

**Comment by yaustar** [comment]
Ah, I bet this was because we've moved the find in file search bar to the find results a few releases back 🤔

**Comment by jpauloruschel** [comment]
Fix is merged and will be available on the next Editor release (v1.21.81).
