### ISSUE TITLE
Component + Entity List Clean up

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/editor#830]
Please see Figma link for updated component list and entity list: https://www.figma.com/file/USwW0a6rU12PJkcz4wfwzg/PlayCanvas-Editor?node-id=267%3A27218

Image preview below:
![image](https://user-images.githubusercontent.com/30747200/179039547-f18500c9-7717-4748-a937-bc253d860c18.png)

**Comment by yaustar** [comment]
I wonder if we should put all the legacy components in a legacy sub menu from root so they are completely out of way and won't confused new users?

**Comment by jiajasper** [comment]
> I wonder if we should put all the legacy components in a legacy sub menu from root so they are completely out of way and won't confuse new users?

Thats a good idea!

**Comment by jiajasper** [comment]
[PlayCanvas New Icons.zip](https://github.com/playcanvas/editor/files/9154221/PlayCanvas.New.Icons.zip)

@josflesan here you go, let me know if they work.

**Comment by yaustar** [comment]
Added in https://github.com/playcanvas/editor/releases/tag/v1.21.70

**Comment by yaustar** [comment]
Note that we didn't move legacy components to it's own area
