### ISSUE TITLE
Expose new material properties

### ISSUE THREAD

**Issue by GSterbrant** [playcanvas/editor#832]
### Description

- [x] Add support for specular maps and tint using the metalness workflow.
- [x] Add support for specularity factor maps and tint.
- [x] Add support for changing the colour encoding of the specular map in both workflows.
- [x] Add support for refraction factor as map and scalar.

**Comment by willeastcott** [comment]
@GSterbrant Presumably, the current status has updated since this issue was originally logged. Worth updating the task list above? Are you still planning on doing everything listed above? ('refraction factor' is presumably pretty much done...)

**Comment by yaustar** [comment]
Done and released
