### ISSUE TITLE
Remove size limit of the tree-view pane of the Assets panel

### ISSUE THREAD

**Issue by rstander-EL** [playcanvas/editor#836]
Feature Request: Make the assets window scalable as big as user wants it

Description:
The assets folders panel/window does not go big enough to see whole file names without having to scroll. Scrolling left to right is a pain and a big time waster. I would like to have that section not be restricted in how much I can scale it to left/right (mostly to the right). I have lots of assets to organize and keep track of and so I've a lot of folders. When you have many levels of folders you can' see the name details like version numbers and such that I need to see at quick glances. 

![playcanvas_FeatureRequest](https://user-images.githubusercontent.com/77989269/179803459-601dd49c-24c4-4671-823a-f4ce0d10cf54.jpg)

**Comment by rstander-EL** [comment]
Oh another issue is that once you have many folders open you can't resize the space. I have to go and close all the folders to make the space bigger then reopen my folders. 

Browser: Chrome

**Comment by willeastcott** [comment]
I've doubled the Assets panel's folder view max width from 300 to 600.
