### ISSUE TITLE
Switch to Master branch button doesn't work when opening a project from a closed branch

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#838]
Thread: https://forum.playcanvas.com/t/cant-open-from-closed-branch-switch-to-master-branch/26695

Create a project and add two users to it
Create a branch (b1) and switch to it with User A
Close tab
With User B, close branch b1
User opens the Editor
When they try to click the button to Switch to Master, it doesn't work

Error:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/16639049/180267168-97b7369f-805c-4265-84d9-a0a71cb09101.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/16639049/180267275-2464818d-6037-4d59-9dc3-e4ba26885fc3.png">

**Comment by ellthompson** [comment]
Fixed in release [1.21.67](https://github.com/playcanvas/editor/releases/tag/v1.21.67)
