### ISSUE TITLE
Lightmap size doesn't update until entity is unselected and reselected

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#843]
Create a primitive
Enable Lightmapped
See that the Lightmap size is inf - inf
Unselect entity and select it again
Lightmap size is 32
Change the multiplier to 64
Lightmap size is unchanged
Unselect entity and select it again
Lightmap size is 256 (why 256?)

https://user-images.githubusercontent.com/16639049/180971037-d16ffe89-c44c-46dd-aac4-d1e4bafc2319.mp4

**Comment by sri-30** [comment]
https://github.sc-corp.net/PlayCanvas/monorepo/pull/1568
