### ISSUE TITLE
Context menu broken icons

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#847]
The context menu has lost some of the icons, like the shapes:

![image](https://user-images.githubusercontent.com/5677782/181340128-72f9c8a5-2f24-4624-acea-6b60f5982e44.png)

**Comment by yaustar** [comment]
We've updated the icons so it needs a hard refresh at the moment (Ctrl / Cmd + Shift + R) 

We are investigating how to best bust cache this.

**Comment by yaustar** [comment]
Fixed in v1.21.71
