### ISSUE TITLE
Archived project zips with chinese characters in the filename will not import

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#848]
Export a project 
Change the filename to have chinese characters (幸福)
Attempt to import into PlayCanvas
Error message will come up saying it can't import

Workaround is to remove the chinese characters from the ZIP filename and import

**Comment by yaustar** [comment]
I ran into this issue again with `™` and `®`

**Comment by yak32** [comment]
the fix will be deployed with the next release

**Comment by yaustar** [comment]
Fixed in 1.23.3 release https://github.com/playcanvas/editor/releases/tag/v1.23.3
