### ISSUE TITLE
Engine 1.55 spams errors with Editor when selection an entity with collision

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#853]
Project: https://playcanvas.com/project/966363/overview/155-crash-in-editor

Select cube. It spams errors and locks editor

https://user-images.githubusercontent.com/16639049/182885074-3686ebac-069b-4035-88ec-6f3ddd739eeb.mp4

Temp fix is to add `?use_local_engine=https://code.playcanvas.com/playcanvas-1.54.1.js` to the end of the scene URL

eg https://playcanvas.com/editor/scene/1493014?use_local_engine=https://code.playcanvas.com/playcanvas-1.54.1.js

**Comment by slimbuck** [comment]
This is fixed.
