### ISSUE TITLE
Editor marks user scripts to not preload and exclude

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#854]
Whenever there is a new patch (Editor release) is pushed, while the project is opened, the user scripts are marked to be excluded and not to preload. Spent a morning to figure out why the project stopped working, and found the scripts were marked as excluded and non-preloaded. Marked them back, and the thing repeated again a few minutes ago. It looks like it is related to the Editor patch being pushed, while the project is opened.

Edit:
Not all user scripts are affected. It somehow affects only some of them, while others remain fine. The same scripts that were excluded earlier returned back to being excluded again.

**Comment by yaustar** [comment]
> Whenever there is a new patch is pushed

What do you mean by 'patch'?

**Comment by LeXXik** [comment]
I mean the scripts situation happened right after:
https://github.com/playcanvas/editor/releases/tag/v1.21.73

**Comment by yaustar** [comment]
Ah, so you mean an Editor release

**Comment by slimbuck** [comment]
Oh wow this is an amazing observation @LeXXik thanks! We'll definitely investigate.

**Comment by LeXXik** [comment]
Just happened again. The scripts reverted to be excluded and not to preload. Unless there was an Editor release, it must be something else then.

**Comment by yaustar** [comment]
No editor release on our side

**Comment by marklundin** [comment]
Just to flag that the @LeXXik is currently testing the beta version of the PCPM package manager which needs to exclude source scripts and and not preload them. 

However, if this is happening without a package.json in the root of the registry (ie. It’s not intentional) then this may well be a bug in the PCPM extension and not the PC editor

**Comment by marklundin** [comment]
@LeXXik  I've looked into this further and this is an [issue](https://github.com/marklundin/pcpm/issues/5) with the package manager extension not the editor. This can probably be closed

**Comment by LeXXik** [comment]
Good catch, @marklundin! Thank you. Closing the issue.
