### ISSUE TITLE
Add 'support area lights' tickbox to the Editor to allow Area Lights to be used.

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#859]
Area lights implementation depends on a LUT table (two float arrays) in order to render them. The engine has an API, that allows the binary file containing those to be set:

`app.setAreaLightLuts(assets.luts);`

In the Editor Settings->Rendering, we have a place to specify Area Lights Data asset. (unreleased feature).

But as this is an internal data file, the ideal solution would be for the user to not have to manage this file, and only tick a check box to require this data to be available for the project.

Proposed solution: In Editor Settings->Rendering, add 'Area Lights Support' checkbox (and remove current unrelease asset link). Store a copy of the LUT tables (current binary format, but probably even better .js file containing the float arrays), and make it available to the engine when the project runs.
When this is checked:
- if the project is running in the launcher, download the lut.js file and add it to the launcher page.
- If publishing / exporting project, include the lut .js file in it.

This is the .js file, which contains the LUT tables (two float arrays), as well as code which converts those into a single binary file.
https://github.com/playcanvas/engine/blob/main/examples/assets/scripts/utils/area-light-lut-bin-gen.js
Likely a file with just the two arrays is needed.

**Comment by willeastcott** [comment]
This has now been added to `SETTINGS` > `RENDERING`:

![image](https://user-images.githubusercontent.com/697563/198041677-e93a5832-140e-4c4d-81df-5ed913aaf010.png)
