### ISSUE TITLE
Be able to collapse all children's children in hierarchy view 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#861]
In a scenario like this:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/16639049/184886026-c7670bf7-d477-434b-af24-86121476112c.png">

It would be useful to be able to collapse the all the children's children in the hierarchy view to this state 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/16639049/184886416-e7dccadb-0fa5-4300-9cf2-682e1e576167.png">

Suggestions have been to have a right click option on the parent to do this
<img width="409" alt="image" src="https://user-images.githubusercontent.com/16639049/184886522-be6a47db-6de6-4ad7-ad5d-7f82cf5b0c36.png">

**Comment by yaustar** [comment]
@jiajasper UX design pass please?

**Comment by yaustar** [comment]
Ah, that's an interesting workaround @lucaheft !

**Comment by lucaheft** [comment]
Yeah, i think that's the default for most applications. Unity does it the same way.
I don't think there is a need to clutter the context menu with an extra option for this.

**Comment by willeastcott** [comment]
@lucaheft is correct - that's how a PCUI `TreeView` works. Should probably be mentioned in the Editor docs on the developer site.

Closing.
