### ISSUE TITLE
[bug report] PlayCanvas' editor can't import fbx with embedded textures

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/editor#866]
You can follow [this tutorial](https://www.youtube.com/watch?v=kEP34CbPWUo) to see how to export fbx with embedded textures in blender. There are tons of [gltf models](https://github.com/KhronosGroup/glTF-Sample-Models) that can be converted to fbx for this test.

Here's a video showing the problem

https://user-images.githubusercontent.com/5656275/185434882-f26217be-2336-4e1d-a288-680ec6dd72ce.mp4

**Comment by slimbuck** [comment]
Hi @marcusx2,

PlayCanvas definitely does support importing FBX with embedded textures :) 

Are you struggling with a specific FBX? If you can share it with us, perhaps we can take a closer look.

Thanks

**Comment by marcusx2** [comment]
PlayCanvas can import FBX with embedded textures, but not if the FBX has embedded textures the way it's done in Blender. Watch the video. If you embed the texture the way the video describes, PlayCanvas always fails to import it.

**Comment by slimbuck** [comment]
Ahh I see. Are you able to share the failing fbx so we can investigate?

**Comment by yaustar** [comment]
After looking at the GLB models you've sent us via email, it looks like there is an issue with the Blender FBX exporter (or settings) as neither FBX Review from Autodesk nor Unity will import/render the embedded textures in the FBX either.

In the short term (if you cannot resolve this with Blender) is to upload the textures separately by unpacking the GLBs using a tool like https://github.com/bghgary/glTF-Shell-Extensions to get the textures
