### ISSUE TITLE
Reimport FBX when created with folder

### ISSUE THREAD

**Issue by ellthompson** [playcanvas/editor#867]
### Description

The editor provides the option to import .fbx files into their own folder. This helps with organisation when importing multiple files. However when reimporting .fbx files, it is necessary to select into each folder and import them individually. The editor should support reimporting multiple .fbx files at once, even if they are in separate folders.

**Comment by jpauloruschel** [comment]
Fix has been merged and will be available on the next Editor release (1.21.81).

**Comment by yaustar** [comment]
[Test archive.zip](https://github.com/playcanvas/editor/files/9423815/Test.archive.zip)

Tested with this set of FBX's and it duplicates the the folders on Production

https://user-images.githubusercontent.com/16639049/186641340-88c1df82-342a-4d40-8903-11e5895c42b8.mp4

**Comment by yaustar** [comment]
This has been fixed
