### ISSUE TITLE
Activate Anim component by script doesn't work

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#875]
If you deactivate the Anim component in the editor and then activate it by script, the animation will not start. (Only when you make a change in the Anim State Graph at runtime in the editor after activating does the animation come to life).

![image](https://user-images.githubusercontent.com/52896137/187521030-6a548d18-6275-4992-8c93-f53c01ef167b.png)

![image](https://user-images.githubusercontent.com/52896137/187521139-5a10c1cb-f559-4427-ba82-e5440a05b52f.png)

https://playcanvas.com/project/975610/overview/animactivate

**Comment by yaustar** [comment]
`activate` is only used on a scene load https://developer.playcanvas.com/api/pc.AnimComponent.html#activate

You need to set `playing` to true to start the animation: https://developer.playcanvas.com/api/pc.AnimComponent.html#playing

Example project: https://playcanvas.com/project/975773/overview/f-animactivate

```
KeyboardControls.prototype.keyDown = function (e) {
    if ((e.key === pc.KEY_P) && (this.entity.anim.baseLayer.activeState !== 'Punch')) {
        this.entity.anim.playing = true;
        this.entity.anim.setBoolean('punch', true);
    }
};
```

**Comment by yaustar** [comment]
@ellthompson What's the reason for having the `activate` property? Could the user set the `playing` property to true on animation creation?
