### ISSUE TITLE
Anchor preset "Fill"/"Stretch" for elements

### ISSUE THREAD

**Issue by Ciberusps** [playcanvas/editor#876]
Anchor preset `(0, 0, 1, 1)` aka "Fill"/"Stretch" is one of the most used presets but there is no option in the editor, its boring to fullfill it by hand everytime and then reset all margins to 0, will be awesome to have such option
![image](https://user-images.githubusercontent.com/14001879/187529503-862b442c-f343-4df4-9c13-c40202515b16.png)

UPD: Moved anchor selection enhancement to #877

**Comment by yaustar** [comment]
For the scope of the ticket, we should include just the presets for fill/stretching on particle axis and have a separate ticket for an Editor UI rework.

**Comment by Ciberusps** [comment]
Moved anchor selection enhancement to #877

**Comment by yaustar** [comment]
Done on our internal repo. Waiting review and merge.

**Comment by yaustar** [comment]
Released in 1.23.2
