### ISSUE TITLE
New Dashboard - Leaving a project that is not owned by me or an ORG I own doesn't work

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#880]
https://user-images.githubusercontent.com/16639049/189134122-9bf7adbb-ae98-48f6-900a-342652475031.mp4

- User A creates a project and adds User B
- User B tries to leave a project but can't

**Comment by jpauloruschel** [comment]
Potential fix has been deployed. Can you verify?

**Comment by yaustar** [comment]
It 'works' but it still takes me to the project 'page'

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/16639049/189380300-7eb74f4a-f03f-4b37-a1ed-3486c682e2ea.png">

And is still on the project list unless I refresh:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/16639049/189380359-a1610d1b-08e5-4654-86e0-4ea1c88c8d81.png">

**Comment by jpauloruschel** [comment]
Let's keep this ticket open to track this other issue. By looking at it now, I agree that it is confusing and the project should no longer appear in the list.
