### ISSUE TITLE
Uploaded thumbnails are returning 403s

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#885]
Thread: https://forum.playcanvas.com/t/problem-about-the-game-artwork-logo-of-the-project/27543
Example project: https://playcanvas.com/project/984914/overview/test-project-for-logo

<img width="918" alt="image" src="https://user-images.githubusercontent.com/16639049/191247079-4db9b26e-b7aa-40ef-a774-5282c5d9a4aa.png">

The image doesn't seem to be the issue here as I've tried myself with the same file

**Comment by yaustar** [comment]
Issue is due to the project been owned by an ORG. We have a fix due to deploy today

**Comment by yaustar** [comment]
Confirmed fix deployed.

**Comment by willeastcott** [comment]
Appears this is fixed. Closing.
