### ISSUE TITLE
manifest.json 404s if the trailing `/` is removed in published link

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#887]
Thread: https://forum.playcanvas.com/t/solved-manifest-json-404s-and-timeouts-on-newly-published-playcanvas-build/26790/

https://playcanv.as/p/xrWromyG/ is fine but using https://playcanv.as/p/xrWromyG would give `GET https://playcanv.as/p/xrWromyGmanifest.json 404` as it looks like we may be generating paths based on the URL?

**Comment by yak32** [comment]
fix is going to be merged soon

**Comment by willeastcott** [comment]
Closing as fixed.
