### ISSUE TITLE
Unwanted suffix added to object names when Imported FBX has objects with modifiers.

### ISSUE THREAD

**Issue by Nickneem** [playcanvas/editor#899]
An unwanted suffix is added to object names when an imported FBX has objects with modifiers.

[Example Project](https://playcanvas.com/editor/scene/1557724)

The FBX in the project has two objects.
Object01 - No modifier. Name is correct: Object01
Object02 - Has modifier. Name is 'incorrect': Object02.001

An example from a WIP Project where the object data name is set correctly in Blender:
![BlenderPC](https://user-images.githubusercontent.com/66830838/195131215-999b644e-58c4-4862-a17c-5873c0386a82.png)

**Comment by willeastcott** [comment]
I just imported this FBX in some other apps and the `.001` extension on `Object2` is not present. So I'm confident this is coming from our import pipeline. @slimbuck, any thoughts on why this might be happening (mitigating name collision, etc)?

**Comment by slimbuck** [comment]
Hi @Nickneem,

Our code gets the mesh name directly from the FBX SDK.

If I import your FBX model into Blender I get the following:

<img width="441" alt="Screenshot 2023-03-06 at 13 20 48" src="https://user-images.githubusercontent.com/11276292/223122106-f5d4a1ea-22a4-4135-a481-c5bc52ba2c58.png">

Which seems to match exactly the hierarchy PlayCanvas creates.

**Comment by slimbuck** [comment]
Closing because WAD.

If I've missed anything at all please reopen here and I'll take a further look!

**Comment by willeastcott** [comment]
Yeah, I agree with @slimbuck here. If you actually instantiate the template in the hierarchy, you get:

![image](https://user-images.githubusercontent.com/697563/223225669-b4c5f31a-9f47-47f4-93f2-0491c5710653.png)

So it is correct.
