### ISSUE TITLE
Rename master branch to main/Allow user to rename the master branch

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#900]
For those that are using version control workflows in additional to the PlayCanvas VC, being able to rename the master branch would help a lot

**Comment by dexterdeluxe88** [comment]
Please also consider having "Main" as the default wording instead of "Master" due to inclusive language

**Comment by yak32** [comment]
pr created

**Comment by yaustar** [comment]
Fixed in 1.23.3 release https://github.com/playcanvas/editor/releases/tag/v1.23.3
