### ISSUE TITLE
REST API download endpoint returns 400 error

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#902]
https://developer.playcanvas.com/en/user-manual/api/app-download/ 

Report: https://discord.com/channels/408617316415307776/408617316415307778/1031655993387515914

Checked myself with a known working config and the same config works for the archive/export endpoint

**Comment by yaustar** [comment]
Reverted the deploy from today

**Comment by slimbuck** [comment]
This should now be resolved.
