### ISSUE TITLE
Add a joint component to the inspector panel

### ISSUE THREAD

**Issue by querielo** [playcanvas/editor#903]
Right now, a user of the editor cannot add and edit [the joint components](https://github.com/playcanvas/engine/tree/main/src/framework/components/joint) in `editor.call("layout.attributes")`.

Similar situation with [the zone component](https://github.com/playcanvas/engine/tree/main/src/framework/components/zone). But it can be replaced by the collision component.

**Comment by querielo** [comment]
@willeastcott Is it correct that there is some kind of protection from adding this kind of components on the server side?

<img width="607" alt="Screen Shot 2022-10-26 at 09 40 41" src="https://user-images.githubusercontent.com/104348270/197944988-83c77dc6-6a39-4c10-b43b-0ecf11ab5574.png">

**Comment by willeastcott** [comment]
Yes, that's correct. You can currently only use the `JointComponent` at runtime. The API was never 100% finalized. It would be great to get it finished and integrated into the Editor.
