### ISSUE TITLE
Deleting builds ADDS to project size rather than removing

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#904]
Take note of the project size, delete an old build and see how the project size goes UP instead of down by the build size

https://user-images.githubusercontent.com/16639049/197236273-7d9d0f28-9d1b-45c3-aaed-3a09dbadd44b.mp4

**Comment by yak32** [comment]
adds to total user usage as well

**Comment by yak32** [comment]
fix will be deployed with the next release of the editor

**Comment by yak32** [comment]
the fix is merged
