### ISSUE TITLE
How to get the current scene name

### ISSUE THREAD

**Issue by 792747481** [playcanvas/editor#909]

**Comment by yaustar** [comment]
In the Editor, you can go to Settings and get/change the scene name 

<img width="183" alt="image" src="https://user-images.githubusercontent.com/16639049/198027119-f34776b2-f679-4c7d-ac57-0898a21ca4ac.png">


<img width="412" alt="image" src="https://user-images.githubusercontent.com/16639049/198027094-247d9cd9-c8b6-461b-8cc5-569574e48aff.png">

**Comment by yaustar** [comment]
For these types of questions, please use the forums :) https://forum.playcanvas.com/
