### ISSUE TITLE
Cannot set material texture transform rotation back to 0

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#910]
Forum: https://forum.playcanvas.com/t/rotation-feature-wont-accept-value-of-0/28099

Give texture transform a rotation value 
Note that you cannot set it back to 0 again

https://user-images.githubusercontent.com/16639049/197958225-1196cc5e-ff16-42cd-b9f9-ad22f1080e5e.mp4

**Comment by willeastcott** [comment]
The fix is now deployed to production. Closing.
