### ISSUE TITLE
observer.js throws 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by ertugrulcetin** [playcanvas/editor#911]
I’m trying to render my terrain on the editor (from heightmap) and somehow play-canvas/observer library throws an error and I can not manipulate the editor.

Any ideas to solve this?

Here is the error;
<img width="463" alt="Screen Shot 2022-10-30 at 20 43 18" src="https://user-images.githubusercontent.com/8271291/198901082-2d3e48c4-e571-438f-9403-50d307c9ab8d.png">

### Steps to Reproduce

1. Generate `meshInstances` from heightmap
2. Attach render component to an entity with `meshInstances`

**Comment by yaustar** [comment]
Can you provide a project/full example for us to try and repro please?

**Comment by ertugrulcetin** [comment]
This was on me - it's resolved in [this post](https://forum.playcanvas.com/t/playcanvas-observer-js-throws-maximum-call-stack-size-exceeded/28152/11)
