### ISSUE TITLE
Increase sensitivity of the local rotation parameter.

### ISSUE THREAD

**Issue by querielo** [playcanvas/editor#912]
Suggestion: set [the step parameter of VectorInput](https://github.com/playcanvas/pcui/blob/main/src/VectorInput/index.js#L24) of the local rotation parameter as 10 or at least 5. Right now, it is hard to change the value with a mouse. If a user needs to set precise angles they can use keyboard.

<img width="512" alt="Screen Shot 2022-10-31 at 17 59 38" src="https://user-images.githubusercontent.com/104348270/199081551-b3f5a46e-cc1e-4142-9b40-9615bcb81223.png">

**Comment by yaustar** [comment]
We have a similar issue here: https://github.com/playcanvas/editor/issues/129 with some proposed solutions

**Comment by willeastcott** [comment]
I've modified the sensitivities. Before, a modest mouse movement of approximately a couple of inches gave:

![before](https://user-images.githubusercontent.com/697563/199214818-f4ed5ea4-4991-4c3e-b4fa-54246fe3c564.gif)

Now:

![after](https://user-images.githubusercontent.com/697563/199214842-b069275f-cb71-4ba9-bdff-dab9f8d8dc7a.gif)

If that looks like an improvement, I can submit + deploy an update.

**Comment by willeastcott** [comment]
This is now deployed. @querielo, can you give it a try and let us know if you're happy with the new sensitivity?

**Comment by willeastcott** [comment]
Gonna assume the update is acceptable. If not, feel free to reopen the issue. 😄

**Comment by querielo** [comment]
Thanks!!!
