### ISSUE TITLE
Code Editor - F2 renaming variables has low contrast in the UI

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#917]
![image](https://user-images.githubusercontent.com/16639049/199974908-c7043781-7699-4860-b5f5-b7da2fcd2f4a.png)

**Comment by willeastcott** [comment]
This is an issue with Monaco, not PlayCanvas. Go here:

https://microsoft.github.io/monaco-editor/

Select Visual Studio Dark as the theme:

![contrast](https://github.com/playcanvas/editor/assets/697563/777a892e-143a-4101-8097-8c7b6f62a3ef)

I'm closing this but feel free to log against Monaco's repo.
