### ISSUE TITLE
Mouse wheel for zoom, does not pick UI elements.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#92]
When using mousewheel to zoom, in Editor it first figures out point in world where mouse is pointing. Then it figures out distance it has to zoom. So for object far away it moves more, and objects close it moves less forward. This is nice and useful, especially working with large scenes.

But UI element are not pickable, this leads them to be ignored.

Here is a project: https://playcanvas.com/project/692472/overview/mouse-wheel-issue
Steps to reproduce:
1. Open Editor
2. Have both boxes (small and large) in view.
3. Ensure large box (red) is behind objects at origin.
4. Hover mouse on small box (blue)
5. Use mouse wheel to move forward/back (working as intented).
6. Hover on Image element (green)
7. Use mouse wheel to move forward/back
Issue - mouse picker ignores elements, leading to wrong distance estimation, so scrolling is too fast.

**Solution: Ensure UI Elements are pickable by Editor for mouse wheel.**

![image](https://user-images.githubusercontent.com/636263/83941874-7af72780-a7f7-11ea-86a7-599eb2f6af12.png)

**Comment by jpauloruschel** [comment]
Building up on this, actually this happens with any object that has a non-opaque Material assigned to it.

**Comment by jpauloruschel** [comment]
Fix has been merged and will be available in the next Editor release. Closing ticket.
