### ISSUE TITLE
solution needed for samsung tablet with s pen

### ISSUE THREAD

**Issue by g1i1U** [playcanvas/editor#921]
### Steps to Reproduce

1. run on samsung tablet with s pen
2. can not do anything on canvas

**Comment by willeastcott** [comment]
I have actually just opened a pull request which adds touch (and pen) support to the 3D view of the Editor. It uses pointer events to abstract user input. It's not quite done but hopefully I can merge it in the next week or two.

**Comment by willeastcott** [comment]
This is a duplicate of https://github.com/playcanvas/editor/issues/128. Closing.
