### ISSUE TITLE
Feature Request: Editor TypeScript Support

### ISSUE THREAD

**Issue by MarshallBelles** [playcanvas/editor#924]
It would be great to have TypeScript support with code completion, syntax and error highlighting.
I personally think this is the most desirable missing feature from PlayCanvas.

Regarding code completion and error highlighting, I would take a look at https://github.com/coder/code-server if you don't know about it - extracting the already-proven VS Code browser is a no-brainer to me. I think you could still maintain complete control over the cloud editor IDE with minimal effort.

If you are open to a professional partnership then you should reach out to https://coder.com/ and see if they can help. 
I'm not affiliated with them in any way, but I have used their workspaces.

Thanks, and cheers!

**Comment by yaustar** [comment]
We are looking to do this as part of the work in this ticket https://github.com/playcanvas/engine/issues/4767

**Comment by MarshallBelles** [comment]
> We are looking to do this as part of the work in this ticket [playcanvas/engine#4767](https://github.com/playcanvas/engine/issues/4767)

Ah, good, that makes this a duplicate. Closing.

**Comment by marklundin** [comment]
Added this ticket to track work https://github.com/playcanvas/editor/issues/1195
