### ISSUE TITLE
Update the version of Ammo in Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#934]
Forum: https://forum.playcanvas.com/t/playcanvas-physics-extension/13737/28?u=yaustar

Bullet3 also fixes an issue that is coming increasing common in metaverse/mmo/open world games from Leonidas: "One thing that bullet3 also solves is capsule colliders following through large mesh colliders (e.g. terrains)."

Do we look at a minor version bump and test against it or try Bullet3?

**Comment by willeastcott** [comment]
This build of ammo imported by the Editor has been updated since this issue was logged. The forum post mentions the need for `ClosestConvexResultCallback` - this is now available in the version imported by the Editor.
