### ISSUE TITLE
Incorrect Half Extents of Collision Component when parent entity is scaled

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#939]
If the parent entity of an entity with Collision Component has no scale of 1, the Half Extents do not match with the size of the entity anymore. This makes it almost impossible to match the collision with the size of the actual model. There is probably a logical reason for this, but I don't think this is the right way.

In the example below the parent entity has a scale of 0.25. The Half Extents should be 0.5 to match with the model.

![image](https://user-images.githubusercontent.com/52896137/204269838-0c126e87-4be5-471c-ac58-f9c61a73dff5.png)

**Comment by yaustar** [comment]
This is as designed as half extents are in world space/size.

**Comment by albertvanveen** [comment]
Why you close it so fast? How the user can give the collision the correct scale this way?

**Comment by yaustar** [comment]
I closed it because it's correct to the design of the feature and won't be changed.

In the image, the blue box (that represents the collision shape) is the the correct size according the the half extent values

**Comment by yaustar** [comment]
What it sounds like you want is a toggle to have the shape be affected by the entity scale that will require an engine level change

**Comment by albertvanveen** [comment]
The Half Extents for the enitity that has the Collision Component is 2. Not 0.5.

**Comment by yaustar** [comment]
And the blue box is 4 units wide/tall/deep so it's the correct size

**Comment by albertvanveen** [comment]
So you use a calculator to match the collision size with the model?

**Comment by yaustar** [comment]
Half extents is half the width/height/deep of the shape. Times it by 2 and you get the full size.

I use the viewport to size 

https://user-images.githubusercontent.com/16639049/204275068-d5fcac3f-9323-4b59-a32c-cd3a45ded9e6.mp4

the shape and sliders to get it right

What it also sounds like is that you would prefer to have viewport gizmos to size the shape instead

I understand what you are getting at but the ticket title implied it's a bug by saying it's 'incorrect', hence closing the ticket

**Comment by albertvanveen** [comment]
You said the Half Extents are in world space. That's not correct reading the discription.

![image](https://user-images.githubusercontent.com/52896137/204275890-d46fd3ce-aa42-418a-bf1a-e85d2194d224.png)

**Comment by yaustar** [comment]
Hmm... that needs to be updated as the API has been updated a while back to remove mention of local space: https://developer.playcanvas.com/api/pc.CollisionComponent.html#halfExtents

**Comment by albertvanveen** [comment]
So it was previous in local space but is now in world space?

**Comment by yaustar** [comment]
For as long as I've been at PlayCanvas, it's never been in local space. I think the original intention is to say that it's rotated to match the Entities rotation hence why the API description makes more sense

**Comment by albertvanveen** [comment]
Anyway, the current design is confusing and user unfriendly. I've edited the title and reopened the issue.

**Comment by albertvanveen** [comment]
Anyway, the current design is confusing and user unfriendly. I've edited the title and I like to reopened the issue.

**Comment by yaustar** [comment]
I will create a new ticket for you that is more accurate to what you want
