### ISSUE TITLE
Uncaught DOMException when clicking on animation

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/editor#943]
When I click on an animation of the Anim Component of an entity I get the error below. I also get this error when I click on an animation state of the State Graph Editor. It seems to happen in all projects.

![image](https://user-images.githubusercontent.com/52896137/204934717-3ea0239c-1092-49cc-a8c4-483e6529df49.png)

![image](https://user-images.githubusercontent.com/52896137/204934932-895a0e42-ff77-4857-8132-e920b0fe170d.png)

![image](https://user-images.githubusercontent.com/52896137/204935082-531620ad-8f0e-4a6a-a386-74bfe3826bed.png)

**Comment by willeastcott** [comment]
@albertvanveen Does this issue still occur? I suspect this has already been dealt with but I want to make sure. @ellthompson - do you have more context on this?

**Comment by ellthompson** [comment]
I've tested this in various read only projects without being about to reproduce the error so I'm closing this for now.
