### ISSUE TITLE
Add reset button for color in particle system

### ISSUE THREAD

**Issue by ertugrulcetin** [playcanvas/editor#947]
I could not find how to reset the color attribute of particles. I can reset all things in here, e.g.velocity, local velocity etc.;

![Screen Shot 2022-12-06 at 22 14 13](https://user-images.githubusercontent.com/8271291/206009738-c7bf61f1-7809-4217-a6c7-b7bec3ac6ed7.png)

Here is the forum post: https://forum.playcanvas.com/t/how-to-reset-color-in-particle-system/28767/4

**Comment by yaustar** [comment]
In PR 
![Kapture 2022-12-14 at 18 00 40](https://user-images.githubusercontent.com/16639049/207672179-9ed51e21-bc97-40ca-bd1f-f280afe28eb0.gif)

**Comment by ertugrulcetin** [comment]
Looks good 👍🏻

**Comment by yaustar** [comment]
Released 1.23.8
