### ISSUE TITLE
Audio Source component should be labeled as deprecated/legacy

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#951]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/16639049/207936025-db93bffa-263d-4e26-abc2-89d61fbeb313.png">

**Comment by willeastcott** [comment]
Actually, this is a bug. All new projects for the past several years have had the legacy audio system (based on the Audio Source component) disabled. The context menu in the Hierarchy panel does not show Audio Source in the Add Component sub-menu (correctly hiding Audio Source). However, the ADD COMPONENT menu in the Inspector was never updated to hide Audio Source. I've submitted a PR to fix this, so I'm closing this.
