### ISSUE TITLE
Code Editor Ignores Key Re-Bindings

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/editor#96]
### Description

I re-binded my Caps Lock and Escape keys to be switched (vim user), and the only way for me to exit the find dialog is to press what now is my Caps Lock key. I don't actually know if this impacts all code editor keyboard inputs, but it at the very least affects exiting the find dialog.

My guess is the code editor is using the keycode, and hasn't yet moved to using `event.key`.

Experienced on: Ubuntu 19.10 / Firefox 78, Chrome 85

### Steps to Reproduce

1. Bind the escape key to another key.
2. Open the code editor.
2. Open the find dialog with Ctrl/Cmd + F.
3. Attempt to exit with the **funtional** escape key. This won't do anything unless the **physical** escape key which has been rebinded to another key is pressed.

**Comment by yaustar** [comment]
How have you rebinded the ESC/capslock key? Is this done at the OS level?

**Comment by Christopher-Hayes** [comment]
Yes, operating system level. For example, if I hit escape (but physically the caps lock on my keyboard) at https://keycode.info I see this:
![Screenshot of keycode.info](https://user-images.githubusercontent.com/6013871/86181641-6a875380-bafc-11ea-8547-5783aea44467.png)
Which actually I now realize is the correct keycode, `27` being the JS keycode for escape. So, I'm not sure why only the physical ecape key works for exiting the find dialog other than it using `event.code`.

**Comment by yaustar** [comment]
Odd, I'm just looking at the code now and it's checking against keycode 27 or 9 (tab).

Not sure why it's ignoring your bindings.

**Comment by Christopher-Hayes** [comment]
I don't have any VIM browser extension. Something to note is that it blurs focus from the dialog input field when I hit escape.
So, it seems like this is running fine:

    TextField.prototype._onKeyDown = function(evt) {
        if (evt.keyCode === 27) {
            this.blur();
        } else if (this.ui.blurOnEnter && evt.keyCode === 13) {
            var focused = false;

            var parent = this.ui.parent;
            while(parent) {
                if (parent.focus) {
                    parent.focus();
                    focused = true;
                    break;
                }

                parent = parent.parent;
            }

            if (! focused)
                this.blur();
        }
    };

I did see the code code you were referring to, it seems like the dialog has its own event listener to know when to blur focus. On top of that, there's a window event listener that decides when to close the dialog. It looks like the search field uses `event.keyCode` while the window event listener prefers `event.code`.

The code below is where it gets the keys mixed up.
```
    window.addEventListener('keydown', function(evt) {
        if (evt.target) {
            var tag = evt.target.tagName;
            if (/(input)|(textarea)/i.test(tag) && ! evt.target.classList.contains('hotkeys'))
                return;
        }

        updateModifierKeys(evt);

        var key = evt.code ? keyByCode[evt.code] : keyByKeyCode[evt.keyCode];

        if (evt.keyCode === 92 || evt.keyCode === 93)
            return;

        var index = [ ctrl+0, alt+0, shift+0, key ].join('+');

        if (keyIndex[index]) {
            var skipPreventDefault = false;
            for(var i = 0; i < keyIndex[index].length; i++) {
                if (! skipPreventDefault && hotkeys[keyIndex[index][i]].skipPreventDefault)
                    skipPreventDefault = true;

                hotkeys[keyIndex[index][i]].callback(evt);
            }
            if (! skipPreventDefault)
                evt.preventDefault();
        }
    }, false);
```
The `evt.code` gives the value `caps lock`, just like the screenshot above from keycode.info. The `evt.keyCode` will get the correct key; however, `evt.code` seems to ignore bindings.
![image](https://user-images.githubusercontent.com/6013871/86261870-1f695100-bb8d-11ea-8e84-38236bc3096a.png)

From there as you would expect any event callbacks are triggered based on the `caps lock` `evt.code`, so the `search-close` callback never is run.
![image](https://user-images.githubusercontent.com/6013871/86262224-9a326c00-bb8d-11ea-8589-fa5becf48ebc.png)

**Comment by yaustar** [comment]
Do you still have issues since we moved to Monoca Text Editor?

**Comment by Christopher-Hayes** [comment]
> Do you still have issues since we moved to Monoca Text Editor?

@yaustar not an issue on Monoco! Closing the ticket.
