### ISSUE TITLE
Fix soft particle rendering with engine v1.60

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/editor#960]
Editor doesn't render soft particles with engine v1.60, please make it work.

**Comment by mvaligursky** [comment]
we recently enabled color grab pass in the Editor to get dynamic refraction to work .. we need to do the same for depth grab for soft particles I think.

repro project: https://playcanvas.com/editor/scene/390137
and select individual effects in the scene view, to render them in the editor

**Comment by mvaligursky** [comment]
related to the new error when a texture is missing, added here: https://github.com/playcanvas/engine/pull/4972
which skips the draw call

**Comment by willeastcott** [comment]
@mvaligursky Since the engine is now on v1.61.3, is this still an issue?

**Comment by mvaligursky** [comment]
This was fixed by @yaustar by enabling depth grab on the Editor camera.
