### ISSUE TITLE
glTF asset import enhancements

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/editor#963]
This issue lists high-level work items still remaining to fully support editor glTF import in roughly priority order:

Support loading:
- [x] node hierarchy
- [x] mesh/primitive data
- [x] standard material
- [x] ratified material extensions
- [x] animated skeletons and skinning data
- [x] morph targets
- [x] cameras
- [x] draco compressed models
- [x] light support KHR_lights_punctual

**Comment by yaustar** [comment]
Material, model and animation support in Release 1.24.0
https://blog.playcanvas.com/gltf-import-arrives-in-the-playcanvas-editor/

https://user-images.githubusercontent.com/16639049/213731863-048395f5-1eff-4e81-bacd-41c38af24499.mp4

https://user-images.githubusercontent.com/16639049/213731942-a271f0a3-a47b-4129-a2ad-76b217435656.mp4

**Comment by slimbuck** [comment]
This work is now done. A follow up ticket will list additional future work.

**Comment by NworbLegin** [comment]
There is a bug in the KHR_lights_punctual import from glTF/glb where a point light is imported with an incorrect rotation setting and the inner and outer radius values have not been converted from radians to degrees.

Rotation: It looks like a point light is imported with an additional rotation of -90 degrees on the x axis
Inner/Outer Radius: These values have not been converted from radians in the glTF to the degree values required for the Editor light value.
