### ISSUE TITLE
How do I package only the ones used in the scene?

### ISSUE THREAD

**Issue by 861172923** [playcanvas/editor#97]
When publishing, the files in the project will be packaged out, and those assets that are not used will also be packaged in it, so that the ZIP package will be large, load time will increase.

How do I package only the ones used in the scene?

I hope to add this feature

**Comment by yaustar** [comment]
To directly answer your question, it be impossible for us to know what assets are used as they can be loaded dynamically by script.

However, the size of the zip is not reflective of what is downloaded by the user.

Each asset has a preload setting. Ticking this means that it is downloaded before the game starts. If assets aren't used till later in the game, you can untick this and load it at runtime when needed.
