### ISSUE TITLE
version 1.50.2 doesn't work, in new Editor

### ISSUE THREAD

**Issue by Casval111** [playcanvas/editor#971]
Version 1.50.2 doesn't work, in new Editor, if using wasm models. 
pc.WasmModule not exists, in version 1.50.2. 
The new Editor is not compatible with the old versions, such as 1.50.2.

**Comment by yaustar** [comment]
Unfortunately, we don't guarantee that the Editor works with all old versions of the Engine. We recommend updating the project to work with the latest version of the Engine

**Comment by willeastcott** [comment]
@Casval111 Out of interest - what is preventing you from just jumping to the latest engine version? Or at least a more recent build?
