### ISSUE TITLE
Cannot change script order in the Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#972]
Forum: https://forum.playcanvas.com/t/editor-issue-script-initialization-order-no-longer-works/29675

Change order of any scripts on a script component
Refresh the Editor
Notice that the order has not changed

https://user-images.githubusercontent.com/16639049/220059439-1f4f83c0-c943-4325-9b00-84c6225a1173.mp4

**Comment by ellthompson** [comment]
Closing this issue as a fix has been released.
