### ISSUE TITLE
Changing script order doesn't work

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#975]
Changing script order on editor doesn't work. It was working before, for some reason it doesn't save anymore.

Video : https://streamable.com/nv8fhu

**Comment by willeastcott** [comment]
@ellthompson is on the case. AFAIK, this should be resolved today. Thanks for reporting.

**Comment by willeastcott** [comment]
Closing since it's a dupe of https://github.com/playcanvas/editor/issues/972
