### ISSUE TITLE
Ability to Choose PlayCanvas Editor Version

### ISSUE THREAD

**Issue by querielo** [playcanvas/editor#976]
Currently, the PlayCanvas Editor automatically updates to the latest version. Which can cause issues for users who need to maintain a specific version for their projects or run older projects that are no longer supported by maintainers.

Therefore, it would be helpful to provide users with the ability to choose which version of the editor (and associated PlayCanvas engine version) they want to use.

For example, [After the Flood](https://playcanvas.com/project/529572/overview/after-the-flood) can no longer be launched due to compatibility issues with the latest editor/engine version.

**Comment by yaustar** [comment]
Unfortunately, to do this would require us to maintain multiple versions of the entire infrastructure as it's not just engine version related. We've discussed this internally a number of times before as we understand the frustrations that our users face with this.

New features etc require changes to the whole stack and unfortunately, we can't let the user choose a version of the platform to use.
