### ISSUE TITLE
Remove the use of deprecated functions

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#978]
Editor uses some deprecated functions from the engine, and those should be removed.

![Screenshot 2023-02-21 at 11 07 49](https://user-images.githubusercontent.com/59932779/220328777-fc41f2bd-5a09-4d52-82e8-03a776583103.png)

Risk: updating Editor to use newer API will remove compatibility with older engines that do not implement those.

**Comment by slimbuck** [comment]
Editor runs on promoted engine always, backwards compatibility shouldn't be a problem.

**Comment by willeastcott** [comment]
@mvaligursky We're now down to this:

![image](https://user-images.githubusercontent.com/697563/235908386-34518d04-087f-4b8c-98c8-95281488bb2b.png)

**Comment by willeastcott** [comment]
@mvaligursky One remaining now:

![image](https://github.com/user-attachments/assets/91d02a27-ae76-4734-94e1-bcd933cef845)

**Comment by mvaligursky** [comment]
Editor v2 fixed this one (not released yet). Closing for now.
