### ISSUE TITLE
Draco Editor Compression doesn't render models and renders in Editor view

### ISSUE THREAD

**Issue by lukastomasek** [playcanvas/editor#980]
The mesh doesn't show up in editor when Draco compression is enabled, even with the latest engine version (1.61.2)

**Asset Tasks Settings:**
<img width="426" alt="Screenshot 2023-02-22 at 4 05 10 PM" src="https://user-images.githubusercontent.com/52459545/220760064-c16c2b5a-5c66-46b9-b2a7-f19ab9be4665.png">

**Editor Preview:**
<img width="1674" alt="Screenshot 2023-02-22 at 3 57 14 PM" src="https://user-images.githubusercontent.com/52459545/220758638-8432fc26-094f-4d5b-a723-f06ec5265485.png">
**Game Preview:**
<img width="1726" alt="Screenshot 2023-02-22 at 3 57 25 PM" src="https://user-images.githubusercontent.com/52459545/220758739-07dc1067-39f6-43c6-a95c-ad1806162bfa.png">

**Comment by slimbuck** [comment]
Hi @lukastomasek,

We are aware of this issue.

It is a peculiarity of the model loader and draco module initialisation. The published game works fine, but editor and launch page doesn't always show draco meshes.

We'll hopefully have a fix for this in the next few days.

Just so you know, scenes imported with hierarchy don't suffer this issue.

Thanks!

**Comment by willeastcott** [comment]
This is now fixed. Closing.

**Comment by lukastomasek** [comment]
Thanks!
