### ISSUE TITLE
Add .webp upload support 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#991]
WebP is supported on 97.41% of devices (Safari 13 and below do not support WebP) and has significant file size savings compared to PNG and JPEG for the same quality.

https://caniuse.com/webp

From Google: https://developers.google.com/speed/webp

> WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

It is decided that we would treat it as a developer's choice to use WebP knowing the limitations rather than adding a fallback or variant option.

Areas affected:

- File upload
- Texture compression
- Asset tasks for resizing (POT, etc)
- glTF import support

**Comment by marklundin** [comment]
This has been completed
