### ISSUE TITLE
Incorrect properties descriptions on camera

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#997]
Camera component has incorrect hint descriptions for `Depth Grabpath` and `Color Grabpass` properties:

![image](https://user-images.githubusercontent.com/5677782/223861234-4d7ae49f-7b7a-4fc3-b2bb-0a1a284b760f.png)

**Comment by willeastcott** [comment]
I've merged a fix. This will be deployed in the coming days. Thanks so much for pointing this out! 🙏

**Comment by LeXXik** [comment]
@willeastcott this needs to be reopened. The descriptions were applied to the wrong attributes:
They were applied to `clearColorBuffer` and `clearDepthBuffer`, which were originally correct.

![image](https://user-images.githubusercontent.com/5677782/235732556-7901bccd-7fd0-49df-aa6b-eb7856e211de.png)
